### PR TITLE
Bump up nacos to 2.1.2

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
This is ridiculous, upgrading the nacos version causes the packaging timeout without any reason, in CI, in my local, and in my codespace machine.

**Comment by wu-sheng** [comment]
The new pom is confusing the maven?

**Comment by kezhenxu94** [comment]
> The new pom is confusing the maven?

I have no idea because the maven command just gets stuck without any useful message, even I turn on maven debug logs.

**Comment by wu-sheng** [comment]
😂😂 I never used this kind of pom file. Let's feedback to Nacos team, this at least doesn't work for us.

**Pull request closed without merging**
