### PR TITLE
Add prometheus, open-telemetry, zabbix as labels

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

We are ready for the metrics from these 3 ecosystems now.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@kezhenxu94 This seems not running in `skip` mode. All CIs are really running.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 This seems not running in `skip` mode. All CIs are really running.

Well. I missed .asf.yaml, it was not considered in skip action

**Review by ascrutae — APPROVED** [review]

**Comment by wu-sheng** [comment]
> asf.yaml

I added in this PR.

**Review by kezhenxu94 — APPROVED** [review]

**Comment by wu-sheng** [comment]
Only working after merge?

**Comment by kezhenxu94** [comment]
> Only working after merge?

Because you also modify action.yaml , which should not be skipped.

**Pull request merged**
