### PR TITLE
Fix bug that rocketmq-plugin set the wrong tag.

### PR DESCRIPTION
**Pull request by Ax1an**
- [x] Explain briefly why the bug exists and how to fix it.
  `NumberFormatException` may occur.

image

image

image

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #. 
  NO.
- [x] Update the CHANGES log.

### CODE REVIEW

**Review by wu-sheng — DISMISSED** [review]
LGTM

**Review by zifeihan — DISMISSED** [review]
LGTM

**Comment by wu-sheng** [comment]
Please don't sync the PR by yourself, we are facing limited CI resources. The PMC will take care of the approved PR one by one.

**Review by wu-sheng — APPROVED** [review]
LGTM

**Pull request merged**
