### PR TITLE
Support jvm_thread metrics

### PR DESCRIPTION
**Pull request by stalary**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
https://github.com/apache/skywalking/issues/5098
___
### New feature or improvement
- Describe the details and related test reports.
Support jvm_thread metrics

### CODE REVIEW

**Comment by stalary** [comment]
PTAL @ascrutae

**Comment by stalary** [comment]
https://github.com/apache/skywalking-data-collect-protocol/blob/24788cf41807048dcbe8dba0958688aaaf630d73/language-agent/JVMMetric.proto

**Comment by stalary** [comment]
How do I update this file? I can't update it with Git
https://github.com/apache/skywalking-data-collect-protocol/blob/24788cf41807048dcbe8dba0958688aaaf630d73/language-agent/JVMMetric.proto

**Comment by wu-sheng** [comment]
Read the doc about `git submodule`.

**Comment by stalary** [comment]
> Take a look at `ui-initialized-templates.yml`, you should add new components on the instance page, then export the new dashboard configurations, and update this file.
> 
> This file managed the default UI layout since 8.0.0. You should have used it, right?

ok, I missed it here

**Comment by stalary** [comment]
截屏2020-07-19 下午10 16 46
How can I solve this problem?

**Comment by wu-sheng** [comment]
I think this is only related to your local git submodule issue. If you are not familiar with the commands, try Sourcetree, it is very friendly to the git submodule with providing a GUI.

**Comment by stalary** [comment]
> I think this is only related to your local git submodule issue. If you are not familiar with the commands, try Sourcetree, it is very friendly to the git submodule with providing a GUI.

thanks,

**Pull request closed without merging**
