### PR TITLE
Fix the zookeeper plugin has many nodes in the cluster case

### PR DESCRIPTION
**Pull request by zhaoyuguang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
https://github.com/apache/skywalking/issues/3371
___
### Bug fix
- Bug description.
The zookeeper plugin has many nodes in the cluster case

- How to fix?
Add a sort list between the addresses list and the peer

### CODE REVIEW

**Comment by wu-sheng** [comment]
Resolves #3371

**Comment by zhaoyuguang** [comment]
> Here is the [test report](https://github.com/SkywalkingTest/agent-integration-test-report/tree/master/2019/8/zhaoyuguang/testReport-zhaoyuguang-op_zk-2019-08-29-18-21.md) and [validate logs](http://35.227.88.23:49001/job/skywalking-agent-test/257/artifact/workspace/logs/validate_2019-08-29-18-21.log)

look like also support 3.5.x, so I also add it in `Supported-list.md`

**Pull request merged**
