### PR TITLE
avoid reordering

### PR DESCRIPTION
**Pull request by IanCao**
avoid reordering

Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by IanCao** [comment]
` public static FileWriter get() {
        if (INSTANCE == null) {
            synchronized (CREATE_LOCK) {
                if (INSTANCE == null) {
                    INSTANCE = new FileWriter();
                }
            }
        }
        return INSTANCE;
    }`

this is the FileWriter double check instantiation code.

`uniqueInstance = new Singleton()` actually process in three steps
1. allocate memory for `uniqueInstance ` reference
2. initialize `uniqueInstance ` 
3. make step1 point step 2

but jvm has reorder characteristics， that order maybe change to 1，3，2
for example, 
Thread 1 process step 1 and 3
at the same time,  Thread 2 process `getUniqueInstance()`  and result is not null, but this time `uniqueInstance` stiil not be initialized.

**Comment by wu-sheng** [comment]
> but jvm has reorder characteristics， that order maybe change to 1，3，2

I am not very familiar with this `reorder`, but even this is happening, this should trigger NPE.  Because the file writer should only be accessed by one thread only. Do I miss anything?

Or are you facing NPE?

**Comment by IanCao** [comment]
yes, actually its only one thread.
im just find a double check in FileWriter when i am doing a new log implement(fluentd) 
My subconscious is that INSTANCE in double check should be volatile.  haha

**Comment by wu-sheng** [comment]
If there is no real NPE happens, and only single thread scenario, let's keep the codes unchanged, OK?

I don't want to misguide people that, this object could/is being accessed across thread. For the double check, is only the performance concern.

**Comment by IanCao** [comment]
ok

**Pull request closed without merging**
