### PR TITLE
Replace deprecated methods

### PR DESCRIPTION
**Pull request by CalvinKirs**
deprecated method replace

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@CalvinKirs all tests failed, please check

**Comment by CalvinKirs** [comment]
> @CalvinKirs all tests failed, please check

From its log, I can’t understand why e2e test fails. Can you help me?

**Comment by wu-sheng** [comment]
Have you run locally? I am guessing your changes break the codes.

**Comment by CalvinKirs** [comment]
> Have you run locally? I am guessing your changes break the codes.

I only ran my modified parts locally.

**Comment by wu-sheng** [comment]
e2e usually means, the SkyWalking backend can't boot after your changes.

**Comment by CalvinKirs** [comment]
> e2e usually means, the SkyWalking backend can't boot after your changes.

Thx, I will try locally later

**Comment by CalvinKirs** [comment]
I will finish it later

**Comment by wu-sheng** [comment]
Closing, no update in 2 weeks.

**Pull request closed without merging**
