### PR TITLE
Merge RocketBot UI as primary UI

### PR DESCRIPTION
**Pull request by wu-sheng**
Submodule update. SkyWalking-ui has been removed.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@TinyAllen @TinyAllen We need to add ASF header to RocketBot.

**Comment by JaredTan95** [comment]
CI failed，files needs to be added license as follows:

```
270 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  skywalking-ui/run.sh
  skywalking-ui/public/index.html
  skywalking-ui/babel.config.js
  skywalking-ui/tslint.json
  skywalking-ui/vue.config.js
  skywalking-ui/tsconfig.json
  skywalking-ui/.browserslistrc
  skywalking-ui/postcss.config.js
  skywalking-ui/src/assets/svg/comment-dots.svg
  skywalking-ui/src/assets/svg/search.svg
  skywalking-ui/src/assets/svg/angle-double-left.svg
  skywalking-ui/src/assets/svg/arrow-down.svg
  skywalking-ui/src/assets/svg/epic.svg
  skywalking-ui/src/assets/svg/earth.svg
  skywalking-ui/src/assets/svg/bulb.svg
  skywalking-ui/src/assets/svg/long-arrow.svg
  skywalking-ui/src/assets/svg/unstage-all.svg
  skywalking-ui/src/assets/svg/soft-unwrap.svg
  skywalking-ui/src/assets/svg/remove-all.svg
  skywalking-ui/src/assets/svg/review-warning.svg
  skywalking-ui/src/assets/svg/list-bulleted.svg
  skywalking-ui/src/assets/svg/information.svg
  skywalking-ui/src/assets/svg/repeat.svg
  skywalking-ui/src/assets/svg/list-numbered.svg
  skywalking-ui/src/assets/svg/ellipsis_h.svg
  skywalking-ui/src/assets/svg/hourglass.svg
  skywalking-ui/src/assets/svg/chart.svg
  skywalking-ui/src/assets/svg/hamburger.svg
  skywalking-ui/src/assets/svg/thumb-up.svg
  skywalking-ui/src/assets/svg/approval.svg
  skywalking-ui/src/assets/svg/comparison.svg
  skywalking-ui/src/assets/svg/mobile-issue-close.svg
  skywalking-ui/src/assets/svg/user.svg
  skywalking-ui/src/assets/svg/account.svg
  skywalking-ui/src/assets/svg/merge-request.svg
  skywalking-ui/src/assets/svg/status_closed.svg
  skywalking-ui/src/assets/svg/status_pending_borderless.svg
  skywalking-ui/src/assets/svg/commit.svg
  skywalking-ui/src/assets/svg/sort-lowest.svg
  skywalking-ui/src/assets/svg/home.svg
  skywalking-ui/src/assets/svg/file-addition-solid.svg
  skywalking-ui/src/assets/svg/status_success_solid.svg
  skywalking-ui/src/assets/svg/status_running_borderless.svg
  skywalking-ui/src/assets/svg/blame.svg
  skywalking-ui/src/assets/svg/chevron-down.svg
  skywalking-ui/src/assets/svg/emoji_smiley.svg
  skywalking-ui/src/assets/svg/overview.svg
  skywalking-ui/src/assets/svg/cancel.svg
  skywalking-ui/src/assets/svg/key-modern.svg
  skywalking-ui/src/assets/svg/tag.svg
  skywalking-ui/src/assets/svg/status_skipped.svg
  skywalking-ui/src/assets/svg/file-modified-solid.svg
  skywalking-ui/src/assets/svg/label.svg
  skywalking-ui/src/assets/svg/comments.svg
  skywalking-ui/src/assets/svg/status_warning.svg
  skywalking-ui/src/assets/svg/plus-square.svg
  skywalking-ui/src/assets/svg/angle-down.svg
  skywalking-ui/src/assets/svg/emoji_slightly_smiling_face.svg
  skywalking-ui/src/assets/svg/location-dot.svg
  skywalking-ui/src/assets/svg/doc-text.svg
  skywalking-ui/src/assets/svg/duplicate.svg
  skywalking-ui/src/assets/svg/unassignee.svg
  skywalking-ui/src/assets/svg/clear.svg
  skywalking-ui/src/assets/svg/cloud-gear.svg
  skywalking-ui/src/assets/svg/issues.svg
  skywalking-ui/src/assets/svg/terminal.svg
  skywalking-ui/src/assets/svg/file-modified.svg
  skywalking-ui/src/assets/svg/chevron-up.svg
  skywalking-ui/src/assets/svg/image-comment-light.svg
  skywalking-ui/src/assets/svg/hook.svg
  skywalking-ui/src/assets/svg/folder-open.svg
  skywalking-ui/src/assets/svg/todo-add.svg
  skywalking-ui/src/assets/svg/angle-up.svg
  skywalking-ui/src/assets/svg/substitute.svg
  skywalking-ui/src/assets/svg/question.svg
  skywalking-ui/src/assets/svg/lock.svg
  skywalking-ui/src/assets/svg/status_canceled_borderless.svg
  skywalking-ui/src/assets/svg/fire.svg
  skywalking-ui/src/assets/svg/scroll-handle.svg
  skywalking-ui/src/assets/svg/chevron-right.svg
  skywalking-ui/src/assets/svg/file-deletion.svg
  skywalking-ui/src/assets/svg/package.svg
  skywalking-ui/src/assets/svg/link.svg
  skywalking-ui/src/assets/svg/key.svg
  skywalking-ui/src/assets/svg/status_canceled.svg
  skywalking-ui/src/assets/svg/arrow-right.svg
  skywalking-ui/src/assets/svg/logo-sw.svg
  skywalking-ui/src/assets/svg/smiley.svg
  skywalking-ui/src/assets/svg/group.svg
  skywalking-ui/src/assets/svg/settings.svg
  skywalking-ui/src/assets/svg/compress.svg
  skywalking-ui/src/assets/svg/token.svg
  skywalking-ui/src/assets/svg/mail.svg
  skywalking-ui/src/assets/svg/notifications-off.svg
  skywalking-ui/src/assets/svg/shield.svg
  skywalking-ui/src/assets/svg/download.svg
  skywalking-ui/src/assets/svg/expand.svg
  skywalking-ui/src/assets/svg/spam.svg
  skywalking-ui/src/assets/svg/slight-frown.svg
  skywalking-ui/src/assets/svg/import.svg
  skywalking-ui/src/assets/svg/task-done.svg
  skywalking-ui/src/assets/svg/expand-left.svg
  skywalking-ui/src/assets/svg/double-headed-arrow.svg
  skywalking-ui/src/assets/svg/retry.svg
  skywalking-ui/src/assets/svg/sort-highest.svg
  skywalking-ui/src/assets/svg/pencil-square.svg
  skywalking-ui/src/assets/svg/angle-double-right.svg
  skywalking-ui/src/assets/svg/book.svg
  skywalking-ui/src/assets/svg/file-tree.svg
  skywalking-ui/src/assets/svg/collapse.svg
  skywalking-ui/src/assets/svg/issue-new.svg
  skywalking-ui/src/assets/svg/smart-card.svg
  skywalking-ui/src/assets/svg/marquee-selection.svg
  skywalking-ui/src/assets/svg/folder-new.svg
  skywalking-ui/src/assets/svg/question-o.svg
  skywalking-ui/src/assets/svg/dashboard.svg
  skywalking-ui/src/assets/svg/code.svg
  skywalking-ui/src/assets/svg/flag.svg
  skywalking-ui/src/assets/svg/podcast.svg
  skywalking-ui/src/assets/svg/stop.svg
  skywalking-ui/src/assets/svg/review-checkmark.svg
  skywalking-ui/src/assets/svg/issue-open-m.svg
  skywalking-ui/src/assets/svg/status_warning_borderless.svg
  skywalking-ui/src/assets/svg/work.svg
  skywalking-ui/src/assets/svg/status_notfound_borderless.svg
  skywalking-ui/src/assets/svg/folder-o.svg
  skywalking-ui/src/assets/svg/bold.svg
  skywalking-ui/src/assets/svg/soft-wrap.svg
  skywalking-ui/src/assets/svg/file-addition.svg
  skywalking-ui/src/assets/svg/status_failed.svg
  skywalking-ui/src/assets/svg/plus.svg
  skywalking-ui/src/assets/svg/level-up.svg
  skywalking-ui/src/assets/svg/warning.svg
  skywalking-ui/src/assets/svg/canceled-circle.svg
  skywalking-ui/src/assets/svg/rss.svg
  skywalking-ui/src/assets/svg/plus-square-o.svg
  skywalking-ui/src/assets/svg/scale.svg
  skywalking-ui/src/assets/svg/angle-right.svg
  skywalking-ui/src/assets/svg/bullhorn.svg
  skywalking-ui/src/assets/svg/issue-parent.svg
  skywalking-ui/src/assets/svg/abuse.svg
  skywalking-ui/src/assets/svg/close.svg
  skywalking-ui/src/assets/svg/git-merge.svg
  skywalking-ui/src/assets/svg/status_success.svg
  skywalking-ui/src/assets/svg/scroll_up.svg
  skywalking-ui/src/assets/svg/issue-child.svg
  skywalking-ui/src/assets/svg/review-list.svg
  skywalking-ui/src/assets/svg/expand-right.svg
  skywalking-ui/src/assets/svg/leave.svg
  skywalking-ui/src/assets/svg/check-circle.svg
  skywalking-ui/src/assets/svg/thumb-down.svg
  skywalking-ui/src/assets/svg/smile.svg
  skywalking-ui/src/assets/svg/issue-close.svg
  skywalking-ui/src/assets/svg/planning.svg
  skywalking-ui/src/assets/svg/status_created_borderless.svg
  skywalking-ui/src/assets/svg/fork.svg
  skywalking-ui/src/assets/svg/issue-created.svg
  skywalking-ui/src/assets/svg/staged.svg
  skywalking-ui/src/assets/svg/text-description.svg
  skywalking-ui/src/assets/svg/screen-normal.svg
  skywalking-ui/src/assets/svg/appearance.svg
  skywalking-ui/src/assets/svg/file-deletion-solid.svg
  skywalking-ui/src/assets/svg/status_success_borderless.svg
  skywalking-ui/src/assets/svg/messages.svg
  skywalking-ui/src/assets/svg/snippet.svg
  skywalking-ui/src/assets/svg/eye-slash.svg
  skywalking-ui/src/assets/svg/play.svg
  skywalking-ui/src/assets/svg/status_open.svg
  skywalking-ui/src/assets/svg/doc-new.svg
  skywalking-ui/src/assets/svg/collapse-left.svg
  skywalking-ui/src/assets/svg/assignee.svg
  skywalking-ui/src/assets/svg/table.svg
  skywalking-ui/src/assets/svg/thumbtack.svg
  skywalking-ui/src/assets/svg/status_manual_borderless.svg
  skywalking-ui/src/assets/svg/preferences.svg
  skywalking-ui/src/assets/svg/redo.svg
  skywalking-ui/src/assets/svg/issue-duplicate.svg
  skywalking-ui/src/assets/svg/admin.svg
  skywalking-ui/src/assets/svg/disk.svg
  skywalking-ui/src/assets/svg/monitor-o.svg
  skywalking-ui/src/assets/svg/status_failed_borderless.svg
  skywalking-ui/src/assets/svg/media.svg
  skywalking-ui/src/assets/svg/screen-full.svg
  skywalking-ui/src/assets/svg/status_notfound.svg
  skywalking-ui/src/assets/svg/volume-up.svg
  skywalking-ui/src/assets/svg/issue-external.svg
  skywalking-ui/src/assets/svg/template.svg
  skywalking-ui/src/assets/svg/star.svg
  skywalking-ui/src/assets/svg/status_created.svg
  skywalking-ui/src/assets/svg/monitor-lines.svg
  skywalking-ui/src/assets/svg/status_scheduled_borderless.svg
  skywalking-ui/src/assets/svg/unlink.svg
  skywalking-ui/src/assets/svg/labels.svg
  skywalking-ui/src/assets/svg/unapproval.svg
  skywalking-ui/src/assets/svg/image-comment-dark.svg
  skywalking-ui/src/assets/svg/spinner.svg
  skywalking-ui/src/assets/svg/emoji_smile.svg
  skywalking-ui/src/assets/svg/applications.svg
  skywalking-ui/src/assets/svg/status_scheduled.svg
  skywalking-ui/src/assets/svg/slight-smile.svg
  skywalking-ui/src/assets/svg/comment-next.svg
  skywalking-ui/src/assets/svg/log.svg
  skywalking-ui/src/assets/svg/credit-card.svg
  skywalking-ui/src/assets/svg/pencil.svg
  skywalking-ui/src/assets/svg/doc-image.svg
  skywalking-ui/src/assets/svg/clock.svg
  skywalking-ui/src/assets/svg/status_pending.svg
  skywalking-ui/src/assets/svg/issue-open.svg
  skywalking-ui/src/assets/svg/dumbbell.svg
  skywalking-ui/src/assets/svg/eye.svg
  skywalking-ui/src/assets/svg/mobile.svg
  skywalking-ui/src/assets/svg/location.svg
  skywalking-ui/src/assets/svg/external-link.svg
  skywalking-ui/src/assets/svg/car.svg
  skywalking-ui/src/assets/svg/live-preview.svg
  skywalking-ui/src/assets/svg/nature.svg
  skywalking-ui/src/assets/svg/pipeline.svg
  skywalking-ui/src/assets/svg/dotted-circle.svg
  skywalking-ui/src/assets/svg/profile.svg
  skywalking-ui/src/assets/svg/arrow-up.svg
  skywalking-ui/src/assets/svg/ellipsis_v.svg
  skywalking-ui/src/assets/svg/remove.svg
  skywalking-ui/src/assets/svg/time-out.svg
  skywalking-ui/src/assets/svg/filter.svg
  skywalking-ui/src/assets/svg/italic.svg
  skywalking-ui/src/assets/svg/comment.svg
  skywalking-ui/src/assets/svg/doc-code.svg
  skywalking-ui/src/assets/svg/calendar.svg
  skywalking-ui/src/assets/svg/clear-all.svg
  skywalking-ui/src/assets/svg/notifications.svg
  skywalking-ui/src/assets/svg/push-rules.svg
  skywalking-ui/src/assets/svg/license.svg
  skywalking-ui/src/assets/svg/error.svg
  skywalking-ui/src/assets/svg/quote.svg
  skywalking-ui/src/assets/svg/collapse-right.svg
  skywalking-ui/src/assets/svg/upload.svg
  skywalking-ui/src/assets/svg/logo.svg
  skywalking-ui/src/assets/svg/bookmark.svg
  skywalking-ui/src/assets/svg/rocket.svg
  skywalking-ui/src/assets/svg/tablet.svg
  skywalking-ui/src/assets/svg/unstaged.svg
  skywalking-ui/src/assets/svg/merge-request-close-m.svg
  skywalking-ui/src/assets/svg/information-o.svg
  skywalking-ui/src/assets/svg/status_manual.svg
  skywalking-ui/src/assets/svg/status_running.svg
  skywalking-ui/src/assets/svg/lock-open.svg
  skywalking-ui/src/assets/svg/branch.svg
  skywalking-ui/src/assets/svg/star-o.svg
  skywalking-ui/src/assets/svg/angle-left.svg
  skywalking-ui/src/assets/svg/merge.svg
  skywalking-ui/src/assets/svg/login-bg.svg
  skywalking-ui/src/assets/svg/food.svg
  skywalking-ui/src/assets/svg/todo-done.svg
  skywalking-ui/src/assets/svg/tanuki.svg
  skywalking-ui/src/assets/svg/status_skipped_borderless.svg
  skywalking-ui/src/assets/svg/scroll_down.svg
  skywalking-ui/src/assets/svg/history.svg
  skywalking-ui/src/assets/svg/folder.svg
  skywalking-ui/src/assets/svg/tachometer.svg
  skywalking-ui/src/assets/svg/users.svg
  skywalking-ui/src/assets/svg/merge-request-close.svg
  skywalking-ui/src/assets/svg/timer.svg
  skywalking-ui/src/assets/svg/monitor.svg
  skywalking-ui/src/assets/svg/go-back.svg
  skywalking-ui/src/assets/svg/chevron-left.svg
  skywalking-ui/src/assets/svg/weight.svg
  skywalking-ui/src/assets/svg/stage-all.svg
  skywalking-ui/src/assets/svg/talic.svg
  skywalking-ui/src/assets/svg/issue-block.svg
  skywalking-ui/src/assets/svg/heart.svg

```

**Comment by kezhenxu94** [comment]
I think svg files should be excluded from the checking(license header) list



> Sent from [mini-github](https://github.com/kezhenxu94/mini-github)

**Comment by wu-sheng** [comment]
Svg files are image files from us. The they could be added

**Pull request merged**
