### PR TITLE
improve MethodsAroundInterceptor API:add MethodAroundContext over the Interceptor …

### PR DESCRIPTION
**Pull request by qxo**
Please answer these questions before submitting pull request

## Why submit this pull request?
- New feature provided
- Improve performance

## Related issues
___
### New feature or improvement
-  MethodsAroundInterceptor should have MethodAroundContext  over the Interceptor 
so we can pass current span,then we change `ContextManager#stopSpan` to `ContextManager#stopSpan(span)` -- for speed up and fail-fast
ref: https://github.com/apache/skywalking/pull/3068

static MethodsAroundInterceptor also need to be support

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why do we need to change this? How much performance does it bring to the agents?

I am not just asking benchmark, I am asking about in the real scenario tests

**Comment by qxo** [comment]
1. The change TraceAnnotationMethodInterceptor  in this pr is the use case 
2. After change of TraceAnnotationMethodInterceptor  the code more strong (fail-fast)
and it could improve the performance  if we grid of the invoke  for ThreadLocal 
It's another pr I want to do:)

**Comment by wu-sheng** [comment]
I do know it is related to performance. My question is how much. 

Change API will break many things, including document etc. especially we have many plugins today. I have found any real performance issue by using ThreadLocal. Actually, most of plugins wouldn't use this.

**Comment by qxo** [comment]
> I do know it is related to performance. My question is how much.
> 
> Change API will break many things, including document etc. especially we have many plugins today. I have found any real performance issue by using ThreadLocal. Actually, most of plugins wouldn't use this.

The change of API is for the future, and it's compatible with the exist plugin (  without change the plugin ).

**Comment by wu-sheng** [comment]
All these changes, including #3124 , need to be proved necessary. Also need to have multiple PMC/committors support that. I would not make the call here.

You should know, as OSS project, we only add or change API when it is necessary, especially these are all open APIs. You are bringing the extra maintain payload to the community.

Personally, I would support this change.

-1 from me.

cc @apache/skywalking-committers if anyone who wants this, please `+1 explicitly. And explain why and what are the scenarios.

**Comment by wu-sheng** [comment]
Ask committer and PMC, id they support, open issue to discuss. We could not change core API directly.

**Comment by qxo** [comment]
I agree the API should not change if necessary
On my point of view, the API should  change  for the future 

This PR try to  make the API strong: pass span over MethodAroundContext 
 and then call `ContextManager#stopSpan(span)`   -- the fail-fast version of stopSpan

combine with #3124( "span carrry TracingContext" , reduce call ThreadLocal  if not required ) will improve  the performance  additionally

**Comment by wu-sheng** [comment]
Yes, I agree the two PRs will improve the performance, but we need to be careful about that. SkyWalking today is making the project more stable by several version releases. So, if we noticed serious performance concerns, we prefer to keep unchanged. Also, we haven't received the report, our agent core(not perfect :) for sure) causes the performance issue to target applications.

**Pull request closed without merging**
