### PR TITLE
sync ui

### PR DESCRIPTION
**Pull request by aeolusheath**
synchronize skywalking-ui

### CODE REVIEW

**Comment by wu-sheng** [comment]
You should update to rocketbot latest commit id. What do you do? I am seeing conflicts.

**Comment by wu-sheng** [comment]
You should fork and clone the repo. Do submodule update. Then, go into skywalking-ui folder, pull the latest of UI master branch. At this point, you will notice, maim repo changlog will show submodule commitid changed, the new one matching the UI master branch commitid.

**Comment by wu-sheng** [comment]
All these could be learn from any doc or blog talking about git submodule.

**Comment by aeolusheath** [comment]
@wu-sheng 

 I fork this repo and go to skywalking ui folder 

then

`git checkout -b origin b817e9542cf5928309518540022e74f0b42ac987`  

b817e9542cf5928309518540022e74f0b42ac987 is the lastest commit in skywalking ui

then git push and pull request.

is there something wrong?

**Comment by wu-sheng** [comment]
git pull origin master 
Then check the main repo git diff. And you need to merge skywalking master with your local change.

**Comment by wu-sheng** [comment]
From your fork, you are pointing to old commit id. Even don't include your own.

image

And I just merged several PR at UI, please sync again.

**Comment by wu-sheng** [comment]
The latest one is 8e2628a36dba0037e90f12cea8a4753deb1b7b2c

https://github.com/apache/skywalking-rocketbot-ui/commit/8e2628a36dba0037e90f12cea8a4753deb1b7b2c

image

**Comment by aeolusheath** [comment]
@wu-sheng I have pushed the latest ～

**Comment by wu-sheng** [comment]
@aeolusheath Yes. You are on the right way. I will wait for a moment. @TinyAllen told me, he has another fix to do. 

Please wait for that, and update the submodule again.

Glad you know how to do this, and because of this, your GitHub account will begin to show on the main repo contributors list.

**Comment by wu-sheng** [comment]
@aeolusheath You could sync again.

**Comment by aeolusheath** [comment]
@wu-sheng  pushed agian，big thanks for your help 🍺

**Pull request merged**
