### PR TITLE
Add HBase client plugin

### PR DESCRIPTION
**Pull request by jang675953**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by zhaoyuguang** [comment]
Why close？

**Comment by jang675953** [comment]
this plugin has not be  tested,click error, wait a few days when i test it.



------------------ 原始邮件 ------------------
发件人: "于玉桔"<notifications@github.com>; 
发送时间: 2019年4月26日(星期五) 晚上10:33
收件人: "apache/skywalking"<skywalking@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [apache/skywalking] 增加HBase插件 (#2539)




Why close？

**Comment by kezhenxu94** [comment]
> this plugin has not be tested,click error, wait a few days when i test it.
> […](#)

Feel free to leave it open to let others know that you're working on it :)

**Comment by wu-sheng** [comment]
And change title and description in English, please.

**Comment by jang675953** [comment]
ok， I will open it again.




------------------ 原始邮件 ------------------
发件人: "kezhenxu94"<notifications@github.com>; 
发送时间: 2019年4月26日(星期五) 晚上11:02
收件人: "apache/skywalking"<skywalking@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [apache/skywalking] 增加HBase插件 (#2539)



 
this plugin has not be tested,click error, wait a few days when i test it.
 …
  
Feel free to leave it open to let others know that you're working on it :)
 
&mdash;

**Comment by wu-sheng** [comment]
After your local test passed.

You need to submit test case to here https://github.com/SkyAPMTest/agent-auto-integration-testcases

You could find the document there too.

**Comment by jang675953** [comment]
ok，thank you




------------------ 原始邮件 ------------------
发件人: "吴晟 Wu Sheng"<notifications@github.com>; 
发送时间: 2019年4月26日(星期五) 晚上11:16
收件人: "apache/skywalking"<skywalking@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [apache/skywalking] Add HBase client plugin (#2539)




After your local test passed.
 
You need to submit test case to here https://github.com/SkyAPMTest/agent-auto-integration-testcases
 
You could find the document there too.

**Comment by jang675953** [comment]
I test it locally,but the component on ui and peer  is empty,i think i should need more time to test it .
there is need more testcase to add.
image
image

**Comment by jang675953** [comment]
image

**Comment by wu-sheng** [comment]
Why close? Need a new one?

**Comment by jang675953** [comment]
At this moment, I have no idea to support hbase-client2.x's async api，and  the 1.x's test  is not complete.




------------------ 原始邮件 ------------------
发件人: "吴晟 Wu Sheng"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 晚上7:39
收件人: "apache/skywalking"<skywalking@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [apache/skywalking] Add HBase client plugin (#2539)




Why close? Need a new one?

**Comment by wu-sheng** [comment]
You could choose. This isn't requirement that you must support both. Is 1.0 plugin still ongoing?

**Comment by jang675953** [comment]
I'm learning  docker and how to build a hbase image.



------------------ 原始邮件 ------------------
发件人: "吴晟 Wu Sheng"<notifications@github.com>; 
发送时间: 2019年5月6日(星期一) 晚上7:56
收件人: "apache/skywalking"<skywalking@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [apache/skywalking] Add HBase client plugin (#2539)




You could choose. This isn't requirement that you must support both. Is 1.0 plugin still ongoing?
 
&mdash;

**Comment by wu-sheng** [comment]
I think hbase should have official docker image and docker-compose. Does it?

**Comment by jang675953** [comment]
There is no an offical image from apache,I found some image,but it  does not work well.





------------------ 原始邮件 ------------------
发件人: "吴晟 Wu Sheng"<notifications@github.com>; 
发送时间: 2019年5月6日(星期一) 晚上8:47
收件人: "apache/skywalking"<skywalking@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [apache/skywalking] Add HBase client plugin (#2539)




I think hbase should have official docker image and docker-compose. Does it?

**Pull request closed without merging**
