### PR TITLE
provide an agent plugin for aliyun rocketmq

### PR DESCRIPTION
**Pull request by shook2012**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] New feature provided
- Related issues
___
### New feature or improvement
provide an agent plugin to support aliyun rocketmq service

### CODE REVIEW

**Comment by wu-sheng** [comment]
Make sure CI works. And how we test it? Otherwise, I would recommend to host source and jar in your personal repo, and add a pointer link in ours. Make sense?

**Comment by shook2012** [comment]
ok

**Comment by wu-sheng** [comment]
Add the link to supported list and agent optional plugin pages. Thanks

**Comment by wu-sheng** [comment]
Related #3630

**Pull request closed without merging**
