### PR TITLE
Add windows powershell quick start guide

### PR DESCRIPTION
**Pull request by Superskyyy**
Pending to merge after I verify the script deployment works from this https://github.com/apache/skywalking-website/pull/690

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
The script has been hosted on website. Please verify and continue.

**Comment by Superskyyy** [comment]
> The script has been hosted on website. Please verify and continue.

Sure, gonna test that after work.

**Comment by Superskyyy** [comment]
Ok it didn't work, gotta fix on the website side first.

**Comment by Superskyyy** [comment]
Rover doc is having dead links

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Yes, we changed them as 0.6 release is a new one.
We will fix the links.

**Pull request merged**
