### PR TITLE
Add some defensive codes for NPE and bump up Kubernetes client version to expose exception stack trace

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
The Kubernetes-client swallowed the exception stack, I bump up the version (minimal) to include https://github.com/kubernetes-client/java/pull/1164 , also added some defensive codes for NPE

**Review by wu-sheng — COMMENTED** [review]
I think you missed dependency check file, and License update

**Review by wu-sheng — APPROVED** [review]
LGTM.

@EvanLjp As k8s-client has been upgraded to 10.0. Your #5778 could continue.

**Comment by kezhenxu94** [comment]
> LGTM.
> 
> @EvanLjp As k8s-client has been upgraded to 10.0. Your #5778 could continue.

That's not the case, I've checked that issue and the bug kubernetes-client/java#1344 is only included in 11.0, and there are API changes affected our uses in 11.0 so I just keep it under 11.0, when dealing with #5778 the k8s-client needs another upgrade and some APIs adjustments

**Pull request merged**
