### PR TITLE
[test/plugin] support plugin testcases run with optional/bootstrap plugins

### PR DESCRIPTION
**Pull request by dmsolr**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
This is PR for supporting plugin testcases run with optional/bootstrap plugins through configuration.yml.
The optional name of configuration is `RunningMode` which has 3 values, `default`,`with_optional`,`with_bootstap`. The default is `default` when the configuration omitted.

### CODE REVIEW

**Comment by dmsolr** [comment]
FYI, @zhaoyuguang

**Comment by dmsolr** [comment]
> LGTM. How to indicate to add only one/serveral specific optional or bootstrap plugins?

Not support yet. I wonder if this is necessary.

**Comment by wu-sheng** [comment]
Actually, only that make sense. Even more than this one. Think in this way, more and more optional plugins added, one day a new optional contributed, all codes are good. But will add one span to many other cases. Then what do you expect?

**Comment by dmsolr** [comment]
> Actually, only that make sense. Even more than this one. Think in this way, more and more optional plugins added, one day a new optional contributed, all codes are good. But will add one span to many other cases. Then what do you expect?

I got it. I will do this later.

**Comment by wu-sheng** [comment]
> I got it. I will do this later.

Once you have that, I recommend you revert these two options, by providing specific plugin selector options, if you feel making sense too.

**Pull request merged**
