### PR TITLE
Upgrade the etcd4j version to solve the memory leak problem

### PR DESCRIPTION
**Pull request by YczYanchengzhe**
### Fix <bug description or the bug issue number or bug issue link>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it. When we use etcd as the registry center of oap, netty reported a memory leak error. Check the version of etcd4j and found that this problem has been fixed in the latest version. It is recommended that skywalking can also upgrade the version of etcd4j

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
We are checking the dependency libraries, so, as you want to upgrade the dependency, you need to update
1. LICENSE, https://github.com/apache/skywalking/blob/master/dist-material/release-docs/LICENSE#L328
2. Dependency checklist, https://github.com/apache/skywalking/blob/master/tools/dependencies/known-oap-backend-dependencies.txt
3. Dependency checklist 2, https://github.com/apache/skywalking/blob/master/tools/dependencies/known-oap-backend-dependencies-es7.txt

About (2) and (3), please notice the tool checking all dependency libraries. If your change actually affects more than one library, (1) should be updated too.

**Comment by wu-sheng** [comment]
@YczYanchengzhe And your changelogs are including unexpected things, please make that clear.

**Comment by YczYanchengzhe** [comment]
Regarding the issue of dependency, I will modify it. What exactly did you mean by the malicious code? How can I fix it~

**Comment by wu-sheng** [comment]
> What exactly did you mean by the malicious code? 

Where I said about `malicious codes`? Something is being misread?

**Comment by wu-sheng** [comment]
Oh, I think I know what do you misread. I mean your commits https://github.com/apache/skywalking/pull/6832/commits. They include only and unrelated things. Not you had submitted real codes.
In the open-source, we usually expect the commits only to include things related to this specific PR.

**Comment by wu-sheng** [comment]
@YczYanchengzhe Any update?

**Comment by YczYanchengzhe** [comment]
I understand what you mean. I'll close this commit and pull one again

**Pull request closed without merging**
