### PR TITLE
add python components

### PR DESCRIPTION
**Pull request by alonelaval**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [* ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

[add Flask plugin](https://github.com/apache/skywalking-python/pull/31)

### CODE REVIEW

**Comment by alonelaval** [comment]
> Does this require server side mapping?

yes.

**Comment by wu-sheng** [comment]
Then you need to update the config file and add the mapping. You only change the component definition.

**Comment by kezhenxu94** [comment]
> > Does this require server side mapping?
> 
> yes.

@alonelaval you misunderstood the meaning, we don't need server mapping for the two components actually

**Comment by alonelaval** [comment]
> > > Does this require server side mapping?
> > 
> > 
> > yes.
> 
> @alonelaval you misunderstood the meaning, we don't need server mapping for the two components actually

OK

**Pull request merged**
