### PR TITLE
Add spring cloud gateway 3.x plugin

### LINKED ISSUE #6492: NPE is thrown in SkyWalking 8.4.0 with gateway plugin
here is the config!

pom.xml
       <dependency>
           <groupId>org.apache.skywalking</groupId>
           <artifactId>apm-toolkit-logback-1.x</artifactId>
           <version>8.4.0</version>
       </dependency>

logback_spring.xml

    <appender name="grpc_log" class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender">
    </appender>
   <root level="info">
        <appender-ref ref="CONSOLE_APPENDER"/>
        <appender-ref ref="ROOT_APPENDER"/>
        <appender-ref ref="grpc_log" />
    </root>

the skywalking  with the default config,but when the gateway startup,the console tips the error like this:

[TID:N/A]  [] 2021-03-05 09:33:02.492:[ERROR] [reactor-http-nio-2:22985] [r.u.Loggers$Slf4JLogger:error:319]--> Operator called default onErrorDropped
java.lang.NullPointerException: null
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.webclient.WebFluxWebClientInterceptor$1.accept(WebFluxWebClientInterceptor.java:85)
	at org.apache.skywalking.apm.plugin.spring.webflux.v5.webclient.WebFluxWebClientInterceptor$1.accept(WebFluxWebClientInterceptor.java:82)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:262)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:252)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:197)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:213)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:255)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:406)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:243)
	at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:339)
	at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:148)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:180)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$TcpClientSubscriber.onError(HttpClientConnect.java:353)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onError(PooledConnectionProvider.java:523)
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:427)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$5(SimpleDequePool.java:309)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:172)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:304)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:254)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

all the pom.xml like this,need help thanks!

[pom.zip](https://github.com/apache/skywalking/files/6087652/pom.zip)

### PR DESCRIPTION
**Pull request by wallezhang**
### Add an agent plugin to support <Spring Cloud Gateway 3.x>
- [x] Add a test case for the new plugin, refer to [the doc](https://github.com/apache/skywalking/blob/master/docs/en/guides/Plugin-test.md)
- [x] Add a component id in [the component-libraries.yml](https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml)
- [ ] Add a logo in [the UI repo](https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets)

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #6492 #6237 .
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wallezhang** [comment]
@wu-sheng Please take a review. I have tested the unit test and scenario test locally.

**Comment by wu-sheng** [comment]
@wallezhang Could you cross-check #6880 with @ralphgj ?
Both of you submit pull requests today, I want you two working together, as you both have experiences of contributing to SkyWalking. And maybe these 2 plugins are for different scenarios. Because I can see #6880 is just bumping the version, and this PR actually requires another new plugin test case.

**Comment by wu-sheng** [comment]
I think you missed the updates about
1. Plugin-list.md checking in the CI, which has failed.
2. Supported-list.md is an important documentation.

**Comment by wallezhang** [comment]
> I think you missed the updates about
> 
> 1. Plugin-list.md checking in the CI, which has failed.
> 2. Supported-list.md is an important documentation.

Yes, I will update it.

**Comment by wu-sheng** [comment]
> > @wallezhang Could you cross-check #6880 with @ralphgj ?
> > Both of you submit pull requests today, I want you two working together, as you both have experiences of contributing to SkyWalking. And maybe these 2 plugins are for different scenarios. Because I can see #6880 is just bumping the version, and this PR actually requires another new plugin test case.
> 
> Haven't checked the PR yet. I will have a look now.

Thanks, you should more specialized than us.
I also pinged @ascrutae to recheck.

**Comment by wallezhang** [comment]
@wu-sheng I have checked the PR. I think we are doing the same thing, which is compatible with Spring Cloud Gateway version 3.x. The `HttpClientFinalizer` class in `reactor-netty` that Spring Cloud Gateway relied on, has change its constructor parameter type, and need to redefine the constructor interceptor point, so I think creating a new plugin is good to version management.

**Comment by wallezhang** [comment]
> > @wu-sheng I have checked the PR. I think we are doing the same thing, which is compatible with Spring Cloud Gateway version 3.x. The `HttpClientFinalizer` class in `reactor-netty` that Spring Cloud Gateway relied on, has change its constructor parameter type, and need to redefine the constructor interceptor point, so I think creating a new plugin is good to version management.
> 
> Agree about a new plugin. And do you check why you are using another way to build plugin test scenario?

I use the same way as `gateway-2.1.x-scenario` except the spring cloud gateway version.

**Pull request merged**
