### PR TITLE
Update cancel.yaml to use ASF GHA

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>. NO NEED
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md). NO NEED

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Thanks @potiuk for quick response, btw, do you need an ASF release for that GHA to be used?

**Review by wu-sheng — APPROVED** [review]
Cool!!! Thanks @potiuk for updating this so quickly.

**Comment by potiuk** [comment]
No need for a release @kezhenxu94. This is not software officially "released" by ASF the idea is that its origin must be controlled by the ASF committers.

**Comment by wu-sheng** [comment]
> do you need an ASF release for that GHA to be used?

From my understanding, if we use internally(inside ASF), this is not a strict required. As this is not included in a source release :) But if they are going to post on the airflow website as a thing called official release(or similar), then it is .

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
One comment here. I thought about the new policy and consequences, and I think it makes much more sense for each projects to keep their own copies of the actions. I am still waiting for the infra/Greg to comment on it but I raised my concerns here about using such actions cross-project:

 https://lists.apache.org/thread.html/rfc3269829edc672f928d8304d7b0aa38d1d2a5f5cb177af95e98a1e5%40%3Cusers.infra.apache.org%3E

Happy if you also join the discussion, I'd love to hear what others think about it.

**Comment by kezhenxu94** [comment]
> One comment here. I thought about the new policy and consequences, and I think it makes much more sense for each projects to keep their own copies of the actions. I am still waiting for the infra/Greg to comment on it but I raised my concerns here about using such actions cross-project:
> 
> https://lists.apache.org/thread.html/rfc3269829edc672f928d8304d7b0aa38d1d2a5f5cb177af95e98a1e5%40%3Cusers.infra.apache.org%3E
> 
> Happy if you also join the discussion, I'd love to hear what others think about it.

Thanks. I'm also watching that thread, will reply there

**Comment by wu-sheng** [comment]
@potiuk I think your(airflow) fork is fine, then SkyWalking doesn't need a new one, from my understanding of ASF policy. 
2 key points,
1. INFRA is making sure the action is security, and doesn't include write operation.
2. Airflow and SkyWalking are in the same foundation, we are just 2 groups of people interesting in different tech directions, but basically, we are sharing branding(ASF) and source code IPs.

**Comment by potiuk** [comment]
> 1. INFRA is making sure the action is security, and doesn't include write operation.

This is not happening now. INFRA is not involved in review of the actions. And some of those actions actually perform write operations.

> 2. Airflow and SkyWalking are in the same foundation, we are just 2 groups of people interesting in different tech directions, but basically, we are sharing branding(ASF) and source code IPs.

The problem is that I (more any on the commiters/PMCs of Airflow) we are not reviewing all the commits in those repos. I simply cloned someone else's action repo (in this case it is mine, so I am pretty sure I know what I am doing but there are other actions that aren't mine). So I just cloned the repo, In my case, I am reviewing only the particular commit I am referring to in 'apache-airflow' but someone could add malicious code in any of the previous commits - I have no physical possibility to review all that code, but I want to keep the history so that I can bring new changes, review and switch to new versions.

**Comment by wu-sheng** [comment]
> This is not happening now. INFRA is not involved in review of the actions. And some of those actions actually perform write operations.

Yes, I know they haven't. I mean, all these things are related to this purpose :)

> The problem is that I (more any on the commiters/PMCs of Airflow) we are not reviewing all the commits in those repos. I simply cloned someone else's action repo (in this case it is mine, so I am pretty sure I know what I am doing but there are other actions that aren't mine). So I just cloned the repo, In my case, I am reviewing only the particular commit I am referring to in 'apache-airflow' but someone could add malicious code in any of the previous commits - I have no physical possibility to review all that code, but I want to keep the history so that I can bring new changes, review and switch to new versions.

We(SkyWalking) are only using the `cancel` task for now, so, I could say this is safe, right :). That is my point of now doing a duplicated clone, specifically for this case.

**Comment by potiuk** [comment]
> We(SkyWalking) are only using the cancel task for now, so, I could say this is safe, right :). That is my point of now doing a duplicated clone, specifically for this case.

For now yes I assume you reviewed my code :). I am more into creating a good policy that anyone could follow.

**Pull request merged**
