### PR TITLE
Add percentile tests in e2e test.

### LINKED ISSUE #4594: Some E2E test cases did not verify the percentile

### PR DESCRIPTION
**Pull request by Humbertzhang**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #4594
Add percentile tests in e2e test.

- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/c2141978d1039375598a32418b75161a78da22c1/CHANGES.md).

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
Really appreciate the great work, we finally get this verifications back, waiting for the results

**Comment by wu-sheng** [comment]
@kezhenxu94 When we have, please consider to use CLI with expected template files to replacing the Java codes

**Comment by kezhenxu94** [comment]
> @kezhenxu94 When we have chance, please consider to use CLI with expected template files to replacing the Java codes

I like the idea but that requires much more extra work than expected, I'd rather create another issue to track that, other contributors who are interested can join me

**Comment by kezhenxu94** [comment]
Some are kind of unstable, let's hold this PR a little bit, @Humbertzhang and I will have a look at those unstable tests

**Comment by kezhenxu94** [comment]
Some are kind of unstable, let's hold this PR a little bit, @Humbertzhang and I will have a look at those unstable tests

**Comment by wu-sheng** [comment]
Yes, CLI thing is just a idea, not relate to this.

**Review by kezhenxu94 — APPROVED** [review]
Merging, rerun 2 times and all passed stably

**Pull request merged**
