### PR TITLE
Bump up infra e2e version and fix istio cases

### PR DESCRIPTION
**Pull request by kezhenxu94**
Also serve as an example that cases use different Kubernetes versions

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
Once e2e passed.

**Comment by wu-sheng** [comment]
This seems not working.

**Review by wu-sheng — DISMISSED** [review]

**Comment by wu-sheng** [comment]
Strange, TLS case fails 3 times(after I retried).

**Comment by kezhenxu94** [comment]
> Strange, TLS case fails 3 times(after I retried).

The mTLS cert is expired... I have extended the expiration date to 100 years

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
