### PR TITLE
fix influxdb bug while setting influxdb connection response format as InfluxDB.ResponseFormat.JSON

### PR DESCRIPTION
**Pull request by cuiweiwei**
### Fix <#5945>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly about why the bug exists and how to fix it.
When use influxdb as storage of Skywalking, due to certain limitations, only can use json as influxdb connection response format .Some errors will occur as show in issue.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<#5945>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
Read the PR I pointed to you. There is more details besides this code change.

**Comment by cuiweiwei** [comment]
When set json as influxdb response format, it will use scientific counting to convert long type to double, but BasicTrace use String type as its startTime, then error occured. The changed code in this pr can solve this problem, and it doesn't affect anything while using msgpack.

**Comment by wu-sheng** [comment]
Could you make CI passed?

**Comment by wu-sheng** [comment]
I want to remind you is this,

> JSON does not support integers above 2^53
SkyWalking has many long fields, which in Java could be 2^63-1

**Comment by wu-sheng** [comment]
How do you activate the JSON format? I remember there is hardcode about `msgpack`. Please recheck.

**Comment by cuiweiwei** [comment]
I have the needs to activate json ,maybe other people have the same need，so i changed the code and re-packaged the project to build image. To say the least, even if someone uses msgpack instead of json, the changed code in this pr will have a positive effect. Compare TraceQuery class to ProfileThreadSnapshotQuery class, the set method of SegmentRecord takes different params, perhaps the author was negligent at the time.

**Comment by wu-sheng** [comment]
To be more clear, I mean this, https://github.com/apache/skywalking/blob/6ff562334044446657ba4df44b98b5f3897864ef/oap-server/server-storage-plugin/storage-influxdb-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/influxdb/InfluxClient.java#L78

If this is hard coded, how JSON format works?

**Comment by cuiweiwei** [comment]
I know you mean here. However, users may find that the default implementation will fail when they use a special version of influxDB, and error logs finally point to this : InfluxDB.ResponseFormat.MSGPACK. Then they find InfluxDBFactory.connect method support both JSON and MSGPACK, and JSON is even the default. so they changed MSGPACK to JSON，error occured. Users may wonder, clearly org. Influxdb. InfluxDBFactory support json, why is wrong

**Comment by wu-sheng** [comment]
My question is, is JSON format working already? If so, this PR should make that part configurable like the previous I linked. And related doc should be updated too.

**Comment by cuiweiwei** [comment]
Yes, according to my tests, it is ok. I have made that part configurable.

**Comment by wu-sheng** [comment]
Same as before, we need to verify. The easiest way to uploading the screenshots of every pages, or a recorded videos.

**Comment by cuiweiwei** [comment]
image
image
image
image
image
image
image
image
image
image

**Comment by wu-sheng** [comment]
Pending on @dmsolr 's review.

**Review by dmsolr — APPROVED** [review]
LGTM, Thanks.

**Pull request merged**
