### PR TITLE
fix shardingsphere plugin span to DB type

### PR DESCRIPTION
**Pull request by swift1911**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.
shardingsphere plugin dosn't set the span type to DB.So it show that the unknown span in the web.

image

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by swift1911** [comment]
> As a local span, it should not be as a DB layer.

Displaying unknown on the page is bad for the user experience. It will make user confuse about the Span.Do you think we should display the type of span is Local rather than Unknown?

**Comment by wu-sheng** [comment]
This thing is called `span layer`. There is no value for the local span.

```Java
public enum SpanLayer {
    DB(1), RPC_FRAMEWORK(2), HTTP(3), MQ(4), CACHE(5);
}
```

**Comment by swift1911** [comment]
> This thing is called `span layer`. There is no value for the local span.
> 
> ```java
> public enum SpanLayer {
>     DB(1), RPC_FRAMEWORK(2), HTTP(3), MQ(4), CACHE(5);
> }
> ```

Yes.There is no value for the local span.Do you think we should add a span type for local span because there are many local span just like SpringAsync,Shardingsphere shows unknown.

**Comment by wu-sheng** [comment]
> Do you think we should add a span type for local span because there are many local span

To say what? Local?

**Pull request closed without merging**
