### PR TITLE
Fix storage-influxdb-plugin serviceCode query

### PR DESCRIPTION
**Pull request by GerryYuan**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/c2141978d1039375598a32418b75161a78da22c1/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please update the `CHANGES log`.

**Comment by dmsolr** [comment]
@GerryYuan Thank you.

**Review by wu-sheng — APPROVED** [review]
I helped with fixing the changelog.

**Review by dmsolr — APPROVED** [review]

**Comment by GerryYuan** [comment]
> I helped with fixing the changelog.



> @GerryYuan Thank you.

**Comment by GerryYuan** [comment]
> @GerryYuan Thank you.

**Comment by GerryYuan** [comment]
> I helped with fixing the changelog.

ok

> @GerryYuan Thank you.

🙂

**Pull request merged**
