### PR TITLE
MOD: update submodule

### PR DESCRIPTION
**Pull request by snakorse**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

___
### New feature or improvement
- Sync the protocol submodule update.

### CODE REVIEW

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/pull/4847 This PR changes submodule, but not your commit id. Let's see whether there is conflict after that one merged.

**Comment by wu-sheng** [comment]
@snakorse Please update the submodule again, this conflict is only caused by another merge.

**Comment by snakorse** [comment]
> @snakorse Please update the submodule again, this conflict is only caused by another merge.

Maybe I missed something, I can't find any updates in the protocol submodule.
I try to merge master branch of this repo to my forked repo, but the conflict still exists, so I reset the merge.

How should I do with the 'update the submodule again'? SOS

**Comment by wu-sheng** [comment]
Simplest way is, close this one, and recreate a new branch based on new master. Then is should be easier.

**Comment by snakorse** [comment]
okay.

**Pull request closed without merging**
