### PR TITLE
Fix the kafka consumer configuration override bug.

### PR DESCRIPTION
**Pull request by wyt**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/changelog/docs/en/changes/changes.md).

When I try the configuration below to set different consumer group for oap server, it doesn't work.
Still the default group in the program.

```yaml
kafka-fetcher:
  selector: ${SW_KAFKA_FETCHER:default}
  default:
    bootstrapServers: ${SW_KAFKA_FETCHER_SERVERS:192.168.101.1:9092}
    ......
    kafkaConsumerConfig:
      enable.auto.commit: true
      group.id: test-group-mysql
```

The reason is that there is an order problem when setting in the code:

```java
properties = new Properties();
properties.putAll(config.getKafkaConsumerConfig());
properties.setProperty(ConsumerConfig.GROUP_ID_CONFIG, config.getGroupId());
properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, config.getBootstrapServers());
```

I don't know if this is by design or a mistake in itself.
Please confirm.

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by dmsolr** [comment]
In fact, it totally is not a bug. To simplify configuration, we prefect users to configure as follows:
```yaml
kafka-fetcher:
  selector: ${SW_KAFKA_FETCHER:default}
  default:
    bootstrapServers: ${SW_KAFKA_FETCHER_SERVERS:192.168.101.1:9092}
    groupId: ${SW_KAFKA_FETCHER_GROUP_ID: skywalking}
```

Not to configure `kafkaConsumerConfig`, this is for advance configure.

**Comment by wu-sheng** [comment]
@dmsolr I checked the codes, it seems we really provide this `kafkaConsumerConfig`. Once we did, I think the changed behavior is at least more sensible.

**Comment by dmsolr** [comment]
make sense.
Yes, users can configure `BOOTSTRAP_SERVERS_CONFIG` and `GROUP_ID_CONFIG ` by KafkaFetchConfig(base) and KafkaConsumerConfig(advance).

**Comment by wu-sheng** [comment]
Yes, once they could be override, make `kafkaConsumerConfig` to override single configuration key seems a better pratice.

**Pull request merged**
