### PR TITLE
Remove fake required workflows

### PR DESCRIPTION
**Pull request by kezhenxu94**
Follow up #8691 , remove those fake jobs that was only used to pass the CI

### CODE REVIEW

**Comment by wu-sheng** [comment]
`Required` is controlled by the GHA file, rather than settings, now?

**Comment by kezhenxu94** [comment]
> `Required` is controlled by the GHA file, rather than settings, now?

I had changed the required context name to `Required` in last PR and now we can use this single name to aggregate all mandatory jobs, so no need to have several fake jobs,

**Comment by wu-sheng** [comment]
I see. Then we need this gets merged before other PRs.

**Comment by kezhenxu94** [comment]
> I see. Then we need this gets merged before other PRs.

Actually not necessary, the fake `Required` workflow is also added in last PR so all new PRs can be merged, this PR is only to remove those unused ones

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
