### PR TITLE
Add docker:ulimits config

### PR DESCRIPTION
**Pull request by aderm**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Support to configure the ulimit parameter of the Linux environment, such as maximum locked-in-memory address space (KB).
- this conf will be used in elasticsearch-5.x-scenario test.
ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

### CODE REVIEW

**Comment by wu-sheng** [comment]
@dmsolr Please make sure, we still could control the memory of containers at runtime. Memory is limited resources in test env.

**Comment by wu-sheng** [comment]
@aderm Please recheck whether these configs are necessary in test env. We are not running in production.

**Comment by dmsolr** [comment]
as far as I'm concerned, these are unnecessary. If you have other considerations, please point out. Welcome to discuss deeply. :)

**Comment by wu-sheng** [comment]
I will keep this open in 2 days, if this hasn't been proved, then close.

**Comment by aderm** [comment]
singe node env, i user es6.7.1，ES checked， log show WARN tips，but not effect startup.

**Pull request closed without merging**
