### PR TITLE
Bump up Zipkin and Zipkin lens UI dependency to 2.24.0

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Review by wankai123 — DISMISSED** [review]

**Comment by kezhenxu94** [comment]
No sure but you might need to regenerate the zipkin-license from the new Lens dependency's package.json and package-lock.json， if they have new dependencies or versions changes in Lens, this is needed.

**Comment by wu-sheng** [comment]
> No sure but you might need to regenerate the zipkin-license from the new Lens dependency's package.json and package-lock.json， if they have new dependencies or versions changes in Lens, this is needed.

Could you provide which command I should run? I thought it is a part of CI check.

**Comment by wu-sheng** [comment]
Do you mean I need to copy the lock file again from the Zipkin repo?

**Comment by kezhenxu94** [comment]
> Do you mean I need to copy the lock file again from the Zipkin repo?

You have to regenerate the zipkin-LICENSE from the package.json and package-lock.json in https://github.com/openzipkin/zipkin/tree/2.24.0/zipkin-lens, this is no part of CI because they are using npm 14 and we are using npm 16. Also, even we copy their package.json and package-lock.json, we have to manually copy those 2 files every time we upgrade the zipkin-lens version. So I'd just check in the generated ziplin-LICENSE file instead of check in the 2 large files

**Comment by wu-sheng** [comment]
@kezhenxu94 Updated.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
