### PR TITLE
Agent service discorvery

### PR DESCRIPTION
**Pull request by EvanLjp**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] New feature provided

- Related issues
https://github.com/apache/skywalking/issues/5063

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by EvanLjp** [comment]
I will add unit tests later, thanks for review first

**Comment by EvanLjp** [comment]
fixing unit test,please wait for a moment

**Comment by wu-sheng** [comment]
Don't change the backend serive url config, it will break many deployed system. Please don't do that.

**Comment by EvanLjp** [comment]
> I think I mentioned before, neither service discovery tech should not be bounded in the agemt core level. If you want to contribute this feature, you need to put it as an optional plugin only. Take a look on Kafka transport plugin and zipkin branch.
@wu-sheng 
it is designed as a plugin mode:
image

**Comment by EvanLjp** [comment]
so i cannot extension with service mode , i would be add a new extension interface ?

**Comment by wu-sheng** [comment]
The concern is, the default config changed. And new backend service path added. This would be very confused. How to write plugin doc would be an issue.

**Comment by EvanLjp** [comment]
> The concern is, the default config changed. And new backend service path added. This would be very confused. How to write plugin doc would be an issue.

how about this mode:
origin backend url is as default.the extension discovery is in Service Discovery 
image

**Comment by wu-sheng** [comment]
By thinking the PR and Kafka transport PR, I prefer you work on a new PR.
Introduce a new SPI service, called ConfigInitService. All plugins and core could provide their services. Then you could separate the current Config in the core and different plugins.
Notice, all config keys should be kept as much as possible.

What do you think? @dmsolr @kezhenxu94 @arugal @EvanLjp

Let's make that decision first, then back to this feature.

**Comment by EvanLjp** [comment]
@wu-sheng  the PR is for agent discovery

**Comment by wu-sheng** [comment]
@EvanLjp Yes, this one and #4847 show, the config of different plugins have been keeping added into the core Config. I want to remove this first. That is the reason I talked about ConfigInitService(not a BootService).

**Comment by EvanLjp** [comment]
i open a new issue  first

**Comment by wu-sheng** [comment]
Once we have this feature, this plugin will be more elegant, because there will be no code changed in the agent core, purely plugin. Same as the Kafka transport plugin.

**Comment by EvanLjp** [comment]
I wonder if the plug-in configuration needs to be refactored,for example mysql

**Comment by wu-sheng** [comment]
> I wonder if the plug-in configuration needs to be refactored,for example mysql

At the code level, yes. But you still could keep the config name unchanged. You just create more Config classes in different plugins.

**Comment by EvanLjp** [comment]
no porblem , i would like be to open a new issue first

**Comment by wu-sheng** [comment]
I think you could improve this PR now. I have set up the new Config initialization core.

**Comment by EvanLjp** [comment]
ok

**Comment by wu-sheng** [comment]
Do we still plan to do this? I think we discussed, cliemt load balance is not a very good way. It is hard to be balaned.

**Comment by EvanLjp** [comment]
i read the oap code and agent code. oap transform data from one oap server to another oap server is get client form a grpc client pool. so oap server can load balance.
why not we still maintain the mode in agent.
we create a grpc clients manager,when transform data ,we random get a client

**Comment by EvanLjp** [comment]
> Do we still plan to do this? I think we discussed, cliemt load balance is not a very good way. It is hard to be balaned.

i don't think keep alive one by one is a good way.Don't you think this is skywalking's current problem?Why don't we try to optimize?

**Comment by wu-sheng** [comment]
Rechecking, whether this feature should be or is planned to continue? It has been no update for a month.

**Comment by EvanLjp** [comment]
may be close is a good choose, thx

**Pull request closed without merging**
