### PR TITLE
Support trace path ignore with patterns match.

### PR DESCRIPTION
**Pull request by JaredTan95**
### Bring agent trace ignore feature to OAP and support dynamic update patterns.
- [x] Update the documentation to include this new feature.
- [x] Tests(including UT, IT, E2E) are added to verify the new feature.

- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Before reviewing the codes, I want to ask for the scenarios about why need this at the backend. What is the case we are opening the backend-side ignorance feature?

**Comment by JaredTan95** [comment]
like sampling logic, we can sample on the agent-side or backend-side. 
So, we can ignore trace on agent source, or we can do this on the backend side. The 2nd scenario is that when the storage resources are limited and there is no way to dynamically update the agent side configurations to ignore more traces currently. 
And I looking forward to the [agent side dynamic update feature](https://github.com/apache/skywalking/issues).

**Comment by wu-sheng** [comment]
@mrproliu Do you have any progress to share about #6114 ? 

@JaredTan95 Will this feature still exist if 6114 completes? This seems a little duplicate.

**Comment by mrproliu** [comment]
> @mrproliu Do you have any progress to share about #6114 ?
> 
> @JaredTan95 Will this feature still exist if 6114 completes? This seems a little duplicate.

Not yet. I'm still working on the Zabbix adaptor. After the Zabbix adaptor finished, I could start the agent side dynamic configuration.

**Comment by JaredTan95** [comment]
> @mrproliu Do you have any progress to share about #6114 ?
> 
> @JaredTan95 Will this feature still exist if 6114 completes? This seems a little duplicate.

I don't think there's a duplicate, the scope of the agent side is a single instance, and the scope of the backend is the entire system. Both of them can exist.

**Comment by wu-sheng** [comment]
> I don't think there's a duplicate, the scope of the agent side is a single instance, and the scope of the backend is the entire system. Both of them can exist.

That is another thing I want to discuss. The current implementation has performance concern. Because basically, ignorance should be service-oriented. For this feature, we need to be very carefully about the performance impact. 
Because `cost` * N agent instances ==> `cost` of M OAP instances. N is much bigger than M.

**Comment by wu-sheng** [comment]
And once you have the rules across services, the rules must check all endpoints of all services.

**Comment by wu-sheng** [comment]
Note, base on CI
```
2021-01-10T13:12:44.7190051Z [INFO] Results:
2021-01-10T13:12:44.7190577Z [INFO] 
2021-01-10T13:12:44.7191080Z [ERROR] Failures: 
2021-01-10T13:12:44.7192309Z [ERROR]   TraceIgnorePathWatcherTest.testDynamicUpdate:64 
2021-01-10T13:12:44.7194630Z Expected: is "/ignore/path/**"
2021-01-10T13:12:44.7195246Z      but: was ""
```
The test is not working. But let's make the design clear first.

**Comment by JaredTan95** [comment]
> Note, base on CI
> 
> ```
> 2021-01-10T13:12:44.7190051Z [INFO] Results:
> 2021-01-10T13:12:44.7190577Z [INFO] 
> 2021-01-10T13:12:44.7191080Z [ERROR] Failures: 
> 2021-01-10T13:12:44.7192309Z [ERROR]   TraceIgnorePathWatcherTest.testDynamicUpdate:64 
> 2021-01-10T13:12:44.7194630Z Expected: is "/ignore/path/**"
> 2021-01-10T13:12:44.7195246Z      but: was ""
> ```
> 
> The test is not working. But let's make the design clear first.

okay

**Comment by wu-sheng** [comment]
@JaredTan95 It seems CDS(https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/ConfigurationDiscoveryService.proto) is on the way faster than I thought.

Refer #6114 

If we have that, do you think still be necessary for the backend ignorance mechanism?

**Comment by JaredTan95** [comment]
I'm also thinking about this logic these days, as you said, service-oriented.

like providing a configuration for the service and service's ignore trace path as follows:

```yaml
servcie-a:
    - /your/path/1/**
    - /your/path/2/**
servcie-b:
    - /your/path/1/**
```

But, this way may have a performance impact when items too much in this config file. If CDS is WIP,  I prefer that filter at the source of the agent data. So, I'll close this PR.

**Pull request closed without merging**
