### PR TITLE
Test for mongo3.x support version

### PR DESCRIPTION
**Pull request by harvies**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
We could remove some minor versions(last one) to ease the test env pressure. OK?

**Comment by wu-sheng** [comment]
Actually, we should do this for all plugins. We already cost too much. Do you want to help on this?

**Comment by harvies** [comment]
> We could remove some minor versions(last one) to ease the test env pressure. OK?

Ok

**Comment by harvies** [comment]
> Actually, we should do this for all plugins. We already cost too much. Do you want to help on this?

no problem

**Comment by harvies** [comment]
> We could remove some minor versions(last one) to ease the test env pressure. OK?

Like this?
support-version.list
3.4.3
3.5.0
3.6.4
3.7.1
3.8.2
3.9.1
3.10.2
3.11.2
3.12.7

**Comment by wu-sheng** [comment]
Yes! And you could keep this style in all other plugins.

**Comment by wu-sheng** [comment]
And, once you are going to remove the tested version, please send mail to dev@skywalking.apache.org to notify all developers. (You need to send mail to dev-subscribe@skywalking.apache.org first and follow the reply to confirm the subscription).

**Comment by wu-sheng** [comment]
Please do that in another pull request. I am going to merge this first.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
