### PR TITLE
Fix the so11y latency of persistence execution latency not correct in ElasticSearch storage

### PR DESCRIPTION
**Pull request by kezhenxu94**
The ES persistence execution is now asynchronous and the execution
latency only counts the time to insert the requests into the bulk
processor, instead of the time after the requests are flushed into the
storage, this patch fixes that issue.

There is the same issue in prepare latency but that needs more changes
so I'll leave it to another pull request.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>. NO
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
before
Screen Shot 2021-11-20 at 15 57 35
 
after
Screen Shot 2021-11-20 at 15 57 56

**Review by wu-sheng — APPROVED** [review]
LGTM @LIU-WEI-git

**Comment by kezhenxu94** [comment]
Push another commit to fix the unit test

**Comment by wu-sheng** [comment]
Yes, noticed too.

**Comment by kezhenxu94** [comment]
Should be good now

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
