### PR TITLE
Refactor version attribute to a property.

### PR DESCRIPTION
**Pull request by damonxue**
Refactor version attribute to a property.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why do we do this? This version is bumped up automatically by maven command.

**Comment by damonxue** [comment]
@wu-sheng After release a new version, we should bump the snapshot version to a new snapshot version by a commit that had to  change many pom files.
[last version commit](https://github.com/apache/skywalking/commit/18008aa6b24ada6602d9c73e1a9d19b6105d8b59)

**Comment by wu-sheng** [comment]
Yes, that change is automatically done through a script, rather than manually. 
This is a typical and official release work.

**Comment by damonxue** [comment]
> Yes, that change is automatically done through a script, rather than manually. This is a typical and official release work.

Ok, I know, it's a CI?

**Comment by wu-sheng** [comment]
No, it is done by release manager with a common maven command.

**Comment by damonxue** [comment]
> No, it is done by release manager with a common maven command.

Ok, i kown, it's versions-maven-plugin command.

**Pull request closed without merging**
