### PR TITLE
Fix potential concurrent problems and tune performance

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] Bug fix
- [ ] New feature provided
- [x] Improve performance

Changes are:

- Fix potential concurrent problems in:

https://github.com/apache/skywalking/blob/72e6888ae3ff4df5d6c36084cdce44ad7d8423a2/oap-server/server-alarm-plugin/src/main/java/org/apache/skywalking/oap/server/core/alarm/provider/RunningRule.java#L127-L131

composite operations are not atomic and not thread-safe;

- Extract fields to avoid creating new objects in every request, reducing overhead:

https://github.com/apache/skywalking/blob/72e6888ae3ff4df5d6c36084cdce44ad7d8423a2/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/DurationUtils.java#L156-L178

Built-in `SimpleDateFormat` is not thread-safe so the `org.joda.time.format.DateTimeFormatter` is adopted

### CODE REVIEW

**Comment by arugal** [comment]
Hi, `TIMEOUT` is not used, please modify it together.

https://github.com/apache/skywalking/blob/72e6888ae3ff4df5d6c36084cdce44ad7d8423a2/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/TraceSegmentServiceClient.java#L48

**Comment by wu-sheng** [comment]
@arugal It is used. https://github.com/apache/skywalking/blob/72e6888ae3ff4df5d6c36084cdce44ad7d8423a2/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/TraceSegmentServiceClient.java#L92

And what is the relationship with this PR?

**Comment by arugal** [comment]
> @arugal It is used.
> 
> https://github.com/apache/skywalking/blob/72e6888ae3ff4df5d6c36084cdce44ad7d8423a2/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/TraceSegmentServiceClient.java#L92
> 
> And what is the relationship with this PR?

Not used, just trying to get a ride.

**Comment by wu-sheng** [comment]
>Not used, just trying to get a ride.

Send a pull request if you want to remove it. This is not related to this PR change. It is legacy code

**Pull request merged**
