### PR TITLE
Using PowerMockito to mock System.getent;

### PR DESCRIPTION
**Pull request by flycash**
Now, I read the document of PowerMockito and find the way to mock system class's static method.
So I remove the reflection code. I think it would be better to use PowerMockito and it can avoid the problem of compatability between difference OS and platform.

see [EnvUtilsTest failed](https://github.com/apache/skywalking/pull/2570)

- Why submit this pull request?
- [X] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@liuhaoyang What do you think? Which one do you prefer?

**Comment by wu-sheng** [comment]
I think you should continue open appveyor to avoid this in next time, no matter which PR you think it is better.

**Comment by flycash** [comment]
It seems that the configuration of appveyor has some mistakes. In fact, I didn't find the config file appveyor.yml int root directory. 
Do we need to add the configuration?

**Comment by wu-sheng** [comment]
@liuhaoyang is working on that, the PR is on the way.

**Comment by wu-sheng** [comment]
@flycash The appveyor setting file has been merged. Could you open the test in your PR, and let's wait it pass.

**Comment by wu-sheng** [comment]
I have sync your branch, you should have it now.

**Pull request merged**
