### PR TITLE
Optimize  Channels

### PR DESCRIPTION
**Pull request by CalvinKirs**
Optimize the initialization size of Channels(returns a power of two sizes for the given target capacity.)
Use bit computing to improve computing efficiency

<!-- ==== 📈 Remove this line WHEN AND ONLY WHEN you're improving the performance, follow the checklist 👇 ====
### Improve the performance of <class or module or ...>
- [ ] Add a benchmark for the improvement, refer to [the existing ones](https://github.com/apache/skywalking/blob/master/apm-commons/apm-datacarrier/src/test/java/org/apache/skywalking/apm/commons/datacarrier/LinkedArrayBenchmark.java)
- [ ] The benchmark result.
```text
<Paste the benchmark results here>

### CODE REVIEW

**Comment by wu-sheng** [comment]
> Optimize the initialization size of Channels(returns a power of two sizes for the given target capacity.)
> Use bit computing to improve computing efficiency

What is the context of this change? Are you really facing the performance issue of a channel mod?

**Comment by CalvinKirs** [comment]
Deeply thanks for your review,I just think this can be modified. For example, Netty's HashedWheelTimer or Java's HashMap all use this method. Although the readability is relatively poor, the performance can be improved a bit.  What do you think?

**Comment by CalvinKirs** [comment]
> > Optimize the initialization size of Channels(returns a power of two sizes for the given target capacity.)
> > Use bit computing to improve computing efficiency
> 
> What is the context of this change? Are you really facing the performance issue of a channel mod?

Deeply thanks for your review,I just think this can be modified. For example, Netty's HashedWheelTimer or Java's HashMap all use this method. Although the readability is relatively poor, the performance can be improved a bit.WDYT?

**Comment by wu-sheng** [comment]
> > > Optimize the initialization size of Channels(returns a power of two sizes for the given target capacity.)
> > > Use bit computing to improve computing efficiency
> > 
> > 
> > What is the context of this change? Are you really facing the performance issue of a channel mod?
> 
> Deeply thanks for your review,I just think this can be modified. For example, Netty's HashedWheelTimer or Java's HashMap all use this method. Although the readability is relatively poor, the performance can be improved a bit.WDYT?

I will think about it, but basically, I prefer to use https://github.com/LMAX-Exchange/disruptor to implement another version of the current buffer for the OAP. That project exists and is widely used, if you like to improve the queue performance, I would like to recommend you to follow that way.

**Comment by CalvinKirs** [comment]
> > > > Optimize the initialization size of Channels(returns a power of two sizes for the given target capacity.)
> > > > Use bit computing to improve computing efficiency
> > > 
> > > 
> > > What is the context of this change? Are you really facing the performance issue of a channel mod?
> > 
> > 
> > Deeply thanks for your review,I just think this can be modified. For example, Netty's HashedWheelTimer or Java's HashMap all use this method. Although the readability is relatively poor, the performance can be improved a bit.WDYT?
> 
> I will think about it, but basically, I prefer to use https://github.com/LMAX-Exchange/disruptor to implement another version of the current buffer for the OAP. That project exists and is widely used, if you like to improve the queue performance, I would like to recommend you to follow that way.

Thank you very much, I will think about the specific design, but the time may be a little longer, I am a beginner at SkyWalking😄

**Comment by kezhenxu94** [comment]
If the PR is not ready for merge, please don't frequently update the branch, it's wasting the CI resources

**Comment by CalvinKirs** [comment]
> 如果PR尚未准备好合并，请不要频繁更新分支，这会浪费CI资源



> If the PR is not ready for merge, please don't frequently update the branch, it's wasting the CI resources

😭Thanks for your reminder.I will pay more attention to them next time

**Comment by wu-sheng** [comment]
> > If the PR is not ready for merge, please don't frequently update the branch, it's wasting the CI resources
> 
> 😭Thanks for your reminder.I will pay more attention to them next time

Seems we have #6747 in track, should we close this?

**Comment by CalvinKirs** [comment]
> > > If the PR is not ready for merge, please don't frequently update the branch, it's wasting the CI resources
> > 
> > 
> > 😭Thanks for your reminder.I will pay more attention to them next time
> 
> Seems we have #6747 in track, should we close this?

yeah, I will close it.

**Pull request closed without merging**
