### PR TITLE
Add plug-ins supporting resteasy4. x

### PR DESCRIPTION
**Pull request by shenzhenwei-hub**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by shenzhenwei-hub** [comment]
add 'resteasy-server-4.x-plugin' module in 'resteasy-plugin' module to support resteasy4.x

**Review by wu-sheng — COMMENTED** [review]
You need to follow plugin dev doc, the integration test is required. Could you read the doc and follow the last test step?

**Comment by wu-sheng** [comment]
@shenzhenwei-hub Do you have any progress?

**Comment by wu-sheng** [comment]
Closing because of no update.

**Pull request closed without merging**
