### PR TITLE
Fix wrong time bucket on attached event

### PR DESCRIPTION
**Pull request by mrproliu**
Fix the wrong time bucket on the attached event, otherwise, the event will write to the monthly index in ES storage.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
This seems a thing could be covered by e2e.

**Review by wankai123 — APPROVED** [review]

**Comment by mrproliu** [comment]
> This seems a thing could be covered by e2e.

Do you mean using e2e to check the index name or time bucket value?

**Comment by wu-sheng** [comment]
I think this can't be read if the time bucket is wrong, right?

**Comment by mrproliu** [comment]
> I think this can't be read if the time bucket is wrong, right?

No, I have done the code research. When we query the records, we just use the alias name, such as `records-all`, the wrong index name will be `records-all-YYYYMM`. But for the long term, the data cannot be queried, because we have the `TTL` mechanism to delete the wrong and older indexes. 
In the E2E, unless we query it for a long time, so we cannot find this kind of problem.

**Comment by wankai123** [comment]
> > I think this can't be read if the time bucket is wrong, right?
> 
> No, I have done the code research. When we query the records, we just use the alias name, such as `records-all`, the wrong index name will be `records-all-YYYYMM`. But for the long term, the data cannot be queried, because we have the `TTL` mechanism to delete the wrong and older indexes. In the E2E, unless we query it for a long time, so we cannot find this kind of problem.

I think we should query like this:
```java
        final SearchResponse response = getClient().search(
            new TimeRangeIndexNameGenerator(
                IndexController.LogicIndicesRegister.getPhysicalTableName(SegmentRecord.INDEX_NAME),
                startSecondTB,
                endSecondTB
            ), search.build());
```

**Comment by wu-sheng** [comment]
Yes, we should use physical indices to query, it has much better performance.

**Comment by mrproliu** [comment]
Sure, but for the attached event query, we need to calculate all of the spans to get the start/end time. If the event timestamp does not contain in the span timestamp range(such as has offset between span and event), It may not be queried in some extreme situations.

**Comment by wu-sheng** [comment]
You reminded me, I think there are some things wrong with the SpanAttachedEventRecord annotation about BanyanDB.

Please use `@BanyanDB.GlobalIndex` for the trace ID. And we need to think about the `@SeriesID`

**Comment by wu-sheng** [comment]
For `SampledStatus4xxTraceRecord` and others, please move `@BanyanDB.SeriesID(index = 0)` to entity ID.

**Review by wu-sheng — DISMISSED** [review]

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
