### PR TITLE
Completing the storage interface document

### PR DESCRIPTION
**Pull request by HarryFQ**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Seems you are using an old branch including some unexpected commit logs. I will squash them. Next time, please use a clean branch to submit pull request.

**Comment by HarryFQ** [comment]
> Seems you are using an old branch including some unexpected commit logs. I will squash them. Next time, please use a clean branch to submit pull request.

Okay, thanks for the reminder.

**Comment by wu-sheng** [comment]
Why closed?

**Comment by HarryFQ** [comment]
> Why closed?
Too many submission logs, resubmit.

**Pull request closed without merging**
