### PR TITLE
Remove `matchedCounter` from `HttpUriRecognitionService#feedRawData`

### PR DESCRIPTION
**Pull request by wu-sheng**
…vice#feedRawData`.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

According to @Superskyyy implementation on R3, this counter doesn't help on the server side.

### CODE REVIEW

**Review by Superskyyy — DISMISSED** [review]

**Comment by wu-sheng** [comment]
@Superskyyy I did the following change according to your feedback

* Remove patterns from `HttpUriRecognitionService#feedRawData` and add max 10 candidates of raw URIs for each pattern.

**Comment by Superskyyy** [comment]
LGTM, waiting for ci to finish.

**Review by Superskyyy — DISMISSED** [review]

**Comment by Superskyyy** [comment]
Mesh1.7.1 seems still failing

**Comment by Superskyyy** [comment]
I'm now building this PR and testing with R3

**Review by Superskyyy — APPROVED** [review]

**Pull request merged**
