### PR TITLE
[test/plugin] add Jenkinsfile-Agent-Test-4

### PR DESCRIPTION
**Pull request by dmsolr**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
We should maintain a workload list doc in the plugin test doc. Listing all tests, execution time and add recommend group and payload when new user comes.

**Comment by kezhenxu94** [comment]
The refactored Jenkins orchestration should be hopefully available later, and maybe we don't need workload 4

**Comment by wu-sheng** [comment]
> The refactored Jenkins orchestration should be hopefully available later, and maybe we don't need workload 4

When you are ready, we could switch. @kezhenxu94

**Comment by dmsolr** [comment]
> The indentation looks odd, mixing spaces and tabs

I will reformat after passed.

**Pull request merged**
