### PR TITLE
fix the issue #3512

### PR DESCRIPTION
**Pull request by YoungHu**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
#3512 
___
### Bug fix
- bug description
 see the issue desc

- How to fix?
  see the code change

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is the difference? Could you post the document of Elasticsearch?

**Comment by dmsolr** [comment]
The `totalHits` means the number of hit documents. The `getHits().length` means the numbe of recalled documents.

**Comment by wu-sheng** [comment]
Thanks for explanation. I would say both ways should be same in the theory. Because ID should be unique in the global always.

**Comment by wu-sheng** [comment]
Based on the design, the id is unique, then if hint more than one is being sure a bug. And this change could cover it up. I would recommend don't change in this way. But try to find out there are duplicated IDs.

So, I tagged this as won't fix and is closing this.

**Pull request closed without merging**
