### PR TITLE
do not direct send after the first aggregation to reduce the network …

### PR DESCRIPTION
**Pull request by whfjam**
Do not direct send after the first aggregation to reduce the network  traffic and reduce the oap-server's load
In my own project i made it a core config , but i don't know how to do it in the new version as my skywalking version is 8.0.1

### Improve the performance of <org.apache.skywalking.oap.server.core.analysis.worker.MetricsAggregateWorker>
- [ ] Add a benchmark for the improvement, refer to [the existing ones](https://github.com/apache/skywalking/blob/master/apm-commons/apm-datacarrier/src/test/java/org/apache/skywalking/apm/commons/datacarrier/LinkedArrayBenchmark.java)
- [x] The benchmark result.
```text
In my situation, about 150 applications with 4 oap-server(Mixed mode) nodes(8G16C) on line, and 700G segments one day , it would reduce my network traffic from 200Mbps to 100-150Mbps and reduce the oap-server's load from 7 to 4
```
- [ ] Links/URLs to the theory proof or discussion articles/blogs. <links/URLs here>

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Hi, this solution was discussed years ago, I can't remember where. 

**We don't do this now**, because the data would not be refreshed to 2nd level aggregation, then last dozens packages of metrics would NOT show up anymore until there is new data coming, which could be very confusing, especially when you do baseline testing or local testing.
Think you this way, you are doing a local test, and send 10+ segment to OAP, then nothing happens.

**Comment by wu-sheng** [comment]
If you want to hold data for longer, you have to use some timer mechanism to refresh the cache if there is no incoming data recently. This would not be an easy coding model, and you have to add some kinds of lock, like Persistent Timer doing.

**Comment by whfjam** [comment]
> you

Yes I see, I have not thought about that，still I think it would be a great improvement about performance , I will try to make it work about what you had mentioned.

**Comment by honganan** [comment]
> > you
> 
> Yes I see, I have not thought about that，still I think it would be a great improvement about performance , I will try to make it work about what you had mentioned.

I'm very interested in your solution and I'm facing the same bottleneck. Would you share your code if it has been verified works by PR or else type?

**Comment by whfjam** [comment]
> bottleneck

in my production environment i just change it not to send directly after aggregation，just use interval send such as 500ms， it won't meat that problem because of in production environment the visit will not stop

**Comment by honganan** [comment]
> > bottleneck
> 
> in my production environment i just change it not to send directly after aggregation，just use interval send such as 500ms， it won't meat that problem because of in production environment the visit will not stop

thanks for your idea.

**Comment by wu-sheng** [comment]
As this PR has no update for a long time, I am going to take over the ownership and finish the remaining half.

**Pull request closed without merging**
