### PR TITLE
Update .env

### PR DESCRIPTION
**Pull request by myie9**
make docker can run ok

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
This docker file is not for downloading from docker hub.
This is for local build.

**Comment by kezhenxu94** [comment]
Duplicate of https://github.com/apache/skywalking/pull/9680

**Comment by myie9** [comment]
> * [ ]  If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #.
> *

it can not run when local run  docker compose

**Comment by wu-sheng** [comment]
Again, it is only used when you have built the image locally, not using the images on the DockerHub.

**Pull request closed without merging**
