### PR TITLE
Add hacktoberfest topic

### PR DESCRIPTION
**Pull request by Superskyyy**
The topic is required to participate in the Hacktoberfest event. 

I suppose some ASF automation will pick this change up and update our repo setting?  

I also added a `hacktoberfest` label to the GitHub discussions (well, issues and discussions share the same labels) and opened a new category to gather related ideas/conversations. Ideas should go into the discussions section, only concrete tasks will turn into issues.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]

**Comment by kezhenxu94** [comment]
> I suppose some ASF automation will pick this change up and update our repo setting?

Yes, Apache Infra automation read `.asf.yaml` and update the settings.

**Comment by Superskyyy** [comment]
Cool! So fast, it's already there lol.

**Comment by wu-sheng** [comment]
How long this label is expected to exist?

**Comment by Superskyyy** [comment]
> How long this label is expected to exist?

Precisely 1 month, then the event ends. This event occurs every year in October.

**Comment by wu-sheng** [comment]
Please add a TODO issue to remember this label from repo after the event ends

**Comment by Superskyyy** [comment]
Ok！

**Pull request merged**
