### PR TITLE
fix spring data redis usercase NPE

### PR DESCRIPTION
**Pull request by zhaoyuguang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
https://github.com/apache/skywalking/issues/2616
___
### Bug fix
- Bug description.
In this example, using `spring-data-redis`, LettuceConnectionFactory::afterPropertiesSet will create a new ClientOptions, this has no peer
image
image

- How to fix?
Monitor changes to the ClientOptions property in AbstractRedisClient.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@zhaoyuguang Do we need to update the integration test case for this?

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang Do we need to update the integration test case for this?

The current lettuce-scenario is using lettuce-core.jar, and the bug issue is using spring-data-redis.

**Comment by wu-sheng** [comment]
@zhaoyuguang I see. Then do we need new case? Or just do code review?

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang I see. Then do we need new case? Or just do code review?

Here is the compatibility of the transformation program, first of all, there is a problem, the old test cases have no cluster use cases, I first add cluster use cases on the old test cases, and then test, whether it is compatible.

**Pull request merged**
