### PR TITLE
minor: Add SBOM to the project.

### PR DESCRIPTION
**Pull request by CalvinKirs**
### <Feature description>
This issue aims to publish SBOM artifacts along with the other Apache projects.

https://cwiki.apache.org/confluence/display/COMDEV/SBOM
Here is an article to give some context.

https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/

Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).

We can use one of the Maven plugin, [CycloneDX maven plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin), a lightweight software bill of materials (SBOM) standard designed for use in application security contexts and supply chain component analysis.

https://maven.apache.org/plugins/index.html#misc

The expected results
```
calvinkirs@CalvinKirss-MBP skywalking % ls -al ~/.m2/repository/org/apache/skywalking/ai-pipeline/10.1.0-SNAPSHOT/                               
total 1120
drwxr-xr-x@ 10 calvinkirs  staff     320 May 16 14:37 .
drwxr-xr-x@  5 calvinkirs  staff     160 May 16 14:44 ..
-rw-r--r--@  1 calvinkirs  staff     297 May 16 14:37 _remote.repositories
-rw-r--r--@  1 calvinkirs  staff  239294 May 16 14:37 ai-pipeline-10.1.0-SNAPSHOT-cyclonedx.json
-rw-r--r--@  1 calvinkirs  staff  209337 May 16 14:37 ai-pipeline-10.1.0-SNAPSHOT-cyclonedx.xml
-rw-r--r--@  1 calvinkirs  staff   91426 May 16 14:37 ai-pipeline-10.1.0-SNAPSHOT.jar
-rw-r--r--@  1 calvinkirs  staff     257 May 16 14:21 ai-pipeline-10.1.0-SNAPSHOT.jar.lastUpdated
-rw-r--r--@  1 calvinkirs  staff    4200 May 16 13:54 ai-pipeline-10.1.0-SNAPSHOT.pom
-rw-r--r--@  1 calvinkirs  staff    1138 May 16 14:37 maven-metadata-local.xml
-rw-r--r--@  1 calvinkirs  staff     245 May 16 14:21 resolver-status.properties
calvinkirs@CalvinKirss-MBP skywalking % 
```
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think the root question about this is why rather than how.

**Comment by CalvinKirs** [comment]
> > The Security team has set up an experimental [DependencyTrack](https://dependencytrack.org/) instance at https://security-tools-ec2-va.apache.org/. If upload SBOMs to this tool, you can use its interface to discover whether there are any current advisories for dependencies of your project. You should be able to log in with your apache.org id (but note this authentication method is experimental).↳
> 
> From this, it seems only about dependency CVE detection.↳

Yes, this application is designed for supply chain component analysis. It typically retrieves publicly available CVE information from sources like NVD to assess whether dependent components are vulnerable to CVEs.

**Comment by wu-sheng** [comment]
I am fine to add as it doesn't affect much. Just if this tool is not going to report that to private mail list or somewhere automatically, I am high doubting who is going to watch a UI page from time to time.

**Comment by CalvinKirs** [comment]
> I think the root question about this is why rather than how.↳

SBOM enables better software composition tracking since ISVs (and their customers) can monitor the security of their application post-deployment, and identify the potential impact of any new vulnerabilities. 

While SBOMs cannot be used to directly solve software attacks, the information they provide is extremely useful for identifying and mitigating potential vectors of attack, such as vulnerabilities.

**Comment by CalvinKirs** [comment]
> I am fine to add as it doesn't affect much. Just if this tool is not going to report that to private mail list or somewhere automatically, I am high doubting who is going to watch a UI page from time to time.↳
Most dependency component vulnerabilities do not pose direct risks. In such cases, the Security Team typically requires a reproducible case if a reporter wants to file a security issue.   https://security.apache.org/blog/credits/#:~:text=If%20a%20project,private%20reporting%20mechanism.

**Comment by wu-sheng** [comment]
> > I am fine to add as it doesn't affect much. Just if this tool is not going to report that to private mail list or somewhere automatically, I am high doubting who is going to watch a UI page from time to time.↳
> 
> 
> 
> Most dependency component vulnerabilities do not pose direct risks. In such cases, the Security Team typically requires a reproducible case if a reporter wants to file a security issue.   https://security.apache.org/blog/credits/#:~:text=If%20a%20project,private%20reporting%20mechanism.
> 
> 

I can't see SBOM has capacity to tell how the lib is being used, and whether match with cve description.

**Comment by wu-sheng** [comment]
My question is, what are difference between using this and check dependency libs?

**Comment by CalvinKirs** [comment]
> > > I am fine to add as it doesn't affect much. Just if this tool is not going to report that to private mail list or somewhere automatically, I am high doubting who is going to watch a UI page from time to time.↳↳
> > 
> > 
> > Most dependency component vulnerabilities do not pose direct risks. In such cases, the Security Team typically requires a reproducible case if a reporter wants to file a security issue.   https://security.apache.org/blog/credits/#:~:text=If%20a%20project,private%20reporting%20mechanism.
> 
> I can't see SBOM has capacity to tell how the lib is being used, and whether match with cve description.

SBOMs just providing a list of dependencies; they offer a more standardized and detailed representation. Some tools, such as the OWASP Dependency-Check, can parse an SBOM and compare it to vulnerability databases to generate a list of CVEs associated with the dependencies.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
