### PR TITLE
Support authentication for log report channel.

### PR DESCRIPTION
**Pull request by zhyyu**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes [#6664 ](https://github.com/apache/skywalking/issues/6664)
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

The log channel use an independent gRPC channel, and it's not decorated by authentication, I decorate it. So agent can upload log when OAP backend open authentication.

It's my first time to open a pull request. Maybe not very standard,  I will appreciate a lot for advices!

### CODE REVIEW

**Comment by wu-sheng** [comment]
I need to to remind you, this log grpc channel is going to be removed once Satellite project is ready.

**Comment by zhyyu** [comment]
> I need to to remind you, this log grpc channel is going to be removed once Satellite project is ready.

Thanks for remind

> I need to to remind you, this log grpc channel is going to be removed once Satellite project is ready.

Thanks for remind, but before Satellite is ready, our company will still use the SkyWalking project.

**Comment by wu-sheng** [comment]
> > I need to to remind you, this log grpc channel is going to be removed once Satellite project is ready.
> 
> Thanks for remind, but before Satellite is ready, our company will still use the SkyWalking project.

8.7.0 is far from release, so, even we merge this, we wouldn't guarantee this included in the next release. That is the point of my reminder.

**Review by wu-sheng — APPROVED** [review]
Temporarily accept. This feature and grpc channel is going to be removed after Satellite 0.2.0 release. cc @EvanLjp @mrproliu

**Comment by kezhenxu94** [comment]
> Temporarily accept. This feature and grpc channel is going to be removed after Satellite 0.2.0 release. cc @EvanLjp @mrproliu 

Do we really want "all in sidecar"? If users don't use Kubernetes etc., they have to deploy another process (satellite) with their application, just for log authentication to work in this case?

**Comment by wu-sheng** [comment]
> > Temporarily accept. This feature and grpc channel is going to be removed after Satellite 0.2.0 release. cc @EvanLjp @mrproliu
> 
> Do we really want "all in sidecar"? If users don't use Kubernetes etc., they have to deploy another process (satellite) with their application, just for log authentication to work in this case?

That is the point. We need a consistent channel, but the current Satellite is not supporting all transport protocols, which is why @EvanLjp set up a new grpc channel for log reporter.

**Comment by BFergerson** [comment]
https://github.com/apache/skywalking/issues/7040 was marked as a duplicate of https://github.com/apache/skywalking/issues/6664 and https://github.com/apache/skywalking/issues/6664 is closed by this. I would think that means this should also fix the issue of the lack of TLS encryption mentioned in https://github.com/apache/skywalking/issues/7040 but this PR doesn't seem to do that.

Also, I'd like to mention that I find it a bit odd that the progress of the primary SkyWalking project is being slowed down by secondary projects like the sidecar. I would think that the primary project sets the pace and the secondary projects would need to keep up to stay functional. Here it seems that there is progress that could be made with SkyWalking but due to issues with a secondary project, that progress is being put on hold.

I believe you know what's best though so feel free to disregard my opinion.

**Comment by wu-sheng** [comment]
@BFergerson I reopened the #7040 as TLS has not been implemented. And if you need this feature, feel free to submit a similar feature like this. 

The satellite project is not moving fast, I guess due to sidecar matters for a large-scale system.

**Pull request merged**
