### PR TITLE
Add banyandb client APIs with most implementation.

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

@lujiajing1126 This is for you. You could add UTs and finish all TODOs. I don't have enough time to finish all types. But most are done.

The different contents for the proto files, I have discussed with @hanahmily. All these should be forwarded in the BanyanDB server side.

Eventually, before merging into master branch. The client lib would be moved into skywalking-banyandb-java-client repo, and run a separate release.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@lujiajing1126 This could be merged once we have confirmation from @hanahmily. Then you could fill the missing part and finish the trace write/read DAOs accordingly.

**Comment by lujiajing1126** [comment]
Got it. I will continue working on this PR. The plugin should also be implement in this PR, right?

**Comment by wu-sheng** [comment]
> Got it. I will continue working on this PR. The plugin should also be implement in this PR, right?

We don't need that. We could merge this directly, as no harm. Then you could do through 2 PRs
1. Finish this client API lib
2. Implement storage plugin

**Comment by wu-sheng** [comment]
We just need to wait for @hanahmily confirmation.

**Comment by lujiajing1126** [comment]
> > Got it. I will continue working on this PR. The plugin should also be implement in this PR, right?
> 
> We don't need that. We could merge this directly, as no harm. Then you could do through 2 PRs
> 
> 1. Finish this client API lib
> 2. Implement storage plugin

Oh, I understand....since I am not able to work on main repo's branches...

**Review by hanahmily — APPROVED** [review]
LGTM

**Comment by wu-sheng** [comment]
> > > Got it. I will continue working on this PR. The plugin should also be implement in this PR, right?
> > 
> > 
> > We don't need that. We could merge this directly, as no harm. Then you could do through 2 PRs
> > 
> > 1. Finish this client API lib
> > 2. Implement storage plugin
> 
> Oh, I understand....since I am not able to work on main repo's branches...

That is not important, even other committers can, we don't recommend 2 people working on the same branch.

**Pull request merged**
