### PR TITLE
Check http protocol in Python agent as well

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think you should set up 2 test cases? One for HTTP, the other for gRPC.

**Comment by kezhenxu94** [comment]
> I think you should set up 2 test cases? One for HTTP, the other for gRPC.

There're two services, provider and consumer, they use grpc and http respectively, I think it's enough, no?

**Comment by wu-sheng** [comment]
> There're two services, provider and consumer, they use grpc and http respectively, I think it's enough, no?

I see, it is enough.

**Comment by wu-sheng** [comment]
Seems python e2e fails.

**Comment by wu-sheng** [comment]
What happens here?

**Comment by kezhenxu94** [comment]
Should be good to go

**Pull request merged**
