### PR TITLE
Improve okhttp plugin performance by optimizing Class.getDeclaredField().

### PR DESCRIPTION
**Pull request by ArjenDavid-sjtu**
### Improve the performance of `apm-okhttp-common`
- [ ] Add a benchmark for the improvement: Not necessary
- [ ] The benchmark result: Trivial
- [ ] Links/URLs to the theory proof or discussion articles/blogs.
https://stackoverflow.com/questions/16395881/getdeclaredfields-absolute-performance

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. No
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
The big performance impact is mostly because reflect execution. But getting field is not very slow. Are you facing real issue?

**Comment by wu-sheng** [comment]
And you should update changes.md in the root.

**Comment by ArjenDavid-sjtu** [comment]
> The big performance impact is mostly because reflect execution. But getting field is not very slow. Are you facing real issue?

I am not facing the real issue yet, maybe later a comparison between the two ways can be made. I was just thought another better way to do getting field.

**Comment by ArjenDavid-sjtu** [comment]
> And you should update changes.md in the root.

I am so sorry for forgetting it! I have updated the changes.md now.

**Comment by wu-sheng** [comment]
> > The big performance impact is mostly because reflect execution. But getting field is not very slow. Are you facing real issue?
> 
> 
> 
> I am not facing the real issue yet, maybe later a comparison between the two ways can be made. I was just thought another better way to do getting field. 

This is better, just want to confirm the real case.

**Comment by wu-sheng** [comment]
Once all tests passed, this at least improves a little, but limited.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
