### PR TITLE
#5013  update  @Column(columnName = ENTITY_ID, length = 512)     private String entityId;

### PR DESCRIPTION
**Pull request by yazong**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

#5013

___
### Bug fix
- Bug description.

description:
insert related table exceptions when using springcloudgateway2.1.X.

table list:

endpoint_relation_server_side
service_instance_relation_client_side
service_instance_relation_server_side
service_relation_client_side
service_relation_server_side

exception list:

2020-07-02 14:38:30,876 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: UPDATE endpoint_relation_server_side SET
source_endpoint= ?,dest_endpoint= ?,component_id= ?,entity_id= ?,time_bucket= ? WHERE id = ?
2020-07-02 14:38:30,909 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: INSERT INTO endpoint_relation_server_side VALUES
(?,?,?,?,?,?)
2020-07-02 14:38:30,913 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [pool-4-thread-1] ERROR [] - D
ata truncation: Data too long for column 'entity_id' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'entity_id' at row 1

2020-07-07 11:35:51,485 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: UPDATE endpoint_relation_server_side SET
source_endpoint= ?,dest_endpoint= ?,component_id= ?,entity_id= ?,time_bucket= ? WHERE id = ?
2020-07-07 11:35:51,518 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: INSERT INTO service_instance_relation_client_side VALUES
(?,?,?,?,?,?,?,?)
2020-07-07 11:35:51,585 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: INSERT INTO service_instance_relation_client_side VALUES
(?,?,?,?,?,?,?,?)
2020-07-07 11:35:51,589 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [pool-4-thread-1] ERROR [] - D
ata truncation: Data too long for column 'entity_id' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'entity_id' at row 1

2020-07-07 11:36:19,347 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: UPDATE service_instance_relation_server_side SET
source_service_id= ?,source_service_instance_id= ?,dest_service_id= ?,dest_service_instance_id= ?,component_id= ?,entity_id= ?,time_
bucket= ? WHERE id = ?
2020-07-07 11:36:19,396 - org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor - 52 [pool-4-thread-1] DEBUG [] - execute
 aql in batch: INSERT INTO service_instance_relation_server_side VALUES
(?,?,?,?,?,?,?,?)
2020-07-07 11:36:19,400 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO - 75 [pool-4-thread-1] ERROR [] - D
ata truncation: Data too long for column 'entity_id' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'entity_id' at row 1

- How to fix?

update @Column(columnName = ENTITY_ID, length = 512)

update java list:
EndpointRelationServerSideMetrics
ServiceInstanceRelationClientSideMetrics
ServiceInstanceRelationServerSideMetrics
ServiceRelationClientSideMetrics
ServiceRelationServerSideMetrics

init table list:
endpoint_relation_server_side
service_instance_relation_client_side
service_instance_relation_server_side
service_relation_client_side
service_relation_server_side

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Has this fixed your issue locally?

**Comment by yazong** [comment]
> Has this fixed your issue locally?

yes.
i have tested the packaging of 'oap-server'.
i replaced 'server-core-8.0.1.jar'.
these exceptions were not reprinted.

**Comment by zhousheng2** [comment]
Hello, I see the repair problem。Is this fix updated on the master branch instead of tag8.0.1?

**Comment by wu-sheng** [comment]
All changes are in the master. 8.0.1 is a tag.

**Comment by zhousheng2** [comment]
However, I've seen the master branch code fix this problem, but tag8.0.1 hasn't fixed it yet

**Comment by zhousheng2** [comment]
I see. Thank you very much

**Comment by zhousheng2** [comment]
Please download the official website path tar.gz Does the package update this problem?

**Comment by wu-sheng** [comment]
The milestone means it should be included in releases starting at that version. It is not in any release right now. 
No one will update the released version, that is wrong.

**Comment by zhousheng2** [comment]
If I use the latest version of the code and replace / oap-libs/ server-core-8.0.1.jar with the compiled server-core-8.0.1.jar, can I use it normally in Linux?

**Comment by wu-sheng** [comment]
Why do you need this?.You could package the codes to get the whole dist tar.

**Comment by zhousheng2** [comment]
Hello, I use git or idea to compile the source code, error
Execute the following command：./mvnw clean package -DskipTests


[INFO] tool-profile-snapshot-exporter ..................... SKIPPED
[INFO] server-starter ..................................... SKIPPED
[INFO] tool-profile-snapshot-exporter-es7 ................. SKIPPED
[INFO] server-starter-es7 ................................. SKIPPED
[INFO] apm-webapp ......................................... SKIPPED
[INFO] apache-skywalking-apm .............................. SKIPPED
[INFO] apache-skywalking-apm-es7 .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.223 s
[INFO] Finished at: 2020-07-10T18:56:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project apm-network: You have 1 Checkstyle violation. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-network

**Comment by wu-sheng** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project apm-network: You have 1 Checkstyle violation. -> [Help 1]

You have changed the source codes, and don't follow the code style.

**Comment by zhousheng2** [comment]
I didn't modify the code before, but I finally packaged it successfully, but it's hard. Even if I can access the connection, there is always something wrong with the download package. Even if I can cross the wall, I can package it successfully

**Comment by yazong** [comment]
> I didn’t modify the code before, and it’s finally packaged successfully, but it is more difficult. Even if I can access the connection, I always download the package and there is a problem, even if I go over the wall, I can package it successfully.

https://blog.llyweb.com/articles/2020/06/24/1592992981568.html

**Pull request merged**
