### PR TITLE
fix the order of segments at the same level

### PR DESCRIPTION
**Pull request by bnubobby**
- Why submit this pull request?
- Bug fix
for  #3844

### CODE REVIEW

**Comment by wu-sheng** [comment]
You need to follow the code format. There is a format file in the root path.

**Comment by bnubobby** [comment]
OK, you're the boss

**Comment by wu-sheng** [comment]
You just need to update the branch, don't need to reopen a new pull request every time. CI will check your PR. Only be able to merge after you passed all tests.

**Comment by bnubobby** [comment]
I'm sorry about that,  I am new for PR

**Comment by bnubobby** [comment]
@wu-sheng 
Please submit another pull request to fix.
When I just tested it, it led to another problem.

**Comment by wu-sheng** [comment]
OK. Do you need help? Or you could fix by yourself?

**Pull request closed without merging**
