### PR TITLE
Perf: optimize Envoy ALS analyzer performance in high traffic load scenario (reduce ~1cpu in ~10k RPS)

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
From what I've tested, `LambdaMetafactory` can nearly reach to the same performance as static call to `setXXX` method, much faster than reflection

**Comment by kezhenxu94** [comment]
I'll check other places to see whether there is critical path that also use reflection

**Comment by kezhenxu94** [comment]
Confirmed, no more place to update in this PR

**Review by wu-sheng — APPROVED** [review]
LGTM.

**Pull request merged**
