### PR TITLE
Fix 3055

### PR DESCRIPTION
**Pull request by zhaoyuguang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
Fix https://github.com/apache/skywalking/issues/3055

### CODE REVIEW

**Comment by wu-sheng** [comment]
+1 for code scan. I also think, we should check all `ContextManager#activeSpan` in plugin, and decide whether we should `@Deprecated` or delete. Let's check that and talk.

**Comment by dmsolr** [comment]
As I know, `ContextManager#activeSpan()` is used for `handleMethodException`

**Comment by dmsolr** [comment]
I think it cannot be deleted. Because it is useful sometimes.

**Comment by wu-sheng** [comment]
From the current failures, I am thinking about, is this right using `ContextManager#activeSpan()` even for logging error? It could cause an NPE too, right?

**Comment by dmsolr** [comment]
Not NPE. It throws 'No active span.' exception when `ContextManager#activeSpan()` called.

**Comment by wu-sheng** [comment]
> Not NPE. It throws 'No active span.' exception when ContextManager#activeSpan() called.

But the exception should not happen in agent, it costs too much.

**Comment by dmsolr** [comment]
I entirely agree with you. Maybe I have a mistake. I mean we need `ContextManager#activeSpan()` in other scenario.

**Comment by zhaoyuguang** [comment]
I scanned the code and found only the two places, which are obvious usage errors.

**Pull request merged**
