### PR TITLE
Remove login permanently.

### PR DESCRIPTION
**Pull request by wu-sheng**
As login is not perfect, and we don't intend to make it works, so remove it permanently

### CODE REVIEW

**Comment by wu-sheng** [comment]
> Seems the org.apache.skywalking.apm.webapp.security package is useless now and can be removed?

I am assuming maybe one day, some contributors to add this back. Anyway, wait for @hanahmily 's suggestion.

**Comment by wu-sheng** [comment]
@JaredTan95 @kezhenxu94 @hanahmily Please run demo locally, and check whether no login works well.

**Comment by zhaoyuguang** [comment]
In my local test, login as we hope, but logout button hidden maybe better
image

**Comment by wu-sheng** [comment]
@zhaoyuguang I am merging that PR, and update this later.

**Comment by wu-sheng** [comment]
@zhaoyuguang I merged and sync your PR to this. Please recheck.

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang I merged and sync your PR to this. Please recheck.

Now,  The UI look like:
image
image

**Comment by wu-sheng** [comment]
@zhaoyuguang Please approve, then I will merge this.

**Comment by wu-sheng** [comment]
@kezhenxu94 `org.apache.skywalking.apm.webapp.security` package has been removed, by following @hanahmily reply.

**Comment by wu-sheng** [comment]
@zhaoyuguang @kezhenxu94 As I have deleted the codes, could you re-verify? Does the webapp startup right?

**Comment by zhaoyuguang** [comment]
Checked, Work as expected.

**Comment by wu-sheng** [comment]
@zhaoyuguang Need another approvement :)

**Pull request merged**
