### PR TITLE
Migrate to new changes action in CI

### PR DESCRIPTION
**Pull request by Superskyyy**
Tested on my own fork, should be working, but we should still monitor it for a day or two see if there's any expected bugs. Now it behaves the same as the old one (the skip ci by individual commit feature is not safe to implement, I decided not to play with it).

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by Superskyyy** [comment]
oh shoot, @kezhenxu94 the action was not approved for running at ASF...

**Comment by wu-sheng** [comment]
Ping INFRA at slack or a JIRA ticket? This should be not hard to get approval.

**Comment by Superskyyy** [comment]
> Ping INFRA at slack or a JIRA ticket? This should be not hard to get approval.

Done, let's wait for update. https://issues.apache.org/jira/browse/INFRA-24599

**Comment by Superskyyy** [comment]
There is a pinned version that we can use (previously approved)

**Comment by Superskyyy** [comment]
Still waiting for response, luckily the action is still running somehow in gha machines.

**Comment by wu-sheng** [comment]
@kezhenxu94 Please check.

**Review by kezhenxu94 — APPROVED** [review]
Great!

**Pull request merged**
