### PR TITLE
FAQ for backend log4j2.xml

### PR DESCRIPTION
**Pull request by seifeHu**
- [ ] Improve performance
Too many  larger log files can causes the hard disk to become full    ,add   .gz and TimeBasedTriggeringPolicy  . add the two changes ,the skywalking oap logs will be zipped in .gz file . 
This changes can make the oap server run  longer times .

### CODE REVIEW

**Comment by wu-sheng** [comment]
My question is for gz. This is only a requirement for all users, from my understanding. If you have the use case, please consider to add a FAQ doc, rather than changing this.

**Comment by seifeHu** [comment]
> My question is for gz. This is only a requirement for all users, from my understanding. If you have the use case, please consider to add a FAQ doc, rather than changing this.

In my case , about running 15 days . My oap logs got more than 60G . so I think default log config do zip . Can lead to  oap server to running longer times.

**Comment by wu-sheng** [comment]
I mean, users could have different solution. Such as using error log only, close log for some packages, or like you using zip mode. My point, yours is just one option. It fits FAQ more than changing the distance tar permanently.

**Comment by wu-sheng** [comment]
@kezhenxu94 @arugal @JaredTan95 Any suggestion about this?

**Comment by kezhenxu94** [comment]
I'm totally agree to keep it unchanged because the changes here are just configurations from third-party framework (log4j), users should modify the configurations in their own environments instead of in SkyWalking repo, we cannot meet every user's requirement if future users don't like the archived logs

**Comment by seifeHu** [comment]
ok. I will make this content into FAQ

**Comment by kezhenxu94** [comment]
@seifeHu any update?

**Comment by JaredTan95** [comment]
We also used `.gz` feature to compress log file size in our scenario, but It doesn't mean suitable for all users. So, Let's keep it and add FAQ docs.

**Comment by wu-sheng** [comment]
@seifeHu Could you update this PR?

**Comment by wu-sheng** [comment]
@kezhenxu94 @JaredTan95 Should we close this? As no update in 10 days.

**Comment by kezhenxu94** [comment]
Prefer to close it and reopen or open another PR if @seifehu is ready

**Pull request closed without merging**
