### PR TITLE
Add feign loadbalancer case for spring-cloud-feign-1.x-scenario plugin.

### PR DESCRIPTION
**Pull request by zifeihan**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.
Add feign loadbalancer case for spring-cloud-feign-1.x-scenario plugin.

### CODE REVIEW

**Review by arugal — APPROVED** [review]
LGTM

**Comment by wu-sheng** [comment]
Please don't merge pr unless it is 8.2.0 bug fixed.

**Comment by wu-sheng** [comment]
There is no 8.2.0 tag yet

**Comment by arugal** [comment]
> There is no 8.2.0 tag yet

Sorry, I thought the test code could be merged.

**Comment by wu-sheng** [comment]
In theory, it should be harmless. But as it is code, who knows.:p

**Pull request merged**
