### PR TITLE
Update submodule url for .gitmodules

### PR DESCRIPTION
**Pull request by SataQiu**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.
As our code repository has changed its name, the corresponding reference url should be updated.

- How to fix?
Update submodule url for `.gitmodules`.

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Check your repo, https://github.com/SataQiu/incubator-skywalking/tree/fix-gitmodules-20190427/apm-protocol/apm-network/src/main

It still shows in old link. You need to follow git document, remove gitsubmodule first(several steps), then add new one. 
I assume you edit the submodule file directly

**Comment by SataQiu** [comment]
Thanks a lot @wu-sheng .
I am not very familiar with git submodule. The code has been updated. 
Clould you please have a look?

**Comment by wu-sheng** [comment]
Yes. Submodule updated right. But you submit an unnecessary file. Please remove it.

**Comment by SataQiu** [comment]
I don't know, but it seems to be back to the first submission  :sob: , how to deal with it?
@wu-sheng

**Comment by SataQiu** [comment]
Is that right?

**Comment by wu-sheng** [comment]
I download your branch, look like submodule still unchanged.

**Comment by wu-sheng** [comment]
How do you update the submodule? Could you provide the step?

**Comment by wu-sheng** [comment]
Look like right :)

**Comment by wu-sheng** [comment]
I had been misguided by GitHub page. @SataQiu Could you please update the submodule, and add *.pb.html again? Then I could merge.

Sorry, ask you to do wrong adjustments.

**Comment by wu-sheng** [comment]
I will merge this tomorrow.

**Comment by SataQiu** [comment]
OK. Thank you! :laughing:

**Comment by wu-sheng** [comment]
> See RAT report in: /home/travis/build/apache/skywalking/apm-protocol/apm-network/target/rat.txt 

Based on this, I assume because we need another PR to `service-mesh-probe/istio/skywalking.config.pb.html` in the protocol repo.

We need to add Apache license header, and update submodule again.

**Comment by SataQiu** [comment]
ok, I would love to do it.

**Comment by SataQiu** [comment]
The CI passed! 
I think we can merge it. 
@wu-sheng

**Comment by wu-sheng** [comment]
Merged. 6.1 will be cut soon.

**Pull request merged**
