### PR TITLE
Don't trace anything if the backend is not available.

### PR DESCRIPTION
**Pull request by zifeihan**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Don't trace anything if the backend is not available.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Do you check the code style? Please check the CI logs.

**Comment by zifeihan** [comment]
> Do you check the code style? Please check the CI logs.

so sorry, not code style, some test will force check segment size when OAP backend not start. i will fix it.

**Comment by wu-sheng** [comment]
I don't remember there is segment size test.

**Comment by zifeihan** [comment]
> I don't remember there is segment size test.

like this,
org.apache.skywalking.apm.agent.core.remote.TraceSegmentServiceClientTest#testSendTraceSegmentWithoutException
```
    public void testSendTraceSegmentWithoutException() throws InvalidProtocolBufferException {
        grpcServerRule.getServiceRegistry().addService(serviceImplBase);

        AbstractSpan firstEntrySpan = ContextManager.createEntrySpan("/testFirstEntry", null);
        firstEntrySpan.setComponent(ComponentsDefine.TOMCAT);
        Tags.HTTP.METHOD.set(firstEntrySpan, "GET");
        Tags.URL.set(firstEntrySpan, "127.0.0.1:8080");
        SpanLayer.asHttp(firstEntrySpan);
        ContextManager.stopSpan();

        serviceClient.consume(storage.getTraceSegments());

        assertThat(upstreamSegments.size(), is(1));
        SegmentObject traceSegmentObject = upstreamSegments.get(0);
        assertThat(traceSegmentObject.getSpans(0).getRefsCount(), is(0));
        assertThat(traceSegmentObject.getSpansCount(), is(1));

        SpanObject spanObject = traceSegmentObject.getSpans(0);
        assertThat(spanObject.getSpanType(), is(SpanType.Entry));
        assertThat(spanObject.getSpanId(), is(0));
        assertThat(spanObject.getParentSpanId(), is(-1));
    }
``

**Comment by wu-sheng** [comment]
Keep trace should be OFF, I think. Is there a case open this?

**Comment by zifeihan** [comment]
@wu-sheng sorry, origin code is ok, this Config.Agent.KEEP_TRACING means Keep tracing even the backend is not available... sorry.

**Pull request closed without merging**
