### PR TITLE
update fix vertx plugin NPE

### PR DESCRIPTION
**Pull request by wentjiang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
https://github.com/apache/skywalking/issues/3338
___
### Bug fix
- Bug description.
my project use vertx v3.4 ,the agent log show
java.lang.NullPointerException
at org.apache.skywalking.apm.plugin.vertx3.HttpServerResponseImplEndInterceptor.beforeMethod(HttpServerResponseImplEndInterceptor.java:39)

- How to fix?
I review code and debug, the context is null, so I find there are not use class io.vertx.ext.web.impl.RouterImpl in my project
finally,I solve it by I create io.vertx.core.http.impl.ServerConnection enhance, it works healthy
___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wentjiang** [comment]
There are no test case in this plugin

**Comment by wu-sheng** [comment]
We need integration test case here, https://github.com/SkyAPMTest/agent-auto-integration-testcases

**Comment by wu-sheng** [comment]
Your target branch is still wrong. And your ci fails.
Please fix.

**Comment by wu-sheng** [comment]
@wentjiang Are you still following this?

**Comment by wentjiang** [comment]
@wu-sheng I think it is a usage question,but I not very be familiar with vertx, in my usage,I don't use the plugin enhance class , so I find an available class to enhance;I think this question need the plugin author to  judge;

**Comment by wu-sheng** [comment]
If you have a new use case, the plugin should enhance. I closed this because you pr target is not master.

**Comment by wentjiang** [comment]
I know ,I change target to master branch

**Comment by wu-sheng** [comment]
@wentjiang please submit a new pull request. And provide plugin tests for it.

**Pull request closed without merging**
