### PR TITLE
support Kafka SASL login module.

### LINKED ISSUE #6157: Failed to connect the Agent to the Kafka authenticated by SASL.
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When SASL authentication is enabled for Kafka, an error is reported during agent access,here are error messages:
ERROR 2021-01-08 06:30:52:951 main ServiceManager : ServiceManager try to pre-start [org.apache.skywalking.apm.agent.core.kafka.KafkaProducerManager] fail.
org.apache.skywalking.apm.dependencies.org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:451)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.admin.Admin.create(Admin.java:59)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
        at org.apache.skywalking.apm.agent.core.kafka.KafkaProducerManager.prepare(KafkaProducerManager.java:58)
        at org.apache.skywalking.apm.agent.core.boot.ServiceManager.prepare(ServiceManager.java:104)
        at org.apache.skywalking.apm.agent.core.boot.ServiceManager.boot(ServiceManager.java:43)
        at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: org.apache.skywalking.apm.dependencies.org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: unable to find LoginModule class: org.apache.kafka.common.security.plain.PlainLoginModule
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:426)
        ... 12 more
Caused by: javax.security.auth.login.LoginException: unable to find LoginModule class: org.apache.kafka.common.security.plain.PlainLoginModule
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:794)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
        at org.apache.skywalking.apm.dependencies.org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:147)
        ... 16 more
___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by DuanYuePeng**
javax.security.auth.login.LoginContext use context class loader to load the login module, when configuring "sasl.jaas.config", we could set the value as org.apache.skywalking.apm.dependencies.org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="pass";, and the context class loader would load the class correctly, otherwise, NoClassFoundException would be thrown

### Fix <#6157>
- [] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #6157.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
LGTM, have you checked in your env? We don't have test case to cover this case.

**Comment by wu-sheng** [comment]
Previous discussion is at #7270

**Comment by DuanYuePeng** [comment]
Yes, after this fix, the `AdminClient` is created successfully.

**Comment by luffy1849** [comment]
My solution is that the `org.apache.kafka.common.security.plain.PlainLoginModule` class needs to be configured as `org.apache.skywalking.apm.dependencies.org.apache.kafka.common.security.plain.PlainLoginModule`. The complete configuration is as follows:

```
plugin.kafka.producer_config[security.protocol]=SASL_PLAINTEXT
plugin.kafka.producer_config[sasl.mechanism]=PLAIN
plugin.kafka.producer_config[sasl.jaas.config]=org.apache.skywalking.apm.dependencies.org.apache.kafka.common.security.plain.PlainLoginModule required username="" password="";
```

**Pull request merged**
