### PR TITLE
GC time metrics should be total time.

### PR DESCRIPTION
**Pull request by wu-sheng**
Use `sum` to replace `longAvg` in GC time calculation. The `longAvg` OP makes the metrics meaning the avg GC time per report period.

This bug is reported from the community. FYI @apache/skywalking-committers

### CODE REVIEW

**Comment by kezhenxu94** [comment]
the unit test `TraceSegmentServiceClientTest.testSendTraceSegmentWithException` is not stable after #3181 , it failed two times, I'll try to find out why it failed sometimes

**Comment by wu-sheng** [comment]
I added a fix for another bug. Prometheus telemetry provider is down.

**Pull request merged**
