### PR TITLE
fix doc_Trace Data Protocol v2_error #2620

### PR DESCRIPTION
**Pull request by coki230**
fix doc_Trace Data Protocol v2_error #2620

Please answer these questions before submitting pull request

- Why submit this pull request?
-  Bug fix

- Related issues
2620
___
### Bug fix
- Bug description.
 the sentence of "After you have trace id and trace instance id, you could send traces and metric. Now we have".
should be "After you have service id and service instance id, you could send traces and metric. Now we have"
- How to fix?

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why close?

**Comment by coki230** [comment]
my mistake, when i finished, it return some error. so i close it

**Comment by wu-sheng** [comment]
Let's wait ci. I think this should pass.

**Comment by wu-sheng** [comment]
Ref #2620

**Pull request merged**
