### PR TITLE
Support disables the verification of server's TLS certificate chain for specific hosts

### PR DESCRIPTION
**Pull request by JaredTan95**
###  Support disables the verification of server's TLS certificate chain for specific hosts by `SW_STORAGE_ES_SSL_INSECURE_HOSTS` env.
**NOTE**: You should never use this in production but only for a testing purpose.

- [ ] If this is non-trivial feature, paste the links/URLs to the design doc.
- [x] Update the documentation to include this new feature.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Notice, #8179 got rejected due to skipping the secure checking.
This is an insecure way for general use.
Couldn't you explain more?

**Comment by JaredTan95** [comment]
Okay, I missed this https://github.com/apache/skywalking/pull/8179 issue.
Feedback from some customers, in some user cases, they don't bind domain on elasticseach multi-node , when they set up skywalking in their `dev` or `test` environment, the connection between oap and es could not be established.
So, We could provide this way for ease of debugging and deployment.
And, we've added instructions, don't use it in production, and this feature don't skip any validation by default.

**Comment by wu-sheng** [comment]
No TLS verification should be fine, but don't need through us, actually. They could put a Nginx/Envoy in the front of ElasticSearch server, then OAP server could access HTTP endpoint without TLS.
This is more comfortable for SkyWalking about that, we are not violating TLS which has explicitly activated in configurations.
Is this working for you?

**Comment by JaredTan95** [comment]
> No TLS verification should be fine, but don't need through us, actually. They could put a Nginx/Envoy in the front of ElasticSearch server, then OAP server could access HTTP endpoint without TLS. This is more comfortable for SkyWalking about that, we are not violating TLS which has explicitly activated in configurations. Is this working for you?

The proxy way may be a working way, but it may cause a little change for deployment architecture. No matter, I closed it temporarily. 

And continue to see the community feedback

**Comment by wu-sheng** [comment]
> > No TLS verification should be fine, but don't need through us, actually. They could put a Nginx/Envoy in the front of ElasticSearch server, then OAP server could access HTTP endpoint without TLS. This is more comfortable for SkyWalking about that, we are not violating TLS which has explicitly activated in configurations. Is this working for you?
> 
> The proxy way may be a working way, but it may cause a little change for deployment architecture. I closed it temporarily.
> 
> And continue to see the community feedback

Let's see, I put more thoughts behind this at here, https://twitter.com/wusheng1108/status/1465833723115409410
If others follow this thread, it should be worth to take a look.

**Comment by JaredTan95** [comment]
related discusson https://github.com/apache/skywalking/discussions/8154

**Pull request closed without merging**
