### PR TITLE
Modify the enumeration judgment usage 

### PR DESCRIPTION
**Pull request by HarryFQ**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Hey @HarryFQ , did you got `NullPointerException` in this query?

**Comment by HarryFQ** [comment]
> Hey @HarryFQ , did you get `NullPointerException` in this query?

Impossible, the equals method produces "npe" generated by the caller. You can check [JLS 8.9 Enums](https://docs.oracle.com/javase/specs/jls/se9/html/jls-8.html#jls-8.9) and[ stackoverflow arguments](https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals).

**Comment by kezhenxu94** [comment]
> > Hey @HarryFQ , did you get `NullPointerException` in this query?
> 
> 
> 
> Impossible, the equals method produces "npe" generated by the caller. You can check [JLS 8.9 Enums](https://docs.oracle.com/javase/specs/jls/se9/html/jls-8.html#jls-8.9) and[ stackoverflow arguments](https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals).
> 
> 

What I meant is that, did you really get NPE before changing to `==`, I know it's impossible after your changes.

**Review by kezhenxu94 — APPROVED** [review]
￼anyway, this is a fix for obvious issue

**Comment by HarryFQ** [comment]
> > > Hey @HarryFQ , did you get `NullPointerException` in this query?
> > 
> > 
> > Impossible, the equals method produces "npe" generated by the caller. You can check [JLS 8.9 Enums](https://docs.oracle.com/javase/specs/jls/se9/html/jls-8.html#jls-8.9) and[ stackoverflow arguments](https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals).
> 
> What I meant is that, did you really get NPE before changing to `==`, I know it's impossible after your changes.

I didn't get "NPE" before the change, but it was changed to "==" to be faster, safer, and more intuitive, but this is also a personal understanding.

**Pull request merged**
