### PR TITLE
fix hbase intercepting bug seems like this issue: #6572;

### PR DESCRIPTION
**Pull request by wuguangkuo**
improve the interceptors code from using reflect manner to using public methods

### Fix #6752 
- [ ] Add a unit test to verify that the fix works.
- [ x] Explain briefly why the bug exists and how to fix it.
     The bug happened when try to get a private filed relative with remote peer,but this field is null

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think you link incorrect issue?

**Comment by wu-sheng** [comment]
And you breaks the plugin test, please verify.

**Comment by wuguangkuo** [comment]
> And you breaks the plugin test, please verify.

The CI log told failure cause as "configuration-nacos" moudle tests，not the code of my committing

**Comment by wu-sheng** [comment]
> > And you breaks the plugin test, please verify.
> 
> The CI log told failure cause as "configuration-nacos" moudle tests，not the code of my committing

Ignore this. I mean this, https://github.com/apache/skywalking/pull/7302/checks?check_run_id=3073114529

**Pull request closed without merging**
