### PR TITLE
Make bootstrap instrumentation available in JDK9 - 11

### PR DESCRIPTION
**Pull request by wu-sheng**
Hi @candyleer 

By following the discussion at https://github.com/raphw/byte-buddy/issues/697 and PR #3171, I have done some adjustments. Now from my local test, the bootstrap instrumentation is available in OpenJDK 8 - 11, due to 8 is available, I assume JDK 6/7 are working too.

The issue remains today that, JDK 12 is still an issue because UnSafe injection is not working in JDK12. I have left a message to @raphw, let's see what is the right move. 

I think we may need two way, which should be OK. But at least, it is better for most widely used JDK, especially 9 and 11.

FYI @apache/skywalking-committers

### CODE REVIEW

**Comment by candyleer** [comment]
Got it

**Comment by wu-sheng** [comment]
`bootstrapJarTmp` folder and document related to it have been removed permanently, as we use unsafe injection in this PR.

**Comment by candyleer** [comment]
LGTM support jdk 6-11

**Pull request merged**
