### PR TITLE
Remove nacos

### PR DESCRIPTION
**Pull request by songzhendong**
Remove nacos

### CODE REVIEW

**Comment by songzhendong** [comment]
Temporarily remove Nacos(After Nacos is stable, it will be re integrated into skywalking)

**Comment by kezhenxu94** [comment]
@arugal please rewrite the commit message when merging, there're too long/many useless message

image

**Comment by wu-sheng** [comment]
@arugal Please pay attention to this. In the commit logs are too many and don't have much meaning. Please consider to edit and remove all.

**Comment by arugal** [comment]
@kezhenxu94 @wu-sheng I will pay attention in the future. Thank you for reminding me :)

**Pull request merged**
