### PR TITLE
Set telemetry instanced id for etcd and nacos plugin

### LINKED ISSUE #3460: The application that 'docker-entrypoint.sh' generated make skywalking 6.3 NPE
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

SkyWalking 6.3 ( docker version 

I use   docker.io/apache/skywalking-oap-server:latest   version.

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

The config template that [docker-entrypoint](https://github.com/apache/skywalking-docker/blob/master/6/6.3/oap/docker-entrypoint.sh) has an error config.

It make OAP server raise an error （ NullPointException

```yml
docker-entrypoint:
  default:
```

And the error stack info :

```text
2019-09-11 18:17:43,823 - org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister - 64 [main] INFO  [] - Current configurations after the bootstrap sync.
Following dynamic config items are available.
---------------------------------------------
key:receiver-trace.default.slowDBAccessThreshold    module:receiver-trace    provider:default    value(current):

2019-09-11 18:17:44,108 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer - 93 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2019-09-11 18:17:44,113 - org.eclipse.jetty.server.Server - 372 [main] INFO  [] - jetty-9.4.2.v20170220
2019-09-11 18:17:44,190 - org.eclipse.jetty.server.handler.ContextHandler - 802 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@33d230ce{/,null,AVAILABLE}
2019-09-11 18:17:44,213 - org.eclipse.jetty.server.AbstractConnector - 280 [main] INFO  [] - Started ServerConnector@4e8598d9{HTTP/1.1,[http/1.1]}{0.0.0.0:12800}
2019-09-11 18:17:44,215 - org.eclipse.jetty.server.Server - 444 [main] INFO  [] - Started @18433ms
2019-09-11 18:17:44,247 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer - 54 [main] INFO  [] - persistence timer start
2019-09-11 18:17:44,254 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer - 42 [main] INFO  [] - Cache updateServiceInventory timer start
2019-09-11 18:17:44,507 - org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker - 108 [DataCarrier.REGISTER_L1.BulkConsumePool.0.Thread] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.register.ServiceInstanceInventory.hashCode(ServiceInstanceInventory.java:81) ~[server-core-6.3.0.jar:6.3.0]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_152]
	at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_152]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:69) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) ~[server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
```

I don't know the cause of the exception, but  the OAP server up after I contrast the file( docker version and non-docker version ) and remove that config.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by hanahmily**
Fixed #3460 

The etcd and nacos plugins didn't set telemetry instance id, that cause telemetry module rises NPE.

### CODE REVIEW

**Comment by hi-sb** [comment]
I had the same problem. Dockerhup has only 6.4.0 mirrors. When can I get the mirror after 6.5.0 restoration?

**Comment by wu-sheng** [comment]
6.5.0 has not released, you need to build the image by yourself. Should not be hard.

**Comment by hi-sb** [comment]
ok

**Comment by hi-sb** [comment]
I've adopted a single point deployment approach, but it throws an exception.
`
2019/10/8 下午5:42:16java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2019/10/8 下午5:42:16	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
2019/10/8 下午5:42:16	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_181]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.remote.selector.ForeverFirstSelector.select(ForeverFirstSelector.java:37) ~[server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.remote.RemoteSenderService.send(RemoteSenderService.java:58) ~[server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:47) ~[server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.register.worker.RegisterRemoteWorker.in(RegisterRemoteWorker.java:32) ~[server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_181]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.onWork(RegisterDistinctWorker.java:76) [server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker.access$100(RegisterDistinctWorker.java:33) [server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.oap.server.core.register.worker.RegisterDistinctWorker$AggregatorConsumer.consume(RegisterDistinctWorker.java:103) [server-core-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:82) [apm-datacarrier-6.3.0.jar:6.3.0]
2019/10/8 下午5:42:16	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:53) [apm-datacarrier-6.3.0.jar:6.3.0]
`

**Comment by hi-sb** [comment]
I've adopted a single point deployment approach, but it throws an exception.

image

**Comment by wu-sheng** [comment]
Read #3471, btw, if this exception didn't happen again, you could ignore it.

**Comment by hi-sb** [comment]
Now I can see the link information in the UI, but I can't see any services. The number of services is 0. I'm not sure if it's caused by this problem. Has anyone else ever had such a situation?

**Comment by hi-sb** [comment]
I solved this problem because I used an nginx to proxy the UI once.

**Pull request merged**
