### PR TITLE
Feature/check style refactor

### LINKED ISSUE #4377: Checkstyle plugin checks test codes too
Currently, the Checkstyle plugin in `pom.xml` of the root project only checks codes in the root project and its submodules, we also need to check those codes in `test/e2e` and `test/plugin`

- reusethe same checkstyle configurations

- add Checkstyle plugin in the `test/plugin/pom.xml` and `test/e2e/pom.xml`, and add the Checkstyle goal to `.github/workflow/plugins-test.yml` and `.github/workflow/e2e.yml`

### PR DESCRIPTION
**Pull request by huangbowen521**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Improve performance

- Related issues
closes #4377 
___

### New feature or improvement
- Checkstyle plugin checks test codes

### CODE REVIEW

**Comment by wu-sheng** [comment]
Test cases are failing, please recheck.

**Comment by arugal** [comment]
[Test case code](https://github.com/apache/skywalking/tree/master/test/plugin/scenarios) also requires check style? :confused:

**Comment by wu-sheng** [comment]
>  also requires check style? 

Yes. All codes should be consistent.

**Comment by wu-sheng** [comment]
Due to `no update`, add new tag and remove milestone. Seems no response from the author.

**Comment by huangbowen521** [comment]
there are existing checkstyle issues for e2e and plugins module, i am working on it.

**Comment by kezhenxu94** [comment]
Close as too many conflicts and no update, should open another PR and rebase on the master

**Pull request closed without merging**
