### PR TITLE
Fix tags store of log and trace on h2/mysql/pg storage

### LINKED ISSUE #6504: Cannot search tags on log and trace pages(SQL Storage: h2/mysql/pg)
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- skywalking 8.4

- What happened?
Cannot search for tags on log and trace pages(SQL Storage: h2/mysql/pg/)

___
### Requirement or improvement
- I am trying to fix.

### PR DESCRIPTION
**Pull request by hailin0**
### Fix <https://github.com/apache/skywalking/issues/6504>
- [ ] Add a unit test to verify that the fix works.
- [ ] Explain briefly why the bug exists and how to fix it.
  1. Fix tags_{n} storage cloumn index, consistent with [query tag index](https://github.com/apache/skywalking/blob/master/oap-server/server-storage-plugin/storage-jdbc-hikaricp-plugin/src/main/java/org/apache/skywalking/oap/server/storage/plugin/jdbc/h2/dao/H2LogQueryDAO.java#L149)
  2. Fix key error of get previousValue

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #6504.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
I think you also should update the e2e tests? FYI @kezhenxu94 @arugal this bug has not been found in current e2e.

**Comment by hailin0** [comment]
> I think you also should update the e2e tests? FYI @kezhenxu94 @arugal this bug has not been found in current e2e.

OK 👌

**Comment by wu-sheng** [comment]
Hi @hailin0 I moved this bug fix into backend  part changelog. You put it into the project catalog.

**Comment by wu-sheng** [comment]
@kezhenxu94 @arugal Please recheck E2E.

**Review by kezhenxu94 — APPROVED** [review]
LGTM, thanks.

**Review by wu-sheng — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Review by wu-sheng — CHANGES_REQUESTED** [review]
I think you somehow break some e2e themselves. Please recheck.

**Comment by hailin0** [comment]
> I think you somehow break some e2e themselves. Please recheck.

👌

**Review by wu-sheng — APPROVED** [review]
@kezhenxu94 Please recheck the e2e, others are good to me.

**Review by wu-sheng — APPROVED** [review]

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
