### PR TITLE
support elasticsearch address configuration with http scheme.

### PR DESCRIPTION
**Pull request by JaredTan95**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

### CODE REVIEW

**Comment by JaredTan95** [comment]
> Why put http here? Are you trying to support https?

yes

**Comment by wu-sheng** [comment]
Put an optional config in es storage provider. This change breaks existing user config, but get little benifit.

Add a config named protocol, use http as default value.

**Comment by wu-sheng** [comment]
Wait for e2e

**Pull request merged**
