### PR TITLE
Append interceptors to elasticsearch-6.x-plugin

### PR DESCRIPTION
**Pull request by CommissarXia**
### <Feature description>
- [ ] If this is non-trivial feature, paste the links/URLs to the design doc.
- [ ] Update the documentation to include this new feature.
- [x] Tests(including UT, IT, E2E) are added to verify the new feature.
- [ ] If it's UI related, attach the screenshots below.

Before appending, Analyze, searchScroll, clearScroll, searchTemplate and deleteByQuery will be tracked through HTTP. In order to show uniformity, our company has modified the jar package separately to replace it, but it is too troublesome. In order to facilitate more people to use, so submit this pr.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
> Update the CHANGES log.

Please follow this.

**Comment by CommissarXia** [comment]
The change log has been committed.

**Comment by wu-sheng** [comment]
Pending on @dmsolr 's review.

**Review by dmsolr — DISMISSED** [review]
LGTM

**Comment by zifeihan** [comment]
Hello, it looks no problem. There is a request, can you provide the relevant scenario or polish elasticsearch-6.x-scenario?

**Comment by wu-sheng** [comment]
@CommissarXia Please follow the reviewer's comments. And your code style issue breaks all CI processes.

**Comment by CommissarXia** [comment]
Oh, I'm sorry, I didn't notice that IDEA automatically merges the import package, it has been modified and submitted.

**Comment by CommissarXia** [comment]
Ok, I will modify the IDEA configuration according to the format control file.

**Comment by wu-sheng** [comment]
I am feeling you haven't run the maven test locally. Please recheck.

**Comment by CommissarXia** [comment]
I have corrected and run maven test successful locally.

**Comment by wu-sheng** [comment]
Follow the code scanner's comments, please.

**Comment by CommissarXia** [comment]
Ok. I have removed unnecessary grouping parentheses and committed. And thank everybody for careful examining and correcting.

**Comment by wu-sheng** [comment]
Have you read the plugin dev doc? The last part of it describes how we test the plugin. https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md#plugin-test-tool

The elasticsearch 6.x tests are here, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios/elasticsearch-6.x-scenario

Please add your new supported ES operations in the demo codes, and modify the expected data file to match them.

**Comment by wu-sheng** [comment]
Also, please note, these tests should be verified locally, and don't cost the unnecessary upstream resources.

**Comment by wu-sheng** [comment]
@CommissarXia Any feedback?

**Comment by wu-sheng** [comment]
@dmsolr Is this PR safe to be merged? If so, please approve, otherwise, let's wait for more updage.

**Review by dmsolr — APPROVED** [review]
It looks good to me.

**Pull request merged**
