### PR TITLE
Fix inconsistent virtual cache describe between code and scope definitions doc

### PR DESCRIPTION
**Pull request by pg-yang**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
One more, https://github.com/apache/skywalking/pull/9622#issuecomment-1254442278

**Comment by pg-yang** [comment]
It's  necessary to update change.md . Right?

**Review by wu-sheng — COMMENTED** [review]
Once you changed the source codes, OAL has to change according.

**Comment by wu-sheng** [comment]
Also, antlr grammar file. 
Changlog is not relative breaking, you don't need to change, because this feature is not released.

**Comment by pg-yang** [comment]
Got it , I should  run test case on my PC firstly .

**Comment by pg-yang** [comment]
Local test have passed

**Review by wu-sheng — APPROVED** [review]
Once e2e passed, it should be good.

**Comment by pg-yang** [comment]
Somethings throw error  after reruning

**Comment by wu-sheng** [comment]
What things? Something env relative?

**Comment by pg-yang** [comment]
Done , a full test take half of day

**Comment by wu-sheng** [comment]
In the afternoon, we would face resource competition with all other projects mostly working at Euro.

**Pull request merged**
