### PR TITLE
 Fix the problem of Kafka transport topics are created duplicated with and without namespace

### LINKED ISSUE #7326: Kafka transport topics are created duplicated with and without namespace
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
 skywalking8.6.0,mac,jdk1.8.0_191

- What happened?
oap creates wrong topic when I write namespace with "yanggy" string value in kafka-fetcher item;

Below is my operation steps;

1. give namespace a string value
```yaml
kafka-fetcher:
  selector: ${SW_KAFKA_FETCHER:default}
  default:
    bootstrapServers: ${SW_KAFKA_FETCHER_SERVERS:localhost:9092}
    namespace: ${SW_NAMESPACE:"yanggy"}
    partitions: ${SW_KAFKA_FETCHER_PARTITIONS:2}
    replicationFactor: ${SW_KAFKA_FETCHER_PARTITIONS_FACTOR:2}
    enableMeterSystem: ${SW_KAFKA_FETCHER_ENABLE_METER_SYSTEM:false}
    enableNativeProtoLog: ${SW_KAFKA_FETCHER_ENABLE_NATIVE_PROTO_LOG:false}
    enableNativeJsonLog: ${SW_KAFKA_FETCHER_ENABLE_NATIVE_JSON_LOG:false}
    isSharding: ${SW_KAFKA_FETCHER_IS_SHARDING:false}
    consumePartitions: ${SW_KAFKA_FETCHER_CONSUME_PARTITIONS:""}
    kafkaHandlerThreadPoolSize: ${SW_KAFKA_HANDLER_THREAD_POOL_SIZE:-1}
    kafkaHandlerThreadPoolQueueSize: ${SW_KAFKA_HANDLER_THREAD_POOL_QUEUE_SIZE:-1}
```
2. start oap server
3. show topics using kafka-manager
  

   we can see that oap creates seven redundant topics without "yanggy" prefix and four wrong topics with "yanggy" prefix; because the partitions of  the topic with "yanggy" prefix is wrong; the partition and replica all shoud be 2;

___
#### First let's see how oap creates topics.
```java
// the KafkaFetcherHandlerRegister class  77-115 lines
AdminClient adminClient = AdminClient.create(properties);
        Set<String> missedTopics = adminClient.describeTopics(Lists.newArrayList(
            config.getTopicNameOfManagements(),
            config.getTopicNameOfMetrics(),
            config.getTopicNameOfProfiling(),
            config.getTopicNameOfTracingSegments(),
            config.getTopicNameOfMeters(),
            config.getTopicNameOfLogs(),
            config.getTopicNameOfJsonLogs()
        ))
                                              .values()
                                              .entrySet()
                                              .stream()
                                              .map(entry -> {
                                                  try {
                                                      entry.getValue().get();
                                                      return null;
                                                  } catch (InterruptedException | ExecutionException ignore) {
                                                  }
                                                  return entry.getKey();
                                              })
                                              .filter(Objects::nonNull)
                                              .collect(Collectors.toSet());

        if (!missedTopics.isEmpty()) {
            log.info("Topics" + missedTopics.toString() + " not exist.");
            List<NewTopic> newTopicList = missedTopics.stream()
                                                      .map(topic -> new NewTopic(
                                                          topic,
                                                          config.getPartitions(),
                                                          (short) config.getReplicationFactor()
                                                      )).collect(Collectors.toList());

            try {
                adminClient.createTopics(newTopicList).all().get();
            } catch (Exception e) {
                throw new ModuleStartException("Failed to create Kafka Topics" + missedTopics + ".", e);
            }
        }
```

oap just gets topics without using namespace !

#### Second let's see why there are four topics having "yanggy" prefix

```
  // the KafkaFetcherHandlerRegister class
   public void start() {
        handlerMap = builder.build();
        if (isSharding) {
            consumer.assign(topicPartitions);
        } else {
            consumer.subscribe(handlerMap.keySet());
        }
        consumer.seekToEnd(consumer.assignment());
        executor.submit(this);
    }
```
 When the start method run, consume will subscribe some topics; if the topic doesn't exist, it will create with one partition and one replica;

___
###  Requirement or improvement
If the bug is true, I will  move the logic of creating topic in oap from prepare phase to start phase. after doing this,  there are two benefits. one is the logic of getting kafka topic name when creating and subscribe kafka topic at oap side is unified. another is the logic of creating topic at oap side and sending metric data to topic at agent is consistent.  oap wouldn't create redundant  topics such as "logs" topic.

```java
public void start() throws ModuleStartException {
        handlerMap = builder.build();

        createTopicIfNeeded(handlerMap.keySet(), properties);

        if (isSharding) {
            consumer.assign(topicPartitions);
        } else {
            consumer.subscribe(handlerMap.keySet());
        }
        consumer.seekToEnd(consumer.assignment());
        executor.submit(this);
    }

  private void createTopicIfNeeded(Collection<String> topics, Properties properties) throws ModuleStartException {
        AdminClient adminClient = AdminClient.create(properties);
        Set<String> missedTopics = adminClient.describeTopics(topics)
                                              .values()
                                              .entrySet()
                                              .stream()
                                              .map(entry -> {
                                                  try {
                                                      entry.getValue().get();
                                                      return null;
                                                  } catch (InterruptedException | ExecutionException ignore) {
                                                  }
                                                  return entry.getKey();
                                              })
                                              .filter(Objects::nonNull)
                                              .collect(Collectors.toSet());

        if (!missedTopics.isEmpty()) {
            log.info("Topics" + missedTopics.toString() + " not exist.");
            List<NewTopic> newTopicList = missedTopics.stream()
                                                      .map(topic -> new NewTopic(
                                                          topic,
                                                          config.getPartitions(),
                                                          (short) config.getReplicationFactor()
                                                      )).collect(Collectors.toList());

            try {
                adminClient.createTopics(newTopicList).all().get();
            } catch (Exception e) {
                throw new ModuleStartException("Failed to create Kafka Topics" + missedTopics + ".", e);
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by Cool-Coding**
Fix (#7326)
- [x] Explain briefly why the bug exists and how to fix it.
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #7326.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

How to fix:
1. wrap the logic of creating kafka topic into a method named <code>createTopicIfNeeded</code>.   
2. move <code>createTopicIfNeeded</code> to start method before consume subscribes topic.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you check the logs why profiling task fails?

**Comment by Cool-Coding** [comment]
> Could you check the logs why profiling task fails?

@wu-sheng Please wait a moment, I have run maven test locally, it is successful. I will still work on it. So far, I haven't found any connection between this failed profiling task and my modification

**Comment by wu-sheng** [comment]
> > Could you check the logs why profiling task fails?
> 
> @wu-sheng Please wait a moment, I have run maven test locally, it is successful. I will still work on it. So far, I haven't found any connection between this failed profiling task and my modification

Take your time, it shows in e2e tests. Not maven's unit tests.

**Comment by Cool-Coding** [comment]
> > > Could you check the logs why profiling task fails?
> > 
> > 
> > @wu-sheng Please wait a moment, I have run maven test locally, it is successful. I will still work on it. So far, I haven't found any connection between this failed profiling task and my modification
> 
> Take your time, it shows in e2e tests. Not maven's unit tests.

@wu-sheng I test my modification in whitebox and blackbox mode again. it works well. e2e test needs oap and ui docker image, it is a little troublesome. I have been working on it for some hours. The failed task is profiling task at first time, lt's meter task at second time. it's confusing.  I will continue do this tomorrow.

**Comment by kezhenxu94** [comment]
@Cool-Coding as the `meter` case is unstable sometimes, I've just rerun it, you can look into it only if it is still failed.

**Comment by wu-sheng** [comment]
> @Cool-Coding as the `meter` case is unstable sometimes, I've just rerun it, you can look into it only if it is still failed.

I just update the branch, if just `meter` fails, then it is fine. It doesn't relate to Kafka I think.

**Review by wu-sheng — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Comment by Cool-Coding** [comment]
> > @Cool-Coding as the `meter` case is unstable sometimes, I've just rerun it, you can look into it only if it is still failed.
> 
> I just update the branch, if just `meter` fails, then it is fine. It doesn't relate to Kafka I think.

@wu-sheng  yes,it's just meter fails at second time. thank you.

**Comment by Cool-Coding** [comment]
> @Cool-Coding as the `meter` case is unstable sometimes, I've just rerun it, you can look into it only if it is still failed.

@kezhenxu94 thank you!

**Pull request merged**
