### PR TITLE
Fix the unexpected RunningContext recreation in the Tomcat plugin.

### PR DESCRIPTION
**Pull request by haoyann**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #NO.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).NO NEED

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is the reason for changing this?

**Comment by haoyann** [comment]
> What is the reason for changing this?

`ContextManager.stopSpan()` and RUNTIME_CONTEXT is removed，ContextManager.getRuntimeContext() will create new RuntimeContext.

**Review by wu-sheng — APPROVED** [review]
LGTM. I updated the changelog for you. Please remember to describe the issue in the PR and changelog.

**Comment by haoyann** [comment]
> LGTM. I updated the changelog for you. Please remember to describe the issue in the PR and changelog.


Thanks  : )

**Pull request merged**
