### PR TITLE
support jedis pipeline

### LINKED ISSUE #6434: jedis not support pipeline
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Feature or performance improvement

___
### Question
- What do you want to know?
I look into jedis-2.x plugin, find that enhanceClass is redis.clients.jedis.Jedis.
But pipeline will directly invoke jedis client.
Jedis --invoke---> client
pipeline ---invoke-->client

There are two solution to solve this  problem
1. just enhance client
2. enhance both Jedis and Pipeline

### PR DESCRIPTION
**Pull request by xuanyu66**
### <Feature description>
- [ ] If this is non-trivial feature, paste the links/URLs to the design doc.
- [X] Update the documentation to include this new feature.
- [X] Tests(including UT, IT, E2E) are added to verify the new feature.
- [ ] If it's UI related, attach the screenshots below.

- [X] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #6434 .
- [X] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Read plugin development doc, one step is missing. We need the plugin e2e test.

**Comment by xuanyu66** [comment]
> Read plugin development doc, one step is missing. We need the plugin e2e test.

OK

**Review by wu-sheng — APPROVED** [review]
LGTM, once all tests passed.

**Review by wu-sheng — CHANGES_REQUESTED** [review]
Plugin tests fail, please recheck.

**Comment by wu-sheng** [comment]
I think you should run the test locally, there is no actual span generated. You could read the logs by yourself.

**Comment by xuanyu66** [comment]
> I think you should run the test locally, there is no actual span generated. You could read the logs by yourself.

image
It look just OK for me

**Comment by xuanyu66** [comment]
> I think you should run the test locally, there is no actual span generated. You could read the logs by yourself.

I ran the test ,found out it's compatible with version 2.9.0 2.8.2 2.7.3, but not compatible with version 2.6.3 and before.
Before 2.6.3, the parent class of pipeline has package private access, so it will bring java.lang.NoSuchMethodError

**Comment by wu-sheng** [comment]
> I ran the test ,found out it's compatible with version 2.9.0 2.8.2 2.7.3, but not compatible with version 2.6.3 and before.
> Before 2.6.3, the parent class of pipeline has package private access, so it will bring java.lang.NoSuchMethodError

Have you tried to find other intercepting points? Such as intercept the parent methods directly? SkyWalking enhancement doesn't care it is a public or private method.

**Comment by xuanyu66** [comment]
@wu-sheng It's done now

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
