### PR TITLE
FIX: Failed to create ExitSpan when thrift transport is not enhanced

### PR DESCRIPTION
**Pull request by xuanyu66**
### Fix <bug description or the bug issue number or bug issue link>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.

When transport is't enhanced by plugin, TServiceClient will fail to set SkyWalkingDynamicField, which make create exit span failed.
I validate transport, if it is not enhanced, set the SkyWalkingDynamicField with "UNKNOWN"

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think the question is, why not enhanced? Which should not happen.

**Comment by xuanyu66** [comment]
> I think the question is, why not enhanced? Which should not happen.

If Someone import some package which implement new transport, which is situation we met.
I think it can not avoid，we need some Safeguard

**Comment by wu-sheng** [comment]
Could you explain about new transport? Why wouldn't we enhance that?

**Comment by xuanyu66** [comment]
> Could you explain about new transport? Why wouldn't we enhance that?

It's jaeger that implement ThriftUdpTransport for UdpSender

```
public class UdpSender extends ThriftSender {
  public static final String DEFAULT_AGENT_UDP_HOST = "localhost";
  public static final int DEFAULT_AGENT_UDP_COMPACT_PORT = 6831;

  @ToString.Exclude private Agent.Client agentClient;
  @ToString.Exclude private ThriftUdpTransport udpTransport;

  /**
   * This constructor expects Jaeger running running on {@value #DEFAULT_AGENT_UDP_HOST}
   * and port {@value #DEFAULT_AGENT_UDP_COMPACT_PORT}
   */
  public UdpSender() {
    this(DEFAULT_AGENT_UDP_HOST, DEFAULT_AGENT_UDP_COMPACT_PORT, 0);
  }

  /**
   * @param host host e.g. {@value DEFAULT_AGENT_UDP_HOST}
   * @param port port e.g. {@value DEFAULT_AGENT_UDP_COMPACT_PORT}
   * @param maxPacketSize if 0 it will use {@value ThriftUdpTransport#MAX_PACKET_SIZE}
   */
  public UdpSender(String host, int port, int maxPacketSize) {
    super(ProtocolType.Compact, maxPacketSize);

    if (host == null || host.length() == 0) {
      host = DEFAULT_AGENT_UDP_HOST;
    }

    if (port == 0) {
      port = DEFAULT_AGENT_UDP_COMPACT_PORT;
    }

    udpTransport = ThriftUdpTransport.newThriftUdpClient(host, port);
    agentClient = new Agent.Client(protocolFactory.getProtocol(udpTransport));
  }
```

**Comment by dmsolr** [comment]
Do you mean customizing transport?

**Comment by xuanyu66** [comment]
> Do you mean customizing transport?

yes, some package maybe  customize transport , we need some safeguard

**Comment by wu-sheng** [comment]
Please resolve conflict.

**Comment by xuanyu66** [comment]
> Please resolve conflict.

done

**Comment by dmsolr** [comment]
> > Do you mean customizing transport?
> 
> yes, some package maybe customize transport , we need some safeguard

This is a known issue. In this scenario, there are two things maybe we need to consider.
1. whether we can get the "peer" from transport
2. can we cover all customized cases

**Comment by xuanyu66** [comment]
> > > Do you mean customizing transport?
> > 
> > 
> > yes, some package maybe customize transport , we need some safeguard
> 
> This is a known issue. In this scenario, there are two things maybe we need to consider.
> 
> 1. whether we can get the "peer" from transport
> 2. can we cover all customized cases

I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport

**Comment by wu-sheng** [comment]
> > > > Do you mean customizing transport?
> > > 
> > > 
> > > yes, some package maybe customize transport , we need some safeguard
> > 
> > 
> > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > 
> > 1. whether we can get the "peer" from transport
> > 2. can we cover all customized cases
> 
> I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> What's your opinion?

My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.

**Comment by dmsolr** [comment]
I agree with @wu-sheng said. Thrift plugin is complex enough and easy to break other cases. I am worried about this.

**Comment by xuanyu66** [comment]
> > > > > Do you mean customizing transport?
> > > > 
> > > > 
> > > > yes, some package maybe customize transport , we need some safeguard
> > > 
> > > 
> > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > 
> > > 1. whether we can get the "peer" from transport
> > > 2. can we cover all customized cases
> > 
> > 
> > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > What's your opinion?
> 
> My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.

we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.

**Comment by wu-sheng** [comment]
> > > > > > Do you mean customizing transport?
> > > > > 
> > > > > 
> > > > > yes, some package maybe customize transport , we need some safeguard
> > > > 
> > > > 
> > > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > > 
> > > > 1. whether we can get the "peer" from transport
> > > > 2. can we cover all customized cases
> > > 
> > > 
> > > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > > What's your opinion?
> > 
> > 
> > My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.
> 
> we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.

It seems strange. Are you saying your thrift is using 2 kinds of transport implementations in one service? Why?

**Comment by xuanyu66** [comment]
> > > > > > > Do you mean customizing transport?
> > > > > > 
> > > > > > 
> > > > > > yes, some package maybe customize transport , we need some safeguard
> > > > > 
> > > > > 
> > > > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > > > 
> > > > > 1. whether we can get the "peer" from transport
> > > > > 2. can we cover all customized cases
> > > > 
> > > > 
> > > > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > > > What's your opinion?
> > > 
> > > 
> > > My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.
> > 
> > 
> > we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.
> 
> It seems strange. Are you saying your thrift is using 2 kinds of transport implementations in one service? Why?

We use official transport to call rpc, jaeger use its customized transport to report trace span

**Comment by wu-sheng** [comment]
> > > > > > > > Do you mean customizing transport?
> > > > > > > 
> > > > > > > 
> > > > > > > yes, some package maybe customize transport , we need some safeguard
> > > > > > 
> > > > > > 
> > > > > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > > > > 
> > > > > > 1. whether we can get the "peer" from transport
> > > > > > 2. can we cover all customized cases
> > > > > 
> > > > > 
> > > > > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > > > > What's your opinion?
> > > > 
> > > > 
> > > > My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.
> > > 
> > > 
> > > we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.
> > 
> > 
> > It seems strange. Are you saying your thrift is using 2 kinds of transport implementations in one service? Why?
> 
> We use official transport to call rpc, jaeger use its customized transport to report trace span.
> there are two different thrift client

That is strange, why SkyWalking needs to work with Jaeger? What is the use case?

**Comment by xuanyu66** [comment]
> > > > > > > > > Do you mean customizing transport?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > yes, some package maybe customize transport , we need some safeguard
> > > > > > > 
> > > > > > > 
> > > > > > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > > > > > 
> > > > > > > 1. whether we can get the "peer" from transport
> > > > > > > 2. can we cover all customized cases
> > > > > > 
> > > > > > 
> > > > > > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > > > > > What's your opinion?
> > > > > 
> > > > > 
> > > > > My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.
> > > > 
> > > > 
> > > > we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.
> > > 
> > > 
> > > It seems strange. Are you saying your thrift is using 2 kinds of transport implementations in one service? Why?
> > 
> > 
> > We use official transport to call rpc, jaeger use its customized transport to report trace span.
> > there are two different thrift client
> 
> That is strange, why SkyWalking needs to work with Jaeger? What is the use case?

Which I want to say is that other package may implement their own customized transport to send message at the same time we use official transport to call rpc between services. Should we take this situation into account.

**Comment by wu-sheng** [comment]
> > > > > > > > > > Do you mean customizing transport?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > yes, some package maybe customize transport , we need some safeguard
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > > > > > > 
> > > > > > > > 1. whether we can get the "peer" from transport
> > > > > > > > 2. can we cover all customized cases
> > > > > > > 
> > > > > > > 
> > > > > > > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > > > > > > What's your opinion?
> > > > > > 
> > > > > > 
> > > > > > My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.
> > > > > 
> > > > > 
> > > > > we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.
> > > > 
> > > > 
> > > > It seems strange. Are you saying your thrift is using 2 kinds of transport implementations in one service? Why?
> > > 
> > > 
> > > We use official transport to call rpc, jaeger use its customized transport to report trace span.
> > > there are two different thrift client
> > 
> > 
> > That is strange, why SkyWalking needs to work with Jaeger? What is the use case?
> 
> Which I want to say is that other package may implement their own customized transport to send message at the same time we use official transport to call rpc between services. Should we take this situation into account.

I have to repeat the point I said before. `MAY` is not a thing the community should take care of. Some real and reasonable use cases are. It is really rare to see a service using 2 RPC protocols but sharing the same framework. And also, you mentioned, SkyWalking and Jaeger are being deployed at the same time. We have no intention to compete, but also I have no vision why you need both at the same time, especially you are talking in Java stack.
Maybe you have something that can't be shared in public, but at the same time, I am afraid, open-source community and project are responding to open information only.

**Comment by xuanyu66** [comment]
> > > > > > > > > > > Do you mean customizing transport?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > yes, some package maybe customize transport , we need some safeguard
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > This is a known issue. In this scenario, there are two things maybe we need to consider.
> > > > > > > > > 
> > > > > > > > > 1. whether we can get the "peer" from transport
> > > > > > > > > 2. can we cover all customized cases
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I think we just set UNKNOWN, if someone want to enhance some customized transport, they can contribute themselves, we should only support official transport.
> > > > > > > > What's your opinion?
> > > > > > > 
> > > > > > > 
> > > > > > > My question would be, if this is not an official transport implementation, why should SkyWalking take care of? User could remove the thrift plugin directly.
> > > > > > 
> > > > > > 
> > > > > > we want to trace thrift rpc call, and it work properly. But other dependency with customized transport cause IllegalStateException.
> > > > > 
> > > > > 
> > > > > It seems strange. Are you saying your thrift is using 2 kinds of transport implementations in one service? Why?
> > > > 
> > > > 
> > > > We use official transport to call rpc, jaeger use its customized transport to report trace span.
> > > > there are two different thrift client
> > > 
> > > 
> > > That is strange, why SkyWalking needs to work with Jaeger? What is the use case?
> > 
> > 
> > Which I want to say is that other package may implement their own customized transport to send message at the same time we use official transport to call rpc between services. Should we take this situation into account.
> 
> I have to repeat the point I said before. `MAY` is not a thing the community should take care of. Some real and reasonable use cases are. It is really rare to see a service using 2 RPC protocols but sharing the same framework. And also, you mentioned, SkyWalking and Jaeger are being deployed at the same time. We have no intention to compete, but also I have no vision why you need both at the same time, especially you are talking in Java stack.
> Maybe you have something that can't be shared in public, but at the same time, I am afraid, open-source community and project are responding to open information only.

OK,I get your point

**Comment by wu-sheng** [comment]
Should we close this? Or you want to add more context?

**Comment by xuanyu66** [comment]
> Should we close this? Or you want to add more context?

yes, close this

**Pull request closed without merging**
