### PR TITLE
Refine Compatible-with-other-javaagent-bytecode-processing.md and rename to Compatibility-with-other-Java-agent-bytecode-processes.md

### PR DESCRIPTION
**Pull request by wingwong-knh**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
Hi, Wing, I think you accidentally removed the `.md` suffix.

**Comment by wingwong-knh** [comment]
> Hi, Wing, I think you accidentally removed the `.md` suffix.

@wu-sheng Oops sorry! Should I submit a new pull request on this edit?

**Comment by kezhenxu94** [comment]
> > Hi, Wing, I think you accidentally removed the `.md` suffix.
> 
> @wu-sheng Oops sorry! Should I submit a new pull request on this edit?

@wingwong-knh you can edit in this branch directly, [here](https://github.com/wingwong-knh/skywalking/edit/patch-1/docs/en/FAQ/Compatibility-with-other-Java-agent-bytecode-processes), 

image

**Review by kezhenxu94 — APPROVED** [review]

**Comment by kezhenxu94** [comment]
File `./docs/en/setup/service-agent/java-agent/README.md` contains a reference to this file, which is renamed, can you please also correct that link in the aforementioned file?

**Comment by wu-sheng** [comment]
Hi, if there is no big grammar error in the file name, we should keep the old one. Because as github URL and website URL is widely used in other blocks, our changes could cause 404.

**Comment by wingwong-knh** [comment]
> Hi, if there is no big grammar error in the file name, we should keep the old one. Because as github URL and website URL is widely used in other blocks, our changes could cause 404.

@wu-sheng  Ah OK, I agree. I think it's fine to keep the file name as it is. Let's revert this edit?

**Comment by wu-sheng** [comment]
> > Hi, if there is no big grammar error in the file name, we should keep the old one. Because as github URL and website URL is widely used in other blocks, our changes could cause 404.
> 
> @wu-sheng Ah OK, I agree. I think it's fine to keep the file name as it is. Let's revert this edit?

Make sense, let me keep it. And keep the old name could make reviewers more clear about what you changed. Otherwise, we see this, purely add a new file.
image

If we should rename a file name in the future, let's use a separated PR to change the file name only.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
