### PR TITLE
Fix MQE Binary Operation between labeled metrics and other type of value result.

### PR DESCRIPTION
**Pull request by wankai123**
- [ ] If this is non-trivial feature, paste the links/URLs to the design doc.
- [ ] Update the documentation to include this new feature.
- [X] Tests(including UT, IT, E2E) are added to verify the new feature.
- [ ] If it's UI related, attach the screenshots below.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [X] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you update the MQE docs about how to apply the operation between labeled values with no-label values, as well as other combinations?

**Comment by kezhenxu94** [comment]
> Could you update the MQE docs about how to apply the operation between labeled values with no-label values, as well as other combinations?

Do we have real use case for "operation between labeled values with no-label values, and other combinations"?

In the doc, I only see this is valuable:

> If we want to transform the percentile value unit from `ms` to `s` the expression is:
> ```text
> service_percentile{_='0,1'} / 1000
> ```

All the other operations, such as `avg(service_percentile{_='0,1'})`, `service_percentile{_='0,1'} - avg(service_percentile{_='0,1'})` don't make any sense to me in reality. Can we come out with some more useful examples in the doc?

**Comment by wu-sheng** [comment]
> Do we have real use case for "operation between labeled values with no-label values, and other combinations"?

AFAIK, I can't say the current cases are perfect, but it could be useful if we are going to measure the long tail case. 

This may not be used in the metric query, but MQE could use this in the alerting rule settings.

**Comment by wankai123** [comment]
> Can we come out with some more useful examples in the doc?

`avg(service_percentile{_='0,1'})` calculate the avg resp_time in `P50,P70`
`service_percentile{_='0,1'} - avg(service_percentile{_='0,1'}`  calculate the deviation from avg resp_time in `P50,P70`
`service_resp_time - service_percentile{_='0,1'}` calculate the difference from all request avg resp_time between `P50,P70`

I think these calculations make sense in statistics.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
