### PR TITLE
add Baidu on the powered-by page

### PR DESCRIPTION
**Pull request by EvanLjp**
Please answer these questions before submitting pull request

add power by

### CODE REVIEW

**Comment by EvanLjp** [comment]
skywalking have been running in a test environment before and will be deployed online next week.
In the future ,i would like to share this.Our department belongs to the tob industry, the data size will not be very large.

**Comment by wu-sheng** [comment]
Interesting, due to #4793, it shows you care about the large scale deployment very much.

**Comment by EvanLjp** [comment]
🙈In Friday,our es cluster is restarted due to some failure, the es cluster store logs data and some skywalking index in test env and preonline env.
Before I knew it, I thought that shards num was for segment record,so i set the number is 5
Because of too many shards in the cluster, the restart time is so long
so,I commit the PR 
https://github.com/apache/skywalking/pull/4793

**Comment by wu-sheng** [comment]
That PR is meaningful, I remembered some people asked about this, but they didn't submit the pull request to fix that in the upstream. Thanks.

**Comment by EvanLjp** [comment]
I remember the 7.0.0 merge some metrics together.
Nowadays,I think skywalking's pressure on es may mainly come from unreasonable allocation of shards,Hope this PR can solve the pressure on es 
https://github.com/apache/skywalking/pull/4793

**Comment by wu-sheng** [comment]
> Nowadays,I think skywalking's pressure on es may mainly come from unreasonable allocation of shards,Hope this PR can solve the pressure on es

If you have some monitoring data to prove this, welcome to let us know. Reducing shards should be a good thing. And also in 8.0.0, we removed the register, which should help to get rid of lock in the es level.

**Comment by EvanLjp** [comment]
ok,i would be focus on it 
When there is time, I will continue to mention some PR,do you think the following content makes sense?
1. spring annotation plugin add regex match,avoid intercepting all spring beans
2. dynamic get config from kubernetes configMap

**Comment by EvanLjp** [comment]
I don't know why the pipline fail ,cloud you follow up @wu-sheng

**Comment by wu-sheng** [comment]
Could you start separated issues to discuss these with details? It makes more people to follow the context.

**Comment by EvanLjp** [comment]
Ok,I would to open a new discuss

**Pull request merged**
