### PR TITLE
fix the order of segments at the same level

### PR DESCRIPTION
**Pull request by bnubobby**
Please answer these questions before submitting pull request

for the #3844

### CODE REVIEW

**Comment by wu-sheng** [comment]
Does this sort work?

**Comment by wu-sheng** [comment]
We have multiple implementation of storage. If you order at database side, you need to change all. H2 and Mysql.

**Comment by bnubobby** [comment]
@wu-sheng  
Does this mean that I need to make the same changes on H2 and MySQL?

**Comment by wu-sheng** [comment]
> Does this mean that I need to make the same changes on H2 and MySQL?

Yes, if you have checked this change makes the UI right, can you confirm?

**Comment by wu-sheng** [comment]
Why close?

**Pull request closed without merging**
