### PR TITLE
Migrate from kubernetes-client/java to fabric8 client

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
I'm going to add some improvements in ALS receiver by mapping Istio ServiceEntries IP to service, and found fabric8's Kubernetes client has Istio client extension, but official Kubernetes client has no such client, I don't think we want to re-implement the Istio Java client by ourselves, so this PR migrates from kubernetes official java client to fabric8's.

I also found the APIs in fabrics8 client is fluent and more friendly...

**Comment by wu-sheng** [comment]
> so this PR migrates from kubernetes official java client to fabric8's

Does this mean the k8s java client is going to be removed from our dependency tree?

**Comment by kezhenxu94** [comment]
> > so this PR migrates from kubernetes official java client to fabric8's
> 
> 
> 
> Does this mean the k8s java client is going to be removed from our dependency tree?

Yes

**Review by wu-sheng — APPROVED** [review]
FYI @wankai123

**Pull request merged**
