### PR TITLE
Optimize the self monitoring grafana dashboard.

### PR DESCRIPTION
**Pull request by Ax1an**
#6498 

Optimize the self monitoring grafana dashboard.

SkyWalking OAP Cluster Monitor Dashboard: 

image

SkyWalking OAP Instance Monitor Dashboard: 

image

- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
# Some screenshots with more metrics (not perfectly complete)
<details>
  <summary>Click to expand</summary>
  
Screen Shot 2021-03-19 at 13 39 06
Screen Shot 2021-03-19 at 13 39 13
Screen Shot 2021-03-19 at 13 39 25
Screen Shot 2021-03-19 at 13 39 31
Screen Shot 2021-03-19 at 13 44 38
Screen Shot 2021-03-19 at 13 44 46
Screen Shot 2021-03-19 at 13 44 52
Screen Shot 2021-03-19 at 13 44 58
Screen Shot 2021-03-19 at 13 45 03
</details>


Generally LGTM, @Ax1an can you please take a look at this 👇 the unit (25 min) looks unreasonable.

Screen Shot 2021-03-19 at 13 49 14

**Comment by Ax1an** [comment]
@kezhenxu94 
I've looked at your question carefully, but in fact, the default unit after I import is seconds. Have you adjusted the chart unit after importing?

From your screenshot, I found that there is something wrong with the legend of some charts, which has been adjusted.

image

image

**Comment by kezhenxu94** [comment]
I didn't change anything

**Comment by Ax1an** [comment]
@kezhenxu94 

According to your screenshot, I found that the cluster dashboard is good, there is a problem with the instance dashboard. 

Could you edit these two panels to see if their units are different?

image

image

**Comment by wu-sheng** [comment]
I am a little confused, what `Minute` and `Second` suffixes mean? I can see the Y axle doesn't match in many cases.

@Ax1an The question is, how the latency could be 25mins.

**Comment by wu-sheng** [comment]
I think @kezhenxu94 's concern is there is a bug existing about converting the unit.

**Comment by wu-sheng** [comment]
I think most latency in the second when report.

https://github.com/apache/skywalking/blob/25214e910a193fbf22511ce6048964f4ce4d3048/oap-server/server-telemetry/telemetry-api/src/main/java/org/apache/skywalking/oap/server/telemetry/api/HistogramMetrics.java#L51

**Review by kezhenxu94 — APPROVED** [review]
Well, must be something wrong in my previous env, tested in a new env and it works.

**Comment by Ax1an** [comment]
@wu-sheng 

I use the rate function to represent the number of seconds.

I use the increase function to represent the increments per minute.

For example, let's assume that there are two persistence_timer_bulk_prepare operations between 09: 59 and 10: 00, which take 20 seconds and 10 seconds respectively. Then, it took 2 minutes to do next persistence_timer_bulk_prepare operation.

This panel should look like this: 

image

This may be difficult to understand at first. It works better when you get used to it. It can help us to intuitively see some high-latency single operation.

**Comment by Ax1an** [comment]
For all time related metrics, the default unit I set is second, because I have also read the part of the code you said.

You can see this in the configuration file.

image

**Comment by wu-sheng** [comment]
> @wu-sheng
> 
> I use the rate function to represent the trend in number per second.
> 
> I use the increase function to represent the increments per minute.
> 
> For example, let's assume that there are two persistence_timer_bulk_prepare operations between 09: 59 and 10: 00, which take 20 seconds and 10 seconds respectively. Then, it took 2 minutes to do next persistence_timer_bulk_prepare operation.
> 
> This panel should look like this:
> 
> image
> 
> This may be difficult to understand at first. It works better when you get used to it. It can help us to intuitively see some high-latency single operation. In order to optimize it.

So, basically, you are showing trend.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
