### PR TITLE
keepAlive msg have to load from database, fectch the properties when …

### PR DESCRIPTION
**Pull request by lubberland**
…there is no sessionCache

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I am not following. The data should either cached with latest or loaded.

**Comment by lubberland** [comment]
> I am not following. The data should either cached with latest or loaded.

https://github.com/apache/skywalking/issues/10796#issuecomment-1556611342
please see this link

**Comment by lubberland** [comment]
when there is no sessionCache for InstanceTraffic
1 、the skywalking service just started
2、the sessionCache was expired
then get a keepalive metrics from http interface or kafka consumer
```
private Metrics requireInitialization(Metrics metrics) {
        final Metrics cached = sessionCache.get(metrics);

        // All cached metrics, it at least had been written once.
        if (cached != null) {
            return cached;
        }

        // If the metrics do not have time bucket relative ID
        // it is treated as high dimensionality metrics.
        // Policy, always try load from the database when miss in the cache.
        if (!model.isTimeRelativeID()) {
            return null;
        }

        // When
        // (1) the time bucket of the server's latest stability status is provided
        //     1.1 the OAP has booted successfully
        //     1.2 the current dimensionality is in minute
        //     1.3 the OAP cluster is rebalanced due to scaling
        // (2) the metrics are from the time after the timeOfLatestStabilitySts
        // (3) the metrics don't exist in the cache
        // the kernel should NOT try to load it from the database.
        //
        // Notice, about condition (2),
        // for the specific minute of booted successfully, the metrics are expected to load from database when
        // it doesn't exist in the cache.
        if (timeOfLatestStabilitySts > 0 &&
            metrics.getTimeBucket() > timeOfLatestStabilitySts
            && cached == null) {
            // Return metrics as input to avoid reading from database.
            return metrics;
        }

        return null;
    }
```

requireInitialization will return metrics,  and do not load  from storage, do not call combine() ,then call  prepareBatchInsert() ,  then the properties is null

this is the pr https://github.com/apache/skywalking/pull/10841  for simple fix

**Comment by wu-sheng** [comment]
I saw that, but properties are reported periodically too. There may be several minutes latency, but eventually, it would be overrided back to normal.
We don't know there would be properties or nor, we don't want to risk reloading everytime if therw is no property for some agents.

**Comment by lubberland** [comment]
1、in java-agent, the kafka producter send keepalive and register msg , use the different key, so the two msg will be consumed by different consumer.
2、for http interface, we use  a domain name (nginx )for the skywalking cluster,  after the balancer,  the two msg may be handled by different skywalking service.
so the properties is often null
when "it would be overrided back to normal.", after one or two minutes ,  the properties will by null again.

i agree with "We don't know there would be properties or nor, we don't want to risk reloading everytime if therw is no property for some agents."   
 the agent writed by unofficial  is uncontrollable

**Comment by lubberland** [comment]
thank you !   I will check the cluster config . Thank you very much for guidance

**Pull request closed without merging**
