### PR TITLE
Add 200000 microsecond sleep in E2E-PHP

### PR DESCRIPTION
**Pull request by heyanlong**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
why sleep so long unnecessarily? This will slow down the checks drastically

**Comment by heyanlong** [comment]
> why sleep so long unnecessarily? This will slow down the checks drastically 


simulation 200ms processing time

**Comment by kezhenxu94** [comment]
> > why sleep so long unnecessarily? This will slow down the checks drastically 
> 
> 
> simulation 200ms processing time

Your title is misleading, which says sleep 200000ms=200s=~2minutes

**Comment by wu-sheng** [comment]
@kezhenxu94 I think the title is microsecond, not ms, which usually is meaning millionseconds

**Pull request merged**
