### PR TITLE
Update docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by BZFYS**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Welcome to be a new contributor.

**Comment by BZFYS** [comment]
> 欢迎成为新的贡献者。

Thank you

**Pull request merged**
