### PR TITLE
Fix incorrect use of ReentrantLock in GRPCExporter

### PR DESCRIPTION
**Pull request by xuxiawei**
fix that an imse (illegalmonitorstateexception) exception will be thrown when finally releasing the lock when an exception occurs in lock() locking

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please take a look at `ReentrantLock` comments in JDK.

```java
 * <p>It is recommended practice to <em>always</em> immediately
 * follow a call to {@code lock} with a {@code try} block, most
 * typically in a before/after construction such as:
 *
 * <pre> {@code
 * class X {
 *   private final ReentrantLock lock = new ReentrantLock();
 *   // ...
 *
 *   public void m() {
 *     lock.lock();  // block until condition holds
 *     try {
 *       // ... method body
 *     } finally {
 *       lock.unlock()
 *     }
 *   }
 * }}</pre>
```

**Comment by wu-sheng** [comment]
Reject this according to JDK recommendation, unless there are other scenarios not covered by JDK comments.

**Comment by kezhenxu94** [comment]
@wu-sheng the patch in this PR exactly changes the codes to what recommended in JDK comment, why close this?

**Comment by wu-sheng** [comment]
Sorry my fault. The cell phone visualization mislead me.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
