### PR TITLE
spring-cloud-gateway traceid does not transmit #3411

### PR DESCRIPTION
**Pull request by hi-sb**
skywalking-version:6.5.0

spring-gateway-version:2.1.2

Error Description:

 Customize the filter, traceid does not transmit.

 "ServerWebExchangeDecorator" is a transport chain,His structure should be like this：

	 serverWebExchangeDecorator
	    -----(ServerWebExchangeDecorator)delegate
		    ------(ServerWebExchangeDecorator)delegate
			  ------.....
			   -----(DefaultServerWebExchange)delegate
  In the current source code, there is no deep search, but only the next level. When there are multiple custom filters, you get an error.

Repair method:

  Look for "delegate" of "ServerWebExchangeDecorator" recursively until "DefaultServerWebExchange"

Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by zhaoyuguang** [comment]
Oh, I may understand, what do you think of using the recursive method, but I hope you add this scenario to the [gateway testcase](https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/gateway-scenario), to make the plugin test more realistic

**Comment by hi-sb** [comment]
my test pull request:

https://github.com/SkyAPMTest/agent-auto-integration-testcases/pull/88

**Comment by zhaoyuguang** [comment]
CI not pass, please check

**Comment by hi-sb** [comment]
Modified style to meet "check style"

**Comment by zhaoyuguang** [comment]
I had triggered the `gateway` and `webflux` auto tests, let's wait for the result

**Comment by zhaoyuguang** [comment]
Look like @Component annotation cause more spans

**Comment by hi-sb** [comment]
@zhaoyuguang This should be another issue.We can't restrict other people from using this annotation.

**Comment by wu-sheng** [comment]
> This should be another issue.We can't restrict other people from using this annotation.

This is not an issue of this PR, but an issue for your test case.

**Comment by hi-sb** [comment]
@wu-sheng I mean, in actual development, there may be people who write as they do in use cases. We can't avoid such problems. But this problem does not fall within the scope of this repair.

**Comment by wu-sheng** [comment]
The point is, I recommend you to add these spans to your verify files, as expected span. Because in tests, the Spring annotation plugin actives with your gateway plugin. Both of them are optional, the test framework only supports them both active or inactive.

**Comment by hi-sb** [comment]
I see what you mean. What you mean is that this annotation activates other plug-ins. I shouldn't do that in use cases.

**Comment by hi-sb** [comment]
@zhaoyuguang @wu-sheng Sorry,We just started using "skywalking".I'm not too familiar with the other plug-ins he owns. I updated my use case.

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang @wu-sheng Sorry,We just started using "skywalking".I'm not too familiar with the other plug-ins he owns. I updated my use case.

Ha~, it doesn't matter, I just tested it, in `skywalking-agent-testcases/gateway-scenario/projectA/docker/startup.sh` line5 add ` rm -rf ${AGENT_FILE_PATH}/plugins/apm-spring-annotation -plugin-*.jar` can work as we expect

**Comment by hi-sb** [comment]
@zhaoyuguang What else do I need to do?

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang What else do I need to do?

Just remove `apm-spring-annotation-plugin-*.jar` can avoid this interceptor

**Comment by wu-sheng** [comment]
@hi-sb Welcome to be 155th contributor. Welcome to the SkyWalking contributor team.

**Pull request merged**
