### PR TITLE
Multi-data source (same host:port) gets db.instance data error #4941

### PR DESCRIPTION
**Pull request by HackerRookie**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ *] Bug fix
- [ *] New feature provided
- [ ] Improve performance

- Related issues
#4941 
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Your codes are not passing the CI. Please fix.

**Comment by HackerRookie** [comment]
> I am not sure your fix. Why remove old cache? This could be performance issue.

1. The ConnectionCache here uses host:port to make the key, in the case of shard tables or multiple data sources (if a database instance has many database, hos and port will be the same) get the db.instance (intercepted from url) is not accurate database name .
2. Here's just parsing url. Performance is not responsive to ignore

**Comment by wu-sheng** [comment]
I still can't get your point. An ip:port is a unique address in the network, where there are many instances? Where are they?

**Comment by wu-sheng** [comment]
More importantly, why you could have a different result from URL parsing? Could you share more details about what you are doing?

**Comment by HackerRookie** [comment]
> I still can't get your point. An ip:port is a unique address in the network, where there are many instances? Where are they?

image
sns01-sns0 host:port same(sns01 is database name)
sns05 - sns10 ........
sns11 - sns 16

Three sets of database services

**Comment by wu-sheng** [comment]
We don't separate the database name, that is another thing. The topology is focusing on the distributed system. You are talking about the multiple databases in one DB process, right?

**Comment by HackerRookie** [comment]
> We don't separate the database name, that is another thing. The topology is focusing on the distributed system. You are talking about the multiple databases in one DB process, right?

Right

**Comment by wu-sheng** [comment]
Right now, we don't have the intent to separate the database.  I can't tell whether we should or shouldn't, but either of them is not the reason, you break the cache.

If you want to add the database entity as a part of topology and the analysis perspective, you should change the cache to include `host:port:db-name`, and also change the peer of the span, which could make the database metrics in the DB dashboard separated too.

**Comment by HackerRookie** [comment]
> Right now, we don't have the intent to separate the database. I can't tell whether we should or shouldn't, but either of them is not the reason, you break the cache.
> 
> If you want to add the database entity as a part of topology and the analysis perspective, you should change the cache to include `host:port:db-name`, and also change the peer of the span, which could make the database metrics in the DB dashboard separated too.

image
In the case of multiple data sources, tags db.instance is currently wrong to take the value of the code.

**Comment by wu-sheng** [comment]
> In the case of multiple data sources, tags db.instance is currently wrong to take the value of the code.

What do you mean wrong? What should it be?

**Comment by HackerRookie** [comment]
> > In the case of multiple data sources, tags db.instance is currently wrong to take the value of the code.
> 
> What do you mean wrong? What should it be?

because of sns01 sns02 sns03 sns04 host:port same. So there's only one database name in the collection cache. Should be displayed separately

**Comment by wu-sheng** [comment]
I think that is caused by the usage of `Tags#DB_INSTANCE`. It saved the database name for now. We haven't given a very specific definition, but it seems like they are treated as the database name in many plugins, I mean for now. 

Like this,
image

**Pull request closed without merging**
