### PR TITLE
Shall not use * for static import.

### PR DESCRIPTION
**Pull request by wayilau**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

I think we always shall not use * for static import. also this file only a little method. we could import them directly to improve readability.

### CODE REVIEW

**Comment by wu-sheng** [comment]
We don't set this rule. If you want to add a new rule, please explain why.

**Comment by wu-sheng** [comment]
Right now, we are very flexible in most coding styling things, as long as it doesn't affect the performance and readable, at least I am good for that.

**Comment by wayilau** [comment]
> We don't set this rule. If you want to add a new rule, please explain why.
static import is useful to reduce our coding.  bug sometime it is confused to read, but here not.
i just think we only use three method, so import directly is enough. it doesn't effect the performance indeed. it is just my idea.

**Comment by wu-sheng** [comment]
We can't make sure whether this change will be undone if someone prefers another way :) If we want to set one way, we need to change style and style check files, which mean a lot of files need to change.

If there is no benefit from there, I suggest we don't do that.

**Pull request closed without merging**
