### PR TITLE
Set version to 8.1.0 for next iteration.

### PR DESCRIPTION
**Pull request by wu-sheng**
8.0.0->8.1.0

### CODE REVIEW

**Comment by wu-sheng** [comment]
@yu199195 ShardingSphere test cases show unstable(data don't match) twice. I am retrying. Please be advised.

**Comment by wu-sheng** [comment]
@yu199195 It seems to keep failing? Could you take a look?

**Comment by yu199195** [comment]
@wu-sheng  hi， sheng，my PR provider  is shardingsphere-4.x-scenario， but I haven't seen the test results of this project， why？，  shardingsphere-4.x-RC1-RC2-scenario  is an error. It was provided before，I'll keep an eye on it。

**Comment by wu-sheng** [comment]
@yu199195 Because I rerun it. And yes, it comes from the old case. The logs just say expected data don't match. I don't know what causes that. 
I want to merge this PR, so just retry it. But the unstable seems to keep happening.

**Comment by wu-sheng** [comment]
@yu199195 The error is here, https://github.com/apache/skywalking/pull/4916/checks?check_run_id=764945306

**Comment by yu199195** [comment]
i down logs， and check in

**Comment by yu199195** [comment]
I down logs， and check in

**Comment by yu199195** [comment]
I compared the logs carefully with  expectedData.yaml in shardingSphere-4.x-RC3, no mismatches found..

**Comment by wu-sheng** [comment]
@dmsolr ShardingSphere tests fail 3+ times. 

@yu199195 I noticed, there are large logs generated. Could you check locally?

**Pull request merged**
