### PR TITLE
[Break Change] Remove endpoint name in backend log and browser log query

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

* [Break Change] Remove page path in the browser log query condition. Only support `query by page path id`.
* [Break Change] Remove endpoint name in the backend log query condition. Only support `query by endpoint id`.
* [Break Change] Fix typo for a column `page_path_id`(was `pate_path_id`) of storage entity `browser_error_log`.   

FYI @lujiajing1126

### CODE REVIEW

**Comment by lujiajing1126** [comment]
@hanahmily I suppose we also have to remove `*_name` definitions in BanyanDB schema

**Comment by wu-sheng** [comment]
> @hanahmily I suppose we also have to remove `*_name` definitions in BanyanDB schema

These fields require wildcard query, which impacts the performance potentially. We don't need to waste time on this feature.

**Comment by wu-sheng** [comment]
@Fine0830 Please help on rechecking, the pages of Trace/Log(Service/Browser) are not using endpoint name in the GraphQL query condition. I remember they have been changed to endpoint ID, please confirm.

**Comment by Fine0830** [comment]
> @Fine0830 Please help on rechecking, the pages of Trace/Log(Service/Browser) are not using endpoint name in the GraphQL query condition. I remember they have been changed to endpoint ID, please confirm.

Now, the endpoint name is used in the query trace condition. Log is using endpoint id.

**Comment by wu-sheng** [comment]
> > @Fine0830 Please help on rechecking, the pages of Trace/Log(Service/Browser) are not using endpoint name in the GraphQL query condition. I remember they have been changed to endpoint ID, please confirm.
> 
> 
> 
> Now, the endpoint name is used in the query trace condition. Log is using endpoint id.

But I can't see endpoint name condition in thr UI. If there is legacy codes, could you remove it? @Fine0830

**Comment by Fine0830** [comment]
> > > @Fine0830 Please help on rechecking, the pages of Trace/Log(Service/Browser) are not using endpoint name in the GraphQL query condition. I remember they have been changed to endpoint ID, please confirm.
> > 
> > 
> > Now, the endpoint name is used in the query trace condition. Log is using endpoint id.
> 
> But I can't see endpoint name condition in the UI. If there are legacy codes, could you remove it? @Fine0830

It's a selector. Here update it to endpoint id?
WechatIMG28

**Comment by wu-sheng** [comment]
Selector is fine. My point is trace query GraphQL, it should not use endpoint name any more. Could you check the query request?

**Review by kezhenxu94 — APPROVED** [review]

**Comment by lujiajing1126** [comment]
@wu-sheng Pls kindly update the integration branch. Thx

**Comment by kezhenxu94** [comment]
> @wu-sheng Pls kindly update the integration branch. Thx

Why should we have this branch in this repo and sync it over and over? instead of creating it on @lujiajing1126 your fork repo?

**Comment by lujiajing1126** [comment]
> > @wu-sheng Pls kindly update the integration branch. Thx
> 
> Why should we have this branch in this repo and sync it over and over? instead of creating it on @lujiajing1126 your fork repo?

The integration will not be merged to the master branch and will be pending util all features are ready (Trace, Log and Metrics).

**Comment by wu-sheng** [comment]
I could sync, but also, @kezhenxu94 is correct. Why have to do? @lujiajing1126 You could sync the master branch to your codebase directly if needed. 
I could do this manually this time, but really, this is not necessary.

**Comment by kezhenxu94** [comment]
> > > @wu-sheng Pls kindly update the integration branch. Thx
> > 
> > 
> > Why should we have this branch in this repo and sync it over and over? instead of creating it on @lujiajing1126 your fork repo?
> 
> The integration will not be merged to the master branch and will be pending util all features are ready (Trace, Log and Metrics).

The codes can be in your fork repo always and you can sync from upstream at anytime you like, and do whatever you like until you think it's ready to open a pull request.

**Comment by wu-sheng** [comment]
The branch is even with master now.

**Comment by lujiajing1126** [comment]
> > > > @wu-sheng Pls kindly update the integration branch. Thx
> > > 
> > > 
> > > Why should we have this branch in this repo and sync it over and over? instead of creating it on @lujiajing1126 your fork repo?
> > 
> > 
> > The integration will not be merged to the master branch and will be pending util all features are ready (Trace, Log and Metrics).
> 
> The codes can be in your fork repo always and you can sync from upstream at anytime you like, and do whatever you like until you think it's ready to open a pull request.

Yes. What I was doing is fetching from upstream (i.e. Apache/Skywalking repo) and rebase from the `banyandb-integration` branch. So when I submit the PR, the compare view will be clear that it only shows what I have changed. Or it will be contaminated with codes from master.

But I guess it would also be OK if you sync when I submit the next PR.

**Comment by wu-sheng** [comment]
> > > > > @wu-sheng Pls kindly update the integration branch. Thx
> > > > 
> > > > 
> > > > Why should we have this branch in this repo and sync it over and over? instead of creating it on @lujiajing1126 your fork repo?
> > > 
> > > 
> > > The integration will not be merged to the master branch and will be pending util all features are ready (Trace, Log and Metrics).
> > 
> > 
> > The codes can be in your fork repo always and you can sync from upstream at anytime you like, and do whatever you like until you think it's ready to open a pull request.
> 
> Yes. What I was doing is fetching from upstream (i.e. Apache/Skywalking repo) and rebase from the `banyandb-integration` branch. So when I submit the PR, the compare view will be clear that it only shows what I have changed. Or it will be contaminated with codes from master.
> 
> But I guess it would also be OK if you sync when I submit the next PR.

Actually, before we merge the branch into the master, there is not necessary to keep the branch updated. The core of SkyWalking is quite stable, even in the 8.7.0 big perf improvement, there are not many codes to be changed. 
You focus on what you are doing, and resolve the conflicts, sync the codes when it is ready to run.

**Pull request merged**
