### PR TITLE
Cancel duplicated workflows

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>. NO
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
New native GHA features to cancel duplicated jobs https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

**Comment by wu-sheng** [comment]
> New native GHA features to cancel duplicated jobs https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

Is this for canceling or blocking duplicated tasks? From my read, this seems like blocking multiple commits CI tasks?

**Comment by kezhenxu94** [comment]
> > New native GHA features to cancel duplicated jobs https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
> 
> Is this for canceling or blocking duplicated tasks? From my read, this seems like blocking multiple commits CI tasks?

Read more in the links of what I posted. 
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run

**Review by wu-sheng — APPROVED** [review]
Should we cancel my personal GHA about canceling?

**Comment by kezhenxu94** [comment]
> Should we cancel my personal GHA about canceling?

I’ll disable it.

**Pull request merged**
