### PR TITLE
fix: k8s otel document path error

### PR DESCRIPTION
**Pull request by innerpeacez**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by innerpeacez** [comment]
otel-rules/mysql.yaml
otel-rules/postgresql.yaml

I also found that these files were missing

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
> otel-rules/mysql.yaml
> 
> otel-rules/postgresql.yaml
> 
> 
> 
> I also found that these files were missing

Missing or path wrong?

**Comment by innerpeacez** [comment]
> > otel-rules/mysql.yaml
> > otel-rules/postgresql.yaml
> > I also found that these files were missing
> 
> Missing or path wrong?

Maybe the file name was changed.

image

**Comment by wu-sheng** [comment]
> > > otel-rules/mysql.yaml
> > > otel-rules/postgresql.yaml
> > > I also found that these files were missing
> > 
> > 
> > Missing or path wrong?
> 
> Maybe the file name was changed.
> 
> image

@yswdqz Could you recheck and fix the docs?

**Pull request merged**
