### PR TITLE
Add unit tests for server-cluster-plugin module

### PR DESCRIPTION
**Pull request by flycash**
Add unit tests for cluster-consul, cluster-zookeeper, cluster-kubernetes

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance
- [X] Add unit tests

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Submodules shouldn't be updated.

**Comment by wu-sheng** [comment]
Please take a look at #2570 , and open multiple jdk and os versions, including the #2570 fix.
I want to check whether the tests could pass.

**Comment by flycash** [comment]
I think I need some help. I don't know why the change list contains the submodule because I only add some unit tests. 
Can you give me some suggestions to solve the problem?

**Comment by wu-sheng** [comment]
I think we update submodule to older version. From the latest to your local version.
Two ways,
1. Read git document and update them again to master submodule commit id.
2. Fork from master again.

**Pull request merged**
