### PR TITLE
Add `count` function for MAL down sampling.

### PR DESCRIPTION
**Pull request by peachisai**
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

This is my scenario
In ```rocketmq``` different consumer group has a different consumer offset

```
rocketmq_consumer_offset{cluster="DefaultCluster",broker="broker-a",topic="topic1",group="group3",} 347.0
rocketmq_consumer_offset{cluster="DefaultCluster",broker="broker-a",topic="topic1",group="group2",} 601.0
rocketmq_consumer_offset{cluster="DefaultCluster",broker="broker-a",topic="topic1",group="group1",} 694.0
```
Downsampling the metrics count 
```
  - name: consumer_group_count
    exp: rocketmq_consumer_offset.sum(['cluster','topic','group']).downsampling(COUNT)
```

 Then I can get the consumer group number to caculate the blacklog messages
```
producer_offset*consumer_group_count- consumer_offset
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
How to make this count accurate when downsampling mechanism affect in hour and day precision?

**Comment by wankai123** [comment]
Sorry, I don't seem to understand the point. Do you expect the result of consumer_group_count is `3`, according to the following expression?
```
  - name: consumer_group_count
    exp: rocketmq_consumer_offset.sum(['cluster','topic','group']).downsampling(COUNT)
```

**Comment by peachisai** [comment]
> Sorry, I don't seem to understand the point. Do you expect the result of consumer_group_count is `3`, according to the following expression?
> 
> ```
>   - name: consumer_group_count
>     exp: rocketmq_consumer_offset.sum(['cluster','topic','group']).downsampling(COUNT)
> ```

Yes,I want to acqurie the number of consumer group count

**Comment by wankai123** [comment]
> Yes,I want to acqurie the number of consumer group count

Then I think you need a `MAL count func rather than a downsampling func`, such as 
```
rocketmq_consumer_offset.count()
```
Downsampling is used to aggregate the result of the metric in (m/h/d).

**Comment by wu-sheng** [comment]
> > Yes,I want to acqurie the number of consumer group count
> 
> 
> 
> Then I think you need a `MAL count func rather than a downsampling func`, such as 
> 
> ```
> 
> rocketmq_consumer_offset.count()
> 
> ```
> 
> Downsampling is used to aggregate the result of the metric in (m/h/d).
> 
> 
> 
> 

And avg or latest for downsampling seems more reasonable?

**Comment by peachisai** [comment]
> > Yes,I want to acqurie the number of consumer group count
> 
> Then I think you need a `MAL count func rather than a downsampling func`, such as
> 
> ```
> rocketmq_consumer_offset.count()
> ```
> 
> Downsampling is used to aggregate the result of the metric in (m/h/d).

It seems cannot invoke
```
2024-02-02 11:28:54,508 org.apache.skywalking.oap.meter.analyzer.dsl.Expression 92 [main] ERROR [] - [10.0.0-SNAPSHOT-8fb408a] failed to run "(rocketmq_consumer_offset.sum(['cluster','topic','group']).count()).tag({tags -> tags.cluster = 'rocketmq::' + tags.cluster}).endpoint(['cluster'], ['topic'], Layer.ROCKETMQ)"
groovy.lang.MissingMethodException: No signature of method: org.apache.skywalking.oap.meter.analyzer.dsl.SampleFamily.count() is applicable for argument types: () values: []
Possible solutions: print(java.io.PrintWriter), print(java.lang.Object), minus(java.lang.Number), minus(org.apache.skywalking.oap.meter.analyzer.dsl.SampleFamily), wait(), any()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72) ~[groovy-4.0.15.jar:4.0.15]
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:163) ~[groovy-4.0.15.jar:4.0.15]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) ~[groovy-4.0.15.jar:4.0.15]
	at Script1.run(Script1.groovy:1) ~[?:?]
	at org.apache.skywalking.oap.meter.analyzer.dsl.Expression.run(Expression.java:81) ~[classes/:?]
	at org.apache.skywalking.oap.meter.analyzer.dsl.Expression.parse(Expression.java:59) ~[classes/:?]
	at org.apache.skywalking.oap.meter.analyzer.Analyzer.build(Analyzer.java:92) ~[classes/:?]
	at org.apache.skywalking.oap.meter.analyzer.MetricConvert.buildAnalyzer(MetricConvert.java:74) ~[classes/:?]
	at org.apache.skywalking.oap.meter.analyzer.MetricConvert.lambda$new$2(MetricConvert.java:61) ~[classes/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.apache.skywalking.oap.meter.analyzer.MetricConvert.<init>(MetricConvert.java:67) ~[classes/:?]
	at org.apache.skywalking.oap.meter.analyzer.prometheus.PrometheusMetricConverter.<init>(PrometheusMetricConverter.java:73) ~[classes/:?]
	at org.apache.skywalking.oap.server.receiver.otel.otlp.OpenTelemetryMetricRequestProcessor.lambda$start$8(OpenTelemetryMetricRequestProcessor.java:130) ~[classes/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) [?:?]
	at org.apache.skywalking.oap.server.receiver.otel.otlp.OpenTelemetryMetricRequestProcessor.start(OpenTelemetryMetricRequestProcessor.java:131) [classes/:?]
	at org.apache.skywalking.oap.server.receiver.otel.OtelMetricReceiverProvider.start(OtelMetricReceiverProvider.java:93) [classes/:?]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) [classes/:?]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:75) [classes/:?]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:52) [classes/:?]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [classes/:?]
```

**Comment by peachisai** [comment]
> groovy.lang.MissingMethodException: No signature of method: org.apache.skywalking.oap.meter.analyzer.dsl.SampleFamily.count() is applicable for argument types: () values: []
> Possible solutions: print(java.io.PrintWriter), print(java.lang.Object), minus(java.lang.Number), minus(org.apache.skywalking.oap.meter.analyzer.dsl.SampleFamily), wait(), any()

It seems not compatible

**Comment by peachisai** [comment]
> > > Yes,I want to acqurie the number of consumer group count
> > 
> > 
> > Then I think you need a `MAL count func rather than a downsampling func`, such as
> > ```
> > 
> > rocketmq_consumer_offset.count()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Downsampling is used to aggregate the result of the metric in (m/h/d).
> 
> And avg or latest for downsampling seems more reasonable?

It seems not compatible

**Comment by wankai123** [comment]
> It seems not compatible

`count()` is not supported yet, you need to implement it if required.
https://github.com/apache/skywalking/blob/fc3cc4bd878e41b2eee84a0bbed3f3808b3ef9b9/docs/en/concepts-and-designs/mal.md#aggregation-operation

**Comment by peachisai** [comment]
> > It seems not compatible
> 
> `count()` is not supported yet, you need to implement it if required. https://github.com/apache/skywalking/blob/fc3cc4bd878e41b2eee84a0bbed3f3808b3ef9b9/docs/en/concepts-and-designs/mal.md#aggregation-operation

Okay,Thank you, I will have a try laterly

**Comment by wu-sheng** [comment]
> > > > Yes,I want to acqurie the number of consumer group count
> 
> > > 
> 
> > > 
> 
> > > Then I think you need a `MAL count func rather than a downsampling func`, such as
> 
> > > ```
> 
> > > 
> 
> > > rocketmq_consumer_offset.count()
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > Downsampling is used to aggregate the result of the metric in (m/h/d).
> 
> > 
> 
> > And avg or latest for downsampling seems more reasonable?
> 
> 
> 
> It seems not compatible

I mean it is suitable if you have counter for general function, rather than downsampling.
How to count for downsampling would be very tricky. One day could have dozens of merging, it doesn't indicate your original meaning anymore, right?

**Comment by peachisai** [comment]
> > > > > Yes,I want to acqurie the number of consumer group count
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Then I think you need a `MAL count func rather than a downsampling func`, such as
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > rocketmq_consumer_offset.count()
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Downsampling is used to aggregate the result of the metric in (m/h/d).
> > 
> > 
> > > 
> > 
> > 
> > > And avg or latest for downsampling seems more reasonable?
> > 
> > 
> > It seems not compatible
> 
> I mean it is suitable if you have counter for general function, rather than downsampling. How to count for downsampling would be very tricky. One day could have dozens of merging, it doesn't indicate your original meaning anymore, right?

Oh, I think I make some misunderstands, I mean the ```count``` aggregation function is not compatible with the code now, I just kown I should implement it. I also agree that ```count``` by aggregation function and downsampling the latest meter is better

I will try to implement the ```count``` aggregation function later.

> > > > > Yes,I want to acqurie the number of consumer group count
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Then I think you need a `MAL count func rather than a downsampling func`, such as
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > rocketmq_consumer_offset.count()
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Downsampling is used to aggregate the result of the metric in (m/h/d).
> > 
> > 
> > > 
> > 
> > 
> > > And avg or latest for downsampling seems more reasonable?
> > 
> > 
> > It seems not compatible
> 
> I mean it is suitable if you have counter for general function, rather than downsampling. How to count for downsampling would be very tricky. One day could have dozens of merging, it doesn't indicate your original meaning anymore, right?

Oh, I think I make some misunderstands, I mean the ```count``` aggregation function is not compatible with the code now, I just kown I should implement it. I also agree that ```count``` by aggregation function and downsampling the latest meter is better

**Comment by peachisai** [comment]
I will  use `count` aggragation in place of the `count` downsampling

**Comment by wu-sheng** [comment]
> I will  use `count` aggragation in place of the `count` downsampling

I am doubt about this logic. Because logically, count for downsampling only works for counting events, offset can't be aggregated or counted between latest data and existing data.

**Pull request closed without merging**
