### PR TITLE
Add Nginx component ID to main repo

### PR DESCRIPTION
**Pull request by wu-sheng**
Add 84 as Nginx component ID

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@wu-sheng do we want to start from a larger number of id (instead of 84) for the NEW language Lua?

**Comment by wu-sheng** [comment]
> do we want to start from a larger number of id (instead of 84) for the NEW language Lua?

I don't know :P Currently, only one component for Nginx Lua now.

**Comment by wu-sheng** [comment]
@kezhenxu94 If you think we will have more span in Nginx level, I could change that.

**Comment by aderm** [comment]
LGTM

**Comment by kezhenxu94** [comment]
> > do we want to start from a larger number of id (instead of 84) for the NEW language Lua?
> 
> I don't know :P Currently, only one component for Nginx Lua now.

Seems the id ranges are divided according to different languages, instead of frameworks (i.e. Nginx),  if there are any possibility that we may another components written by Lua(not necessarily in Nginx level) , I think it's better to start from another id number and give Lua a range; what's more, 84 makes the Java id range non-continuous (1-83 and 85 to xxx) 😅 odd, harmless though

**Comment by kezhenxu94** [comment]
I'm good to merge this anyway, it does no harm, feel free to merge 😄

**Comment by wu-sheng** [comment]
@kezhenxu94 Updated ID to 6000 as a separated group.

**Pull request merged**
