### PR TITLE
Optimising docker image size.

### PR DESCRIPTION
**Pull request by JaredTan95**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

In my opinion, I think the final image is too big.
If there are no special requirements for the docker image, we can optimize it in some way.

Before:
```bash
skywalking/ui                               latest      733MB
skywalking/oap                              latest     834MB
```

After:
```bash
skywalking/ui                               latest     83.4MB
skywalking/oap                              latest    184MB
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is the difference between two basic images?

**Comment by wu-sheng** [comment]
@TinyAllen I think you should consider adding an e2e stage(parallel) to check the image we built in dev stage.

**Comment by wu-sheng** [comment]
@JaredTan95 I think you should consider adding an e2e stage(parallel) to check the image we built in dev stage.

**Comment by JaredTan95** [comment]
Closed, temporarily. Others need to be done.

**Comment by hanahmily** [comment]
Seems like there’s no `bash` in it. entrypoint script can not be executed.

**Pull request closed without merging**
