### PR TITLE
fix recording url tag with wrong port

### PR DESCRIPTION
**Pull request by ralphgj**
### Fix <bug description or the bug issue number or bug issue link>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.
The default port is -1 in `URI`, now use empty string instead of the default value.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
Confirmed through `java.net.URL` source code. Good catch.

**Comment by ralphgj** [comment]
sorry, I had a mistake and recommit now. please review again, thx.

**Comment by wu-sheng** [comment]
> sorry, I had a mistake and recommit now. please review again, thx.

You just did a force push, I can't see what you changed. Could you be clear about that?

**Review by wu-sheng — APPROVED** [review]

**Review by wu-sheng — CHANGES_REQUESTED** [review]
Please check the plugin test logs. Your change breaks the tests.

**Review by wu-sheng — APPROVED** [review]
When all plugin tests passed, this should be good.

**Pull request merged**
