### PR TITLE
close inputStream safety & FIX NPE in AlarmService

### PR DESCRIPTION
**Pull request by IanCao**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@peng-yongsheng review this one and check v6 codes

**Comment by wu-sheng** [comment]
@peng-yongsheng review this one and check v6 codes to avoid this.

**Comment by peng-yongsheng** [comment]
I'm not sure it is actually fixed the too many open files bug. 
@IanCao Do you running with this code over one day ago?

**Comment by wu-sheng** [comment]
No matter does this fix file handler issue. The codes look like an issue to me.

**Comment by IanCao** [comment]
> I'm not sure it is actually fixed the too many open files bug.
> @IanCao Do you running with this code over one day ago?

no, It just started today. and i'll pay more attention to check whether this bug has solved or not

**Comment by wu-sheng** [comment]
Feedback from the test, this PR can't fix the file handle leak. Just consider this as a code style issue.

**Pull request merged**
