### PR TITLE
Support ZGC metric is OAP and UI

### LINKED ISSUE #8411: [Feature] support zgc metric collect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

zgc is new GarbageCollector from jdk 11, it is the most advanced  GarbageCollector util now, now skywalking gc not support collect the metric

### Use case

agent collect zgc count and time, from skywalking ui we can see 

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xu1009**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #8411 .
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by xu1009** [comment]
it is still failed, the error message is strange

**Comment by wu-sheng** [comment]
This error usually means the docker-compose can't bootstrap. Could you try the docker image locally?

**Comment by wu-sheng** [comment]
Notice, the UI template updates may be reset in the near future, as the 9.0.0 UI uses a different template structure.
Welcome back to recheck when it is ready on Mar.

**Review by wu-sheng — APPROVED** [review]

**Comment by xu1009** [comment]
ok

**Pull request merged**
