### PR TITLE
test: add JDK 15 into test matrix

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

Based on https://adoptopenjdk.net/support.html, we have JDK 15 release from OpenJDK jdk-15.0.1+9 20th Oct 2020. It was released first at Sep. 2020. It is very new, I am trying to test whether we have any break there.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Seems the tests passed while the Jacoco plugin failed to analyze the result, only the latest snapshot of Jacoco support JDK 15

https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by wu-sheng** [comment]
Thanks for locating the issue already. Let's wait for the next Jacoco release.

**Comment by wu-sheng** [comment]
```
Change History
Snapshot Build 0.8.7.202012290703 (2020/12/29)
New Features
JaCoCo now officially supports Java 15 (GitHub #1094, #1097).
Experimental support for Java 17 class files (GitHub #1132).
Non-functional Changes
JaCoCo now depends on ASM 9.0 (GitHub #1094, #1097).
Maven plug-in has no dependency on maven-reporting-impl any more (GitHub #1121).
```

Waiting for the next formal release.

**Review by kezhenxu94 — APPROVED** [review]
Luckily, JaCoCo 0.8.6 has supported JDK 15 (experimental though) and I've upgraded to 0.8.6 in https://github.com/apache/skywalking/pull/6631 so this PR is good to go

**Pull request merged**
