### PR TITLE
Add go-redis to component-libraries.yml

### LINKED ISSUE #10879: [Feature] Go auto-instrument agent support go-redis
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[go-redis](https://github.com/redis/go-redis) is a Golang Redis client for Redis Server and Redis Cluster, and it's widely used.

Since we have [skywalking-go](https://github.com/apache/skywalking-go) now, it might be good to cover this Redis client. There is no Redis client available on the [Supported Libraries](https://skywalking.apache.org/docs/skywalking-go/next/en/agent/support-plugins/#supported-libraries) now. 

Before start working on it, **I would like to have some supporters for this proposal.**

### Use case

Addressed in the description.

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

I think it's a good first issue for new community developers. So I would like to try it if we have supporters.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jiekun**
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by jiekun** [comment]
The component id will be used in auto instrument implementation. This PR is marked as draft for now. I will link the auto instrument PR here later.

**Comment by wu-sheng** [comment]
Don't use close, this wouldn't finish the issue you mentioned.

**Comment by wu-sheng** [comment]
If this is a draft, you have a button to switch this PR into draft status.

**Comment by jiekun** [comment]
> If this is a draft, you have a button to switch this PR into draft status.

Thank you for your timely response. Issue mentioned above are fixed. I will ping for reviewer once the PR is ready. :)

**Comment by jiekun** [comment]
> I think this should be ready to merge?

Yes. Draft status removed.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
