### PR TITLE
Add Apache ShenYu (incubating) component ID (#8796)

### PR DESCRIPTION
**Pull request by hutaishi**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
You should upload the logo to booster UI, and update submodule here too.

**Comment by wu-sheng** [comment]
You need your project logo here, if you want it showing up in the topology, please add and try it locally.

https://github.com/apache/skywalking-booster-ui/tree/main/src/assets/img/technologies

Recommend using compressed ~10k size logo, and provide a screenshot here to verify it is suitable from color and size.

**Comment by hutaishi** [comment]
Thinks. I'll prepare the logo

**Comment by hutaishi** [comment]
> You need your project logo here, if you want it showing up in the topology, please add and try it locally.
> 
> https://github.com/apache/skywalking-booster-ui/tree/main/src/assets/img/technologies
> 
> Recommend using compressed ~10k size logo, and provide a screenshot here to verify it is suitable from color and size.

### LOGO:
APACHESHENYU

### screenshot
image

**Pull request merged**
