### PR TITLE
Fix Agent Plugin "asynchttpclient" not record the status code of the …

### PR DESCRIPTION
**Pull request by darcydai**
…response

### Fix <agent asynchttpclient plugin not record the response status code>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.
     add a tag to async span when status received method be invoked

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
You need to update the changelog.

**Comment by darcydai** [comment]
> You need to update the changelog.
 Hi sheng, I have added change log

**Review by ascrutae — APPROVED** [review]

**Review by ascrutae — COMMENTED** [review]
You should also changed the expected data of async http client scenario. Link:   https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/asynchttpclient-scenario/config/expectedData.yaml

**Review by ascrutae — CHANGES_REQUESTED** [review]
You should also changed the expected data of async http client scenario. Link: https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/asynchttpclient-scenario/config/expectedData.yaml

**Comment by darcydai** [comment]
> You should also changed the expected data of async http client scenario. Link: https://github.com/apache/skywalking/blob/master/test/plugin/scenarios/asynchttpclient-scenario/config/expectedData.yaml

ok I will do it tomorrow，and run 'asynchttpclient-scenario' in local env

**Review by ascrutae — APPROVED** [review]
LGTM

**Pull request merged**
