### PR TITLE
doc: added contributor over time

### PR DESCRIPTION
**Pull request by juzhiyuan**
Hi, I have not seen any section that matches this PR, then I remove all of them 🤔 

This PR aims to add the Contributor Over Time for Apache SkyWalking since 2015-11-09, I hope SkyWalking will like it.

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think you should add this to the website, if you like the trend graph from time to time.
https://skywalking.apache.org/team/

**Comment by wu-sheng** [comment]
The team page will be updated every day and once new PR merged in the website repo, like we did for the document.

**Comment by juzhiyuan** [comment]
ok, let me do it.

**Comment by wu-sheng** [comment]
When you do this, please make sure it is either attched on every project, or aggregating all projects data into one graph, considering SkyWalking has many subprojects.
Also, we need this to rebuild every time.

**Comment by juzhiyuan** [comment]
> When you do this, please make sure it is either attched on every project, or aggregating all projects data into one graph, considering SkyWalking has many subprojects.
> Also, we need this to rebuild every time.

Good catch! Let me generate a graph contains all subprojects :)

And we will support one link target to a dynamic graph, so we don't have to update that graph every time.

**Comment by juzhiyuan** [comment]
image

Yes, when I try to add all projects, I find that it has too many projects 😂 Could we attach this graph for every project? (on the README file instead of website).

**Comment by juzhiyuan** [comment]
It's not clear for repos that don't have too many contributors when combining all of the projects.

**Comment by wu-sheng** [comment]
Do you mean api7 host service? Be careful anout it.
ASF TLP relies on commercial vendor website, which could be a concern by PMC, even ASF at policy level.

**Comment by juzhiyuan** [comment]
Yes, this graph is generated by API7, and for now, I will generate every graph by that service, without any commercial information actually 🤔 

> And we will support one link target to a dynamic graph, so we don't have to update that graph every time.

This feature is still in progress :)

**Comment by wu-sheng** [comment]
> Yes, this graph is generated by API7, but for now, I will generate every graph by that service, without any commercial information actually 🤔
> 
> > And we will support one link target to a dynamic graph, so we don't have to update that graph every time.
> 
> This feature is still in progress :)

Yes, but you will add it into the website pipeline or accessing api7 service address every time when user accesses this team page.
Either way, you need the PMC approval(vote) to accept this.

**Comment by wu-sheng** [comment]
Also, I am guessing you mean the 2nd way, then your service speed to global people matters.

**Comment by wu-sheng** [comment]
> image
> 
> Yes, when I try to add all projects, I find that it has too many projects 😂 Could we attach this graph for every project? (on the README file instead of website).

We removed this kind of graph including star trend from the readme. SkyWalking is focusing on GitHub for development, website for users. @Jtrust is leading all things, we have no plan to add them back.

**Comment by wu-sheng** [comment]
> It's not clear for repos that don't have too many contributors when combining all of the projects.

I prefer to add this to the whole ecosystem, rather than a repo. For SkyWalking, contributions to any repo are same, and we appreciated them in same.

**Comment by juzhiyuan** [comment]
😂 ok, got it. But making a chart that contains multiple repos' trends is a little hard in this style. Let us reconsider.

**Comment by wu-sheng** [comment]
> 😂 ok, got it. But making a chart that contains multiple repos' trends is a little hard in this style. Let us reconsider.

I just recommend to use one line in the graph. I am feeling you are thinking one line per repo

**Pull request closed without merging**
