### PR TITLE
fix: correct system variable spelling

### PR DESCRIPTION
**Pull request by BFergerson**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
FYI @wankai123

**Comment by wu-sheng** [comment]
@BFergerson Curious, are you doing something related to OpenAPI?

**Comment by BFergerson** [comment]
No, I was reviewing the config and noticed the spelling error. Also noticed `SW_SUPERDATASET_STORAGE_DAY_STEP` doesn't follow the format of `SW_STORAGE_ES_SUPER_DATASET_`.

Want me to fix that too?

**Comment by wu-sheng** [comment]
Yes, it should be fixed.

**Pull request merged**
