### PR TITLE
Elasticsearch storage support merge all records(without super datasets) indices into one physical index

### PR DESCRIPTION
**Pull request by mrproliu**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please sync and resolve conflicts.

**Comment by wu-sheng** [comment]
When you are ready, please list the all indices now. I am thinking we should list them in some docs, as from now, our index list is nearly unchanged.

**Comment by mrproliu** [comment]
After disabling logic sharding in ES, we have these indices:
* sw_ui_template
* sw_metrics-all-`${day-format}`
* sw_log-`${day-format}`
* sw_segment-`${day-format}`
* sw_browser_error_log-`${day-format}`
* sw_zipkin_span-`${day-format}`
* sw_records-all-`${day-format}`

**Comment by wu-sheng** [comment]
Please update `backend-storage.md` add some description below `Since 9.2.0` paragraph

**Review by wu-sheng — APPROVED** [review]
I am still discussing with @wankai123 to find a way to make logic shard way could keep as same as previous. You may need to follow that later. Right now, this is good

**Pull request merged**
