### PR TITLE
Remove InfluxDB 1.x and Apache IoTDB 0.X as storage options

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/changelog/docs/en/changes/changes.md).

[**IMPORTANT**] Remove InfluxDB 1.x and Apache IoTDB 0.X as storage options, check details at [here](https://github.com/apache/skywalking/discussions/9059). Remove converter-moshi 2.5.0, influx-java 2.15,  iotdb java 0.12.5, thrift 0.14.1, moshi 1.5.0, msgpack 0.8.16 dependencies. Remove InfluxDB and IoTDB relative codes  and E2E tests.

### CODE REVIEW

**Review by wankai123 — APPROVED** [review]

**Comment by wu-sheng** [comment]
Pending on 
- https://github.com/apache/skywalking/discussions/9059
- https://lists.apache.org/thread/2x88hcq5r57vrj7vzjvqzbhsfdjjg6dh

**Comment by wu-sheng** [comment]
@mrproliu If this gets merged, you could get rid of the next adjustment for ebpf profiling adjustment.

**Comment by kezhenxu94** [comment]
I think the labels should be `backend`, and `plugin`?

**Comment by wu-sheng** [comment]
> I think the labels should be `backend`, and `plugin`?

Changed, just wanted to highlight this.

**Review by mrproliu — APPROVED** [review]

**Pull request merged**
