### PR TITLE
code cleanup: remove unnecessary and optimize the function's parameters.

### PR DESCRIPTION
**Pull request by JaredTan95**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

### CODE REVIEW

**Comment by JaredTan95** [comment]
Weird~, I  will test in my local env.

**Comment by kezhenxu94** [comment]
You remove some `throws` exception, I guess there're unused `import`s

**Pull request merged**
