### PR TITLE
refactor: more consistent with other listener managers

### PR DESCRIPTION
**Pull request by BFergerson**
#### Renamed `EventAnalyzerListenerFactoryManager` to `IEventAnalyzerListenerManager`

Consistent with:
- `ISegmentParserListenerManager`
- `ErrorLogParserListenerManager`
- `PerfDataParserListenerManager`

#### Renamed `ILogAnalysisListenerFactoryManager` to `ILogAnalysisListenerManager`

Consistent with: 
- `ISegmentParserListenerManager`
- `ErrorLogParserListenerManager`
- `PerfDataParserListenerManager`

#### Removed `extends Service` from `IEventAnalyzerListenerManager` & `ILogAnalysisListenerManager`

Consistent with `ISegmentParserListenerManager` plus they were not being registered as service implementations.

#### Renamed `EventAnalyzerListenerFactoryManager.factories()` to `IEventAnalyzerListenerManager.getEventAnalyzerListenerFactories()`

Consistent with:
- `ISegmentParserListenerManager.getSpanListenerFactories()`
- `ILogAnalysisListenerManager.getLogAnalysisListenerFactories()`

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
I can't rerun the fail task, GHA seems not responding.

**Comment by BFergerson** [comment]
Assuming moving forward I'm allowed to merge once tests pass and reviewers have approved changes. Let me know if not.

**Comment by wu-sheng** [comment]
It is OK to merge, but you should remove all commit details, as they are not very useful.
We are using squash merge.
You could check the latest commit log, it includes two useless sentences.

**Comment by BFergerson** [comment]
Ah, I see. Will do going forward.

**Pull request merged**
