### PR TITLE
kubernetes.client.opeanapi.ApiException

### PR DESCRIPTION
**Pull request by buzuotaxuan**
Fix  https://github.com/apache/skywalking/issues/6408

### CODE REVIEW

**Comment by wu-sheng** [comment]
@buzuotaxuan We need you to update the `changes.md` in the root.

**Review by wu-sheng — APPROVED** [review]

**Comment by buzuotaxuan** [comment]
ok

**Review by wu-sheng — DISMISSED** [review]
LGTM, wait for other reviews.

**Review by kezhenxu94 — DISMISSED** [review]

**Comment by EvanLjp** [comment]
Maybe the bug is caused by updating the Kubernetes version, I don't find the bug with the low Kubernetes client version.

**Review by EvanLjp — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
