### PR TITLE
[test/plugin] immigrate test shardingsphere 4.x RC1 RC2 scenario

### PR DESCRIPTION
**Pull request by tuohai666**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
#3583
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wayilau** [comment]
All tests passed! 
LGTM

**Comment by wu-sheng** [comment]
Strange, this PR always cause CI test failure on MacOs, even it should not relate to the changes.

**Comment by wayilau** [comment]
> Strange, this PR always cause CI test failure on MacOs, even it should not relate to the changes.


> Strange, this PR always cause CI test failure on MacOs, even it should not relate to the changes.

I remember It's passed last time when i merge master into this.

**Comment by wu-sheng** [comment]
> I remember It's passed last time when i merge master into this.

Yes, it passed multiple times, and suddenly always fail. That is why I feel strange.

**Pull request merged**
