### PR TITLE
ProtectiveShieldMatcher add feature for exclude some class with -Dskywalking_enhance_ignore_class_pattern, so we ignore some package

### PR DESCRIPTION
**Pull request by qxo**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

ProtectiveShieldMatcher add feature for exclude some class with -Dskywalking_enhance_ignore_class_pattern, so we ignore some package

ie: `-Dskywalking_enhance_ignore_class_pattern=^com\.jprofiler`
then unnecessary warn log will not show each startup
```
WARN 2019-08-24 10:19:56:010 Attach Listener ProtectiveShieldMatcher :  Byte-buddy occurs exception when match type.
java.lang.IllegalStateException: Cannot resolve type description for com.jprofiler.agent.k
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:144)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1392)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:8009)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getSuperClass(TypeDescription.java:3604)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:299)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:266)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:37)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:15)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:107)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:147)
```

### CODE REVIEW

**Comment by qxo** [comment]
where is "SkyWalkingAgent#L91-L99" , A link will be helpful:)

I don't known if was the way for ignore classes “out of box”
I thought it should have:)

看到问题点，就顺带解决了，觉得该回馈开源社区就提上来了，也许存在更好的方式是我不知的

Never mind, help yourself:)

**Comment by wu-sheng** [comment]
`SkyWalkingAgent` is the class name, Line 91 - 99. Ignore is there static, you could provide this feature there.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/0ae2228a86713d89ce9f6bf849fb9a96303d0cfa/apm-sniffer/apm-agent/src/main/java/org/apache/skywalking/apm/agent/SkyWalkingAgent.java#L91-L99

**Comment by qxo** [comment]
On my test add ignore like "SkyWalkingAgent#L91-L99"  will not work the issue:
`	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:144)`

**Comment by wu-sheng** [comment]
Could you provide the codes you changed? This should work.

**Comment by qxo** [comment]
{code}

        final ByteBuddy byteBuddy = new ByteBuddy()
            .with(TypeValidation.of(Config.Agent.IS_OPEN_DEBUGGING_CLASS));

        Junction<TypeDescription> ignores = nameStartsWith("net.bytebuddy.");

//change start 
        String ignoreList = System.getProperty("skywalking_ignore_class_prefixlist");
        if (ignoreList != null && (ignoreList = ignoreList.trim()).length() > 0) {
            logger.info("skywalking_ignore_class_prefixlist:{}",ignoreList);
            for (String p : ignoreList.split("[ ,;:]+")) {
                ignores = ignores.or(nameStartsWith(p));
            }
        }
//change end

        ignores = ignores.or(nameStartsWith("org.slf4j."))
        .or(nameStartsWith("org.apache.logging."))
        .or(nameStartsWith("org.groovy."))
        .or(nameContains("javassist"))
        .or(nameContains(".asm."))
        .or(nameStartsWith("sun.reflect"))
        .or(allSkyWalkingAgentExcludeToolkit())
        .or(ElementMatchers.<TypeDescription>isSynthetic());
        new AgentBuilder.Default(byteBuddy)
            .ignore(
                ignores)
            .type(pluginFinder.buildMatch())
            .transform(new Transformer(pluginFinder))
            .with(new Listener())
            .installOn(instrumentation);
{code}

then -Dskywalking_ignore_class_prefixlist=com.jprofiler

**Pull request closed without merging**
