### PR TITLE
optimize server-alarm-plugin

### PR DESCRIPTION
**Pull request by muyun12**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided

- [ ] Improve performance

#### Configuration adjustment
- old configuration
```
webhooks:
    - http://xxx
    - http://xxxx
```
- new configuration
```
webhooks:
    default:
        - http://xxx
    some:
       - http://xxxx
```

#### Custom  the Alert Extension

Implement `RemoteEndpoint` interface

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@muyun12 did you check #3525 ? Is this PR similar to that one? See comments there please

**Comment by muyun12** [comment]
@kezhenxu94 this PR is similar to [#3525](https://github.com/apache/skywalking/pull/3525).  The reality I encountered was that I needed to integrate third-party webhooks to trigger the corresponding workflow. Based on this, the alarm plugin is enhanced to add extensions conveniently without changing the sw source code for each extension.

**Comment by wu-sheng** [comment]
Webhook in http provides you the capability to integrate without changing codes.

**Comment by kezhenxu94** [comment]
> The reality I encountered was that I needed to integrate third-party webhooks to trigger the corresponding workflow.

For now, you have to set up your own http server and receive the alarm message from SkyWalking, and dispatch to third-party system in your http server.

And even if we're going to refactor the alarm plugin to SPI pattern (like #3525), we won't want to modify the existed configuration format for compatibility.

**Pull request closed without merging**
