### PR TITLE
fix: Fix macos test script command not found error. #6846

### LINKED ISSUE #6846: Issue running Plugin test on macos
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS, and JRE?
Skywalking 8.6 code on master branch, macos (Big Sur), JDK 1.8

- Which company or project?
Plugin test framework fails with run.sh failing to run sed command on macos

- What happened?
Run Plugin test on macos as per [link](https://github.com/apache/skywalking/blob/master/docs/en/guides/Plugin-test.md#local-test-and-pull-request-to-the-upstream) on macos. it fails with error such as "invalid command .". After debugging for some time found that sed command used on between 145-156 in run.sh is not compatible on macos.

Either the document needs to be updates to support linux only and remove macos or fix the run.sh script.

### PR DESCRIPTION
**Pull request by wallezhang**
### Fix <#6846>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.

Fix the `run.sh` test script command not found error on MacOS. Because the syntax of `sed` command is different between macOS and Linux. So I use different syntax according to the current os.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #6846.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please update changelog in the project section.

**Comment by wallezhang** [comment]
> Please update changelog in the project section.

Done

**Review by dmsolr — APPROVED** [review]
LGTM

**Comment by wu-sheng** [comment]
@dmsolr Have you run this on a real MacOS?

**Comment by dmsolr** [comment]
> @dmsolr Have you run this on a real MacOS?

Yes. I tested it passed on my laptop.

**Pull request merged**
