### PR TITLE
Replace add with addAll, reduce the invoke time a little.

### PR DESCRIPTION
**Pull request by Arugal**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

### CODE REVIEW

**Comment by wu-sheng** [comment]
For a LinkedList today, what is the difference? Could you show me the benchmark?

**Comment by Arugal** [comment]
Jdk1.8 addAll internally only handles size and modCount once

**Comment by wu-sheng** [comment]
@Arugal I got your point, I hope next time, you could provide this to approve your point.

# Benchmark
```
@BenchmarkMode(Mode.Throughput) 
@OutputTimeUnit(TimeUnit.MILLISECONDS) 
@State(Scope.Thread) 
@Fork(2) 
@Warmup(iterations = 4) 
@Measurement(iterations = 5) 
public class ConsumerThreadTest {
    private LinkedList<Object> container = new LinkedList<Object>();
    private static final Object o = new Object();
    private static final List list = new ArrayList(100);

    static {
        for (int i = 0; i < 100; i++) {
            list.add(0);
        }
    }

    @Benchmark
    public void testAdd() {
        for (int i = 0; i < 100; i++) {
            container.add(o);
        }
        container.clear();
    }

    @Benchmark
    public void testAddAll(){
        container.addAll(list);
        container.clear();
    }

    @BenchmarkMode(Mode.AverageTime)
    @OutputTimeUnit(TimeUnit.MICROSECONDS)
    public static void main(String[] args) throws RunnerException {
        Options options = new OptionsBuilder().include(ConsumerThreadTest.class.getSimpleName()).build();
        new Runner(options).run();
    }
}
```

# Env
```
# JMH version: 1.19
# VM version: JDK 1.8.0_91, VM 25.91-b14
# VM invoker: /Users/wusheng/Documents/applications/jdk1.8.0_91.jdk/Contents/Home/jre/bin/java
# VM options: -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=52989:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8
```

# Results 
```
Benchmark                       Mode  Cnt     Score    Error   Units
ConsumerThreadTest.testAdd     thrpt   10  1531.322 ± 42.526  ops/ms
ConsumerThreadTest.testAddAll  thrpt   10  1736.827 ± 84.429  ops/ms
```

# Conclusion
In this single operation, this change could improve 10% performance

**Comment by wu-sheng** [comment]
@Arugal This is a very good way when you do performance improvement codes. You even could include the benchmark in PR.

**Comment by Arugal** [comment]
@wu-sheng I didn't know before 😊

**Comment by wu-sheng** [comment]
@Arugal I guessed so. That is why I wrote one and tested by myself. Google the Java jmh benchmark. You could do this easily.

**Comment by Arugal** [comment]
@wu-sheng yes, I studied last night.

**Pull request merged**
