### PR TITLE
Fix isSelf address.

### PR DESCRIPTION
**Pull request by wayilau**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
https://github.com/apache/skywalking/issues/3018
___
### Bug fix
- Bug description.

### CODE REVIEW

**Comment by wu-sheng** [comment]
We are waiting for Apache Jenkins restore.

**Comment by Arugal** [comment]
Hi All

Should a base class be abstracted to cover the necessary test.

Taking ```ClusterRegister#registerRemote``` as an example, various plugins have different implementations.

ps: I don't know if I described it clearly

case 1:  ```NacosCoordinatorTest``` 
```
    @Test
    public void queryRemoteNodes() throws NacosException {
        registerSelfRemote();
        List<Instance> instances = mockInstance();
        when(namingService.selectInstances(anyString(), anyBoolean())).thenReturn(instances);
        List<RemoteInstance> remoteInstances = coordinator.queryRemoteNodes();
        assertEquals(2, remoteInstances.size());

        RemoteInstance selfInstance = remoteInstances.get(0);
        validate(selfRemoteAddress, selfInstance);

        RemoteInstance notSelfInstance = remoteInstances.get(1);
        validate(remoteAddress, notSelfInstance);
    }
```

case 2: ```ZookeeperCoordinatorTest```
```
    @Test
    public void queryRemoteNodes() {
    }
```

case 3: ```EtcdCoordinatorTest```
```
    @Test
    public void queryRemoteNodes() {
        registerSelfRemote();

        EtcdKeysResponse.EtcdNode node = PowerMockito.mock(EtcdKeysResponse.EtcdNode.class);
        EtcdKeysResponse.EtcdNode node1 = PowerMockito.mock(EtcdKeysResponse.EtcdNode.class);

        when(response.getNode()).thenReturn(node);
        list = new ArrayList<>();
        List list1 = Mockito.spy(list);
        list1.add(node1);
        when(node.getNodes()).thenReturn(list1);
        when(node1.getValue()).thenReturn("{\"serviceId\":\"my-service\",\"host\":\"10.0.0.2\",\"port\":1001}");
        List<RemoteInstance> remoteInstances = coordinator.queryRemoteNodes();
        assertEquals(1, remoteInstances.size());

        RemoteInstance selfInstance = remoteInstances.get(0);
        velidate(selfRemoteAddress, selfInstance);
    }

```

**Comment by wu-sheng** [comment]
@Arugal we are welcome test enhancement. You could send a pull request to do that

**Pull request merged**
