### PR TITLE
Remove log4j version properties in webapp

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

> Turns out to be the case, the property <log4j.version>2.6.2</log4j.version> is not used, please remove it instead

Quote from https://github.com/apache/skywalking/pull/8285#issuecomment-991826955, webapp doesn't use log4j2.

### CODE REVIEW

**Review by fgksgf — APPROVED** [review]

**Review by kezhenxu94 — APPROVED** [review]
I thought we use logback in webapp

**Review by mrproliu — DISMISSED** [review]

**Review by kezhenxu94 — CHANGES_REQUESTED** [review]
> I thought we use logback in webapp

Turns out to be the case, the property is not used, please remove it instead

**Comment by wu-sheng** [comment]
OK, let me remove this.

**Review by kezhenxu94 — APPROVED** [review]
LGTM

**Pull request merged**
