### PR TITLE
[test/plugin] support jvm-container

### PR DESCRIPTION
**Pull request by dmsolr**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
#3528 
___
### New feature or improvement
- Describe the details and related test reports.

It make plugin test-cases immigrated easy!

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think we should immigrate an easy test case in this PR to verify. What do you think?

**Comment by dmsolr** [comment]
Yes. I will push a jetty-scenario.

**Comment by wu-sheng** [comment]
Cool. Thanks.

**Comment by wu-sheng** [comment]
Related to #3583

**Comment by wu-sheng** [comment]
Congrats. It passed in 35mins, and cost per VM 30% CPU. Make sense to me. And we could add more to group1(Group2 is already 30min, longest path). Due to its timeout last time, please make timeout to 60s for each case.

Also, let's add multiple node parallel for compose case, to make the test framework structure completed.

**Pull request merged**
