### PR TITLE
MOD: Kafka-plugin Compatible with KafkaTemplate

### PR DESCRIPTION
**Pull request by stalary**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [x] Improve performance

- Related issues
https://github.com/apache/skywalking/issues/3478
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.
Compatible with KafkaTemplate

### CODE REVIEW

**Comment by stalary** [comment]
> LGTM. @zhaoyuguang Could you run Kafka plugin case again? In case this would break the old things.
> 
> @stalary Do we need another case for this?

I tested kafka-clients and kafkaTemplate locally and found no problem. We can add some cases of kafkaTemplate

**Comment by wu-sheng** [comment]
@haodut Could you test this PR codes? It should fix your issue.

**Comment by haodut** [comment]
> 
> 
> @haodut Could you test this PR codes? It should fix your issue.

Yes, it fix my issue.

**Comment by wu-sheng** [comment]
> Yes, it fix my issue.

@haodut Please approve this PR :)

**Comment by wu-sheng** [comment]
I am going to merge this

**Pull request merged**
