### PR TITLE
Support Java 21 as runtime and ship jre-21 image.

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
@kezhenxu94 Please take a look whether the JDK21 runtime is applied correctly on e2e.

If so, what do you suggest for these JDK21 cases? It passed, which proved OAP is good to run on JDK21. It seems we are good for JDK 11/17/21, and it should not be necessary to test every time.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Please take a look whether the JDK21 runtime is applied correctly on e2e.
> 
> If so, what do you suggest for these JDK21 cases? It passed, which proved OAP is good to run on JDK21. It seems we are good for JDK 11/17/21, and it should not be necessary to test every time.

The new cases added in this PR are part of the whole cases we did for Java 11, to be 100% sure that Java 21 works, we should run the whole cases at least 1 time

**Comment by wu-sheng** [comment]
Make sense. Let's say I am going to change current JDK11 to JDK21, after tests passed, I revert all of them back?

**Comment by kezhenxu94** [comment]
> Make sense. Let's say I am going to change current JDK11 to JDK21, after tests passed, I revert all of them back?

Sounds good

**Comment by wu-sheng** [comment]
@kezhenxu94 Could you verify the changes I made?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Could you verify the changes I made?

The changes looks good to me and the cases seem to pass for Java 21.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
