### PR TITLE
 Support SOAP request cxf(3.x) webservice

### PR DESCRIPTION
**Pull request by wz8188**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

### CODE REVIEW

**Comment by wu-sheng** [comment]
You need to submit test pull request, do you know where and how?

**Comment by wu-sheng** [comment]
Be advised, RESTEasy plugin merged, conflict needs to be solved.

**Comment by wz8188** [comment]
> Be advised, RESTEasy plugin merged, conflict needs to be solved.

**Comment by wu-sheng** [comment]
Why PR closed?

**Comment by wz8188** [comment]
> Why PR closed?

solving conflict

**Comment by wu-sheng** [comment]
I have tagged this PR as `TBD`(To be decided), so until you submit the test, and report to us that, the test has passed in your local, we wouldn't review. So you don't need to close the PR to resolve the conflict.

**Comment by wu-sheng** [comment]
We are still waiting for integration test case PR, and with no conflict. With time passing, the conflicts will keep coming, because there are 6-7 plugin PRs are going.

**Comment by wz8188** [comment]
I'm so sorry that my own pc has been stolen. I can not work now.I will coding the test case next week.


 
---Original---

**Comment by wu-sheng** [comment]
@wz8188 Sorry to hear that. Be careful. Just don't want to you feel frustrating, as the conflicts happen many times.

**Comment by asfgit** [comment]
FAILURE

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/skywalking-e2e/14/

**Comment by wu-sheng** [comment]
I am closing this PR for now, as no update in 30 days. Please submit a new one when you are ready. @wz8188

**Pull request closed without merging**
