### PR TITLE
Polish academy docs

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Review by wankai123 — APPROVED** [review]

**Review by Superskyyy — APPROVED** [review]

**Comment by wu-sheng** [comment]
```
  5 links checked.
  [✖] https://cwiki.apache.org/confluence/display/SKYWALKING/Home → Status: 0
  ERROR: 1 dead links found!
```

This time, deadlink seems irrelevant

**Review by wankai123 — APPROVED** [review]

**Comment by Superskyyy** [comment]
> ```
>   5 links checked.
>   [✖] https://cwiki.apache.org/confluence/display/SKYWALKING/Home → Status: 0
>   ERROR: 1 dead links found!
> ```
> 
> This time, deadlink seems irrelevant

It does seem dead tho. I cannot open it.

**Review by kezhenxu94 — APPROVED** [review]

**Comment by wu-sheng** [comment]
Yes, it seems dead. It is an ASF INFRA, I would ask infra team to take a look.

**Comment by wu-sheng** [comment]
Oh, I have seen the `red alert` from infra list.

**Comment by kezhenxu94** [comment]
while I can open it 😄

**Comment by wankai123** [comment]
> https://cwiki.apache.org/confluence/display/SKYWALKING/Home

I can open it too
image

**Comment by wu-sheng** [comment]
Yes, it is back :)

image

**Pull request merged**
