### PR TITLE
try to enable cross build for arm64 docker image

### PR DESCRIPTION
**Pull request by mis98zb**
### <Feature description>
- [ ] If this is non-trivial feature, paste the links/URLs to the design doc.
- [ ] Update the documentation to include this new feature.
- [ ] Tests(including UT, IT, E2E) are added to verify the new feature.
- [ ] If it's UI related, attach the screenshots below.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Any update about this PR?

**Comment by mis98zb** [comment]
some E2E test failed with building test docker image (not the oap/ui image).
need more investigation...

**Comment by wu-sheng** [comment]
> btw, the oap/ui images pushed to docker hub can work on my local docker environment...

Of course it can. What is the issue about this?

**Comment by mis98zb** [comment]
> > btw, the oap/ui images pushed to docker hub can work on my local docker environment...
> 
> Of course it can. What is the issue about this?

hehe, I mean, I've tested the pushed oap/ui images local and they started up without error.

however, E2E failed with biulding test docker image.
not sure if it is due to the base image change...

**Comment by wu-sheng** [comment]
That is the point of e2e. Usually there are some pre-setup in your local env, which makes every steps working well. But running in the e2e env could expose these missing steps.

**Comment by mis98zb** [comment]
E2E.java succeeded meanwhile E2E.js failed.
It's hard to find out why....
maybe need some time to study E2E code...

**Comment by kezhenxu94** [comment]
Hi @mis98zb , I've opened https://github.com/apache/skywalking/pull/8141 to address the review comments and polish the `Makefile`, can you please take a look?

**Comment by kezhenxu94** [comment]
Closing in favor of https://github.com/apache/skywalking/pull/8141

**Pull request closed without merging**
