### PR TITLE
inject span tags from correlation

### PR DESCRIPTION
**Pull request by EvanLjp**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] New feature provided

___
### New feature or improvement
- supports full link stress testing to distinct the traffic source.
- supports tags query on UI

### CODE REVIEW

**Comment by EvanLjp** [comment]
@wu-sheng @kezhenxu94 Do you think the MD5 algorithm needs to be modified?

**Review by wu-sheng — CHANGES_REQUESTED** [review]
This will make duplicated injection for every segment. I prefer we don't do this. You are making this similar to OpenTracing Baggage, which we didn't plan to support when we disigned the correlation context.

Also, every new feature should be discussed before changing im case to avoid argument after you have finished the prototype codes.

**Comment by wu-sheng** [comment]
MD5 thing is not the thing we should discuss, please read above comments. That is the key.

**Comment by EvanLjp** [comment]
> This will make duplicated injection for every segment. I prefer we don't do this. You are making this similar to OpenTracing Baggage, which we didn't plan to support when we disigned the correlation context.
> 
> Also, every new feature should be discussed before changing im case to avoid argument after you have finished the prototype codes.

The above code is only 

> This will make duplicated injection for every segment. I prefer we don't do this. You are making this similar to OpenTracing Baggage, which we didn't plan to support when we disigned the correlation context.
> 
> Also, every new feature should be discussed before changing im case to avoid argument after you have finished the prototype codes.

Do you have any other ideas? This PR comes from support for online flow pressure measurement.

**Comment by wu-sheng** [comment]
The key issue is, injecting this has high-security and memory/network/backend overload concerns. We should carefully reconsider how to do this. Personally, I still prefer an API or a pure optional plugin. The key point is, asking users to activate this manually, then we could set up documentation with it to tell users, note the security issue.

**Comment by EvanLjp** [comment]
> The key issue is, injecting this has high-security and memory/network/backend overload concerns. We should carefully reconsider how to do this. Personally, I still prefer an API or a pure optional plugin. The key point is, asking users to activate this manually, then we could set up documentation with it to tell users, note the security issue.

@wu-sheng  there are some ideas about supporting it in an optional way.
step 1:
refactor some  codes of the span behavior:
1. define a new span callback interface for service loader
2. define a span filter chain to process span behavior, such as extract for the carrier or inject to carrier
3. the order of the span filter chain triggered is ordered by the number of callback interfaces. 

step 2:
supports correlation behavior by filter chain:
1. the default correlation behavior is only propagate
2. the optional behavior will add an injection behavior, the code way is to add a filter rather than override to ensure the stability of the main process.

**Comment by EvanLjp** [comment]
@wu-sheng thx for review this version. I have extracted the dangerous behavior to the optional plugin. If this behavior is tolerated, I will modify the doc and add the unit test later.

**Comment by wu-sheng** [comment]
> Do you think the MD5 algorithm needs to be modified?

Back to this, MD5 could be replaced by BASE64, basically in the open-source.

**Review by wu-sheng — COMMENTED** [review]
I am a little confused about this plugin. Could you consider simply providing `ContextManagerExtendService`'s extension? It could create an extension of `TracingContext`.

Then, could add new logic into `TracingContext#extract` w/o changing any core level code.

Make sense?

**Comment by EvanLjp** [comment]
> I am a little confused about this plugin. Could you consider simply providing `ContextManagerExtendService`'s extension? It could create an extension of `TracingContext`.
> 
> Then, could add new logic into `TracingContext#extract` w/o changing any core level code.
> 
> Make sense?

no problem

**Pull request closed without merging**
