### PR TITLE
Remove TLS support from firehose receiver

### PR DESCRIPTION
**Pull request by wu-sheng**
Notice, no HTTPS/TLS setup support. By following AWS Firehose request, it uses [proxy request](https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers) (`https://...` instead of `/aws/firehose/metrics`), there must be a proxy(Nginx, Envoy, etc.).

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

@pg-yang I think we need to update Firehose and S3 document to add a proxy requirement in the metrics forward path

### CODE REVIEW

**Comment by wu-sheng** [comment]
Upstream discussion on Armeria to locate this.

https://line-armeria.slack.com/archives/C1NGPBUH2/p1676811880163349

**Comment by wu-sheng** [comment]
Upstream discussion on Armeria to locate this.

https://line-armeria.slack.com/archives/C1NGPBUH2/p1676811880163349

**Comment by wu-sheng** [comment]
Debug logs from @pg-yang 
image

image

**Comment by pg-yang** [comment]
We should remove the configurations from  https://github.com/apache/skywalking/blob/cabe40eb47fc83d681f1f40359798915f8ff7428/oap-server/server-starter/src/main/resources/application.yml#L558-L560 as well

**Review by kezhenxu94 — COMMENTED** [review]
Configs in yaml file should be removed too

**Comment by pg-yang** [comment]
and configuration-vocabulary.md

**Comment by kezhenxu94** [comment]
And doc https://github.com/apache/skywalking/blob/cabe40eb47fc83d681f1f40359798915f8ff7428/docs/en/setup/backend/aws-firehose-receiver.md#notice

**Comment by wu-sheng** [comment]
Debug logs from @pg-yang 
image

image


> And doc https://github.com/apache/skywalking/blob/cabe40eb47fc83d681f1f40359798915f8ff7428/docs/en/setup/backend/aws-firehose-receiver.md#notice

I will update other docs, and leave AWS doc to @pg-yang. He should have a more accurate version than I could do.

**Review by pg-yang — APPROVED** [review]
LGTM, wait for GHA

**Pull request merged**
