### PR TITLE
Optimize TraceQuery

### PR DESCRIPTION
**Pull request by dominicqi**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Improve performance

- Related issues
___
### New feature or improvement
- Describe the details and related test reports.
1. Use FilterContext replace QueryContext.(reduce scoring cost and use filter cache)
2. reduce query index scope
   - range query use `multiple indices` `ignore_unavailable` params ignore missing or closed index
   - traceId query get the trace start time (got in #4353). add one more(next) index to query.

### CODE REVIEW

**Comment by dominicqi** [comment]
> I am sorry to say, today, we don't require timestamp in thr trace id anymore.
> Many agents don't implement in this way, including our native lua agent.

So sad , many ES cluster was deploy as a `hot-warm architecture` , put the old data  in warm datanode. This will cause search very slow use the alias.

**Comment by dominicqi** [comment]
@wu-sheng  Another way, can with save segment routing by `trace_id`. Then the `TraceIdQuery` can use the traceId routing to the right shard . I think i will improve the query very much.
Here is the [routing doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html)

**Comment by dominicqi** [comment]
@wu-sheng  Another way, can with save segment routing by `trace_id`. Then the `TraceIdQuery` can use the traceId routing to the right shard . I think i will improve the query very much.
Here is the [routing doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html)

**Comment by wu-sheng** [comment]
I know direct index query is faster. several seconds vs 500ms.

**Comment by dominicqi** [comment]
> I know direct index query is faster. several seconds vs 500ms.

Use routing  then we could query with alias  , it is fast too. No need to found the direct index. Can direct to the right shard.

**Comment by dominicqi** [comment]
image

image

routing vs no routing

**Comment by wu-sheng** [comment]
Custom routing and sharding rule seems reasonable. But we need an explicit sharding key annotation, or add attribute into Column annotation. Let's think more clear about this. Make this possible in 8.1 release. OK?

**Comment by dominicqi** [comment]
> Column

Ok

**Comment by wu-sheng** [comment]
@dominicqi As the 8.0.0 is tagged and on voting, we could continue on this, if you have time.

**Comment by wu-sheng** [comment]
#5132 is closing to merge, it provides similar features.

**Pull request closed without merging**
