### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by wayilau**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance
- [x] document

### CODE REVIEW

**Comment by wayilau** [comment]
A question, i just modify doc, I think it needs not run all the ci cases.   May be we can use github api to customize our favoriate action. We may have our test-infra. @wu-sheng

**Comment by wu-sheng** [comment]
Please select label and milestone next time, as you are a committee already.

**Comment by wayilau** [comment]
> Please select label and milestone next time, as you are a committee already.

OK, I will.

**Comment by wayilau** [comment]
> > Please select label and milestone next time, as you are a committee already.
> 
> OK, I will.

Do we have a plan to automation this?  just like k8s's  when i opened an issue or a pr, the necessary lable auto labled.

**Comment by wu-sheng** [comment]
We can't, as ASF don't give the permission.

**Comment by wayilau** [comment]
> We can't, as ASF don't give the permission.

i got it.

**Pull request merged**
