### PR TITLE
Add hierarchy for Pulsar

### PR DESCRIPTION
**Pull request by CodePrometheus**
Add hierarchy for Pulsar

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/11941.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/docs/en/changes/changes.md).

### CODE REVIEW

**Review by wankai123 — COMMENTED** [review]
I think we don't have a showcase about PULSAR, if you have tested it, could you add some relevant screenshots？

**Comment by wu-sheng** [comment]
@CodePrometheus Please follow the above review and resolve the conflicting.

**Comment by CodePrometheus** [comment]
Sorry, I've been busy with work lately. The showcase is in progress, and local test is as shown below, but the `service_hierarchy_relation` does not seem to be related to Virtual-MQ and Pulsar-cluster now, I'm still trying to figure it out, If teachers have any suggestions please let me know, thanks very much.
image
image
image

**Comment by wu-sheng** [comment]
From what I saw, your V-MQ is using IP:port which is provided by the agent plugin, meanwhile, server monitoring is using service name in k8s or something similar. You build the hierarchy rules, you need to make sure whey are aligned and the rules follow the setup.

**Comment by peachisai** [comment]
Due to the difficulty of building the IP:port form relationship with the Pulsar-cluster ,I suggest adjusting local hosts to accommodate the Pulsar-cluster name If Pulsar java plugin report the address name as I suppose

**Comment by CodePrometheus** [comment]
> Due to the difficulty of building the IP:port format relationship with the Pulsar-cluster ,I suggest adjusting local hosts to accommodate the Pulsar-cluster name If Pulsar java plugin report the address name as I suppose

It works, @peachisai You’re a genius! Very thanks~
image


And I have an idea, is it possible to declare an empty custom key in auto-matching-rules, such as `custom: ""`

**Comment by wu-sheng** [comment]
Please resolve the conflicts.

**Pull request merged**
