### PR TITLE
Upgrade guava version to support higher JDK version

### PR DESCRIPTION
**Pull request by kezhenxu94**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

#3540 and #3477 

https://github.com/apache/skywalking/blob/5b039e9747fac98444b4ec423a5d57524202f286/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/annotation/AnnotationScan.java#L54-L56

the `classpath.getTopLevelClassesRecursive("org.apache.skywalking")` returns empty `set` under JDK 8+, and it turns out to be an issue of Guava, see https://github.com/google/guava/issues/3249#issuecomment-416234877 , this patch upgrades the Guava version to 23.1, and I've verified locally the exception disappear and OAP starts successfully

### CODE REVIEW

**Comment by wu-sheng** [comment]
Maybe CI found the issue.

**Comment by kezhenxu94** [comment]
I've replayed the e2e tests under JDK 1.9 manually (which won't report check status back to this PR), let's wait and see the result, if it passes, I think it should **generally work on 1.9 and above**, https://builds.apache.org/job/skywalking-e2e-2/763/console

**Comment by wu-sheng** [comment]
If you see it passed, reply me here. I am using phone only, today.

**Comment by kezhenxu94** [comment]
@wu-sheng it passes under JDK 9, see the selected/highlighted words below the screenshot
image

**Comment by wu-sheng** [comment]
Cool. How about higher? 11 for example? I am thinking about we need JRE documentation update.

**Comment by kezhenxu94** [comment]
> Cool. How about higher? 11 for example? I am thinking about we need JRE documentation update.

I tested this afternoon locally with OpenJDK 12, it works fine too, so it's highly possible that it also works on JDK 10 and JDK11, do we need to replay this on the infra Jenkins?

**Comment by wu-sheng** [comment]
The infra is setting up our VM. Please submit an issue to track the higher jdk tests.

In this PR, at least, we should update document.

**Comment by kezhenxu94** [comment]
Oops, I've made a mistake that the container in which our e2e runs is based on OpenJDK8, the JDK version in `Jenkinsfile-E2E` is just for compile time only, so we'll need some real tests

**Comment by wu-sheng** [comment]
OK, so we haven't verified in 9+?

**Comment by kezhenxu94** [comment]
> OK, so we haven't verified in 9+?

I verified JDK12 locally, others are not verified yet

**Comment by kezhenxu94** [comment]
We may need much more resources if we want to verify every commit on those versions

**Comment by wu-sheng** [comment]
OK. I think 9 and 11 are LTS versions, right? We could focus on that.

**Pull request merged**
