### PR TITLE
[OAL] Keep the endpoint avg resp time meter name the same with others scope.

### PR DESCRIPTION
**Pull request by JaredTan95**
This is a minor polish.
So far, we have `cpm` , `sla`, `percentile`, `resp_time` for `service`, `instance`, `database` scope, but for `endpoint`, `endpoint_avg` not keep the same format of `_resp_time`.

And, we also need to update the query parameter in `UI` query/repo.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why do we suddenly change this? I am fine but just curious.

**Comment by wu-sheng** [comment]
This could break 3rd party integration, so, I want to know why.

**Comment by JaredTan95** [comment]
> Why do we suddenly change this? I am fine but just curious.

In order to make the user experience better, for example, when users configure alarm rules, the avg response time of the endpoint can be configured as naturally as the avg response time of the service/instance, rather than making endpoint avg unique. It looks a bit weird, and users will think that there is something specially designed in it?

**Comment by JaredTan95** [comment]
> This could break 3rd party integration, so, I want to know why.

If it involves large changes or coordination troubles, we can still use the original name

**Comment by wu-sheng** [comment]
> > Why do we suddenly change this? I am fine but just curious.
> 
> 
> 
> In order to make the user experience better, for example, when users configure alarm rules, the avg response time of the endpoint can be configured as naturally as the avg response time of the service/instance, rather than making `endpoint_avg` unique. It looks a bit weird, and users will think that there is something specially designed in it?

No specific reason. I believe this is a mistake. If we plan to fix, let us be clear this is a break change in the change log, and search all docs, whether OAL and alarm docs affected by this break.

**Comment by JaredTan95** [comment]
> > > Why do we suddenly change this? I am fine but just curious.
> > 
> > 
> > In order to make the user experience better, for example, when users configure alarm rules, the avg response time of the endpoint can be configured as naturally as the avg response time of the service/instance, rather than making `endpoint_avg` unique. It looks a bit weird, and users will think that there is something specially designed in it?
> 
> No specific reason. I believe this is a mistake. If we plan to fix, let us be clear this is a break change in the change log, and search all docs, whether OAL and alarm docs affected by this break.

Okay

**Comment by wu-sheng** [comment]
Waiting for all e2e passed.

**Comment by JaredTan95** [comment]
> I noticed `endpoint_avg` exists in the GraphQL protocol files(comments), `metrics.graphqls` and `metrics-v2.graphqls`. Could you fix them as well?

ok

**Comment by wu-sheng** [comment]
Please update the submodule and check whether there is UT failing.

**Comment by JaredTan95** [comment]
CI failed looks like timeout, and I tested ok locally.

**Comment by wu-sheng** [comment]
Oh.. [ui-configuration.graphqls](https://github.com/apache/skywalking-query-protocol/compare/d6e294735ab43b2fa9e70b11c91d85268591dec0...3dd9ea164a6699d9e11678c9c039c4d999b6546b#diff-6aff06ba444cee4695a7b03480c317f756fc406afe6beebe4eb4e76cc35a919a) will be merged, I think we can't sync the submodule for now. 

https://github.com/apache/skywalking/issues/8477 is only going to be taken care of by @wankai123 after booster UI is ready.

**Comment by wu-sheng** [comment]
We need a submodule rollback, sorry, I forgot the breaking change.

**Review by wu-sheng — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
