### PR TITLE
Add FluentBit integration E2E test and doc

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>. NO
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
FYI @hailin0

**Review by wu-sheng — APPROVED** [review]
FYI @Shikugawa, @kezhenxu94 found a way to use fluentbit directly by using LUA script.

Once e2e passed, it works for me.

**Comment by Shikugawa** [comment]
@wu-sheng Using lua is not enough for the real use-case. It is because it can't modify request headers...

**Comment by wu-sheng** [comment]
> @wu-sheng I'm not sure about how much we affected by performance issue by using lua filter. But it seems enough to have.

Native one is always better to have and have better performance, AFAIK. I just want to inform you, before yours gets merged, we still have an option.

**Pull request merged**
