### PR TITLE
 update dependencyManagement

### PR DESCRIPTION
**Pull request by IanCao**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by IanCao** [comment]
@wu-sheng @peng-yongsheng Hi, i have added those third-party libraries into oap's dependency manager according to the current state

**Comment by peng-yongsheng** [comment]
@IanCao Thank you very much, I will merge this into the master after compile finished. cc @wu-sheng

**Comment by wu-sheng** [comment]
@peng-yongsheng If this versions of libs are the current ones, merge this please.

**Comment by peng-yongsheng** [comment]
> @peng-yongsheng If this versions of libs are the current ones, merge this please.

I had been compared them with the 6.1.0 release library. That all right.

**Pull request merged**
