### PR TITLE
 Provide plugin for ShardingSphere (#2699)

### PR DESCRIPTION
**Pull request by tuohai666**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
___
### New feature or improvement
- For #2699

### CODE REVIEW

**Comment by wu-sheng** [comment]
Ping @ascrutae when this is ready to test.

**Comment by ascrutae** [comment]
got it


Original Message
Sender:吴晟 Wu Shengnotifications@github.com
Recipient:apache/skywalkingskywalking@noreply.github.com
Cc:Zhang" zhangxin@apache.org; Mentionmention@noreply.github.com
Date:Wednesday, May 22, 2019 17:13
Subject:Re: [apache/skywalking] Provide plugin for ShardingSphere (#2699)(#2727)


Ping @ascrutae when this is ready to test.

**Comment by tuohai666** [comment]
@ascrutae , just reminder, please help to review this plugin and its test case.

**Comment by wu-sheng** [comment]
@ascrutae Please review and test this plugin with this test, https://github.com/SkyAPMTest/agent-auto-integration-testcases/pull/73

**Comment by wu-sheng** [comment]
@tuohai666 You at least change 10+ files, but GitHub can't show the difference, and I think those should not be changed. Could you recheck what happen?

**Comment by tuohai666** [comment]
> @tuohai666 You at least change 10+ files, but GitHub can't show the difference, and I think those should not be changed. Could you recheck what happen?

OK. I'll find out what happend.

**Comment by tuohai666** [comment]
@wu-sheng There're 26 no changes files in this pr, yes they are identical with original files in content. I have compared their hexadecimal data and proved the equivalence. Github point out these files due to their access permission changed(from 755 to 644).

For *.sh files, I need to revert the permission to 755. 
For text files like *.java, *.proto and LICENSE files I suggest keep the modification.

**Will revert 644 to 755 (.sh files):**
`docker/oap/docker-entrypoint.sh (Take this one to illustrate)`
original:
image
in my pr:
image
And another two:
```
docker/ui/docker-entrypoint.sh
tools/releasing/create_source_release.sh
```

**Suggest to keep 644(.java, .proto and LICENSE files):**
`apm-dist/release-docs/licenses/ui-licenses/LICENSE-popperjs (Take this one to illustrate)`
original:
image
in my pr:
image
The others:
```
apm-dist/release-docs/licenses/ui-licenses/LICENSE-vue-datepicker-local
...t-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/DynamicPluginLoader.java 
...c/main/java/org/apache/skywalking/apm/agent/core/plugin/loader/InstrumentationLoader.java 
apm-sniffer/apm-sdk-plugin/h2-1.x-plugin/pom.xml
apm-sniffer/apm-sdk-plugin/jdbc-commons/pom.xml
...n/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/ConnectionTracing.java
apm-sniffer/apm-sdk-plugin/mysql-5.x-plugin/pom.xml
apm-sniffer/apm-sdk-plugin/mysql-6.x-plugin/pom.xml
apm-sniffer/apm-sdk-plugin/mysql-8.x-plugin/pom.xml
apm-sniffer/apm-sdk-plugin/mysql-common/pom.xml
apm-sniffer/apm-sdk-plugin/postgresql-8.x-plugin/pom.xml
...ETA-INF/services/org.apache.skywalking.apm.agent.core.plugin.loader.InstrumentationLoader
oap-server/server-receiver-plugin/receiver-proto/src/main/proto/google/api/annotations.proto
oap-server/server-receiver-plugin/receiver-proto/src/main/proto/google/api/http.proto
oap-server/server-receiver-plugin/receiver-proto/src/main/proto/google/rpc/code.proto
...erver/server-receiver-plugin/receiver-proto/src/main/proto/google/rpc/error_details.proto
oap-server/server-receiver-plugin/receiver-proto/src/main/proto/google/rpc/status.proto
oap-server/server-receiver-plugin/receiver-proto/src/main/proto/jaeger/collector.proto 
oap-server/server-receiver-plugin/receiver-proto/src/main/proto/jaeger/model.proto 
...eceiver-plugin/receiver-proto/src/main/proto/protoc-gen-swagger/options/annotations.proto
...-receiver-plugin/receiver-proto/src/main/proto/protoc-gen-swagger/options/openapiv2.proto
tools/releasing/generate-ui-depedencies.py 
```

**Comment by tuohai666** [comment]
Of course, I can reset them back if you are confused. 
But I think plain text reset to executable is not reasonable. 
Further more, two java files side by side, one is executable, another is not executable, is this good?
image
I'm not sure this is what you want.

**Comment by wu-sheng** [comment]
I don't know why it stays in that way. I just want to keep the PR as clean as possible.

**Comment by tuohai666** [comment]
@wu-sheng OK, done, clear now.

**Comment by wu-sheng** [comment]
Thanks

**Pull request merged**
