### PR TITLE
Branch quartz scheduler

### PR DESCRIPTION
**Pull request by IAMTJW**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why create a new one?

**Comment by IAMTJW** [comment]
> Why create a new one?

create a new branch want to do something and the old is deleted careless

**Comment by IAMTJW** [comment]
> 1. CI fails
> 2. You should not update query-protocol
> 3. The plugin test is still unprovided.

I dont konw the reason why the ' Compile all and Build docker image' is failed

**Comment by wu-sheng** [comment]
Ignore `istio-mixer-ci / build`. That is another issue.

**Pull request closed without merging**
