### PR TITLE
fix doc

### PR DESCRIPTION
**Pull request by EvanLjp**
Please answer these questions before submitting a pull request

- Why submit this pull request?
fix doc

### CODE REVIEW

**Review by kezhenxu94 — CHANGES_REQUESTED** [review]
For existing config names, we prefer to keep it as is for compatibility, your changes are breakages

**Comment by EvanLjp** [comment]
the config name is submited by me recently. And 8.2.0 has not been released, i think i can fix it

**Review by kezhenxu94 — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Comment by EvanLjp** [comment]
@wu-sheng PR fail is because of the poorly connection with central repository.
image

**Comment by wu-sheng** [comment]
I submitted a rerun.

**Pull request merged**
