### PR TITLE
Optimize the speed of UI query interface based on elasticsearch storage

### PR DESCRIPTION
**Pull request by Liu-XinYuan**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

- Related issues
#4194 
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by Liu-XinYuan** [comment]
These two parameters are passed from the front end. The backend determines which indexes the query data is based on these two times

**Comment by wu-sheng** [comment]
You have the time-related parameter already. You should not break all.

**Comment by Liu-XinYuan** [comment]
- startSecondTB and endSecondTB are not real time. 
- If I calculate the real time through these two parameters, I must get the parameter Step according to org.apache.skywalking.oap.server.core.query.DurationUtils and I must put this conversion in ElasticSearchClient. This will form a circular dependency between the library-client module and server-core

**Comment by wu-sheng** [comment]
> startSecondTB and endSecondTB are not real time.

What do you mean not real? It is the exact time the client side query. And `Downsampling` is there too. What do you need? That is all. This is just an optimization inside the ES implementation, breaking all is not a good idea.

**Comment by Liu-XinYuan** [comment]
It makes sense that I can convert to real time by downsampling and bucket.

**Pull request closed without merging**
