### PR TITLE
add ignore *.log for hs_err_pid*.log/replay_pid*.log

### PR DESCRIPTION
**Pull request by qxo**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
This pr conflicts with master. And where are these logs from?

**Comment by qxo** [comment]
> This pr conflicts with master. And where are these logs from?

hs_err_pid*.log/replay_pid*.log generated when jvm crash on maven build.

**Comment by wu-sheng** [comment]
That is unexpected, why we need to ignore those? We don't have tests for JVM crashing. The ignore file is not for all caees, it just ignore for tool config or test generated files.

**Comment by qxo** [comment]
> That is unexpected, why we need to ignore those? We don't have tests for JVM crashing. The ignore file is not for all caees, it just ignore for tool config or test generated files.

当构建时内存不足就会产生这些临时文件, we should ignore it just like target dir.

**Comment by wu-sheng** [comment]
You could have many files, such as dump file. It is not reasonable to add ignore for all.

**Pull request closed without merging**
