### PR TITLE
Fix javadoc on JDK 11

### LINKED ISSUE #5919: [JDK11] Javadoc doesn't work out.
I was facing this in the 8.3.0 release. Let's fix this and add `check` in the CI process.

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #5919.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

I passed the check on JDK11 locally(MacOS), try to find out whether there is an error on the Linux OpenJDK 11.

### CODE REVIEW

**Comment by wu-sheng** [comment]
This seems an incompatible issue between scale and javadoc.

**Review by kezhenxu94 — DISMISSED** [review]
LGTM, just wait for CI status

**Review by wu-sheng — COMMENTED** [review]
Seem like still failing
> 2020-11-30T02:12:40.9351565Z [INFO] apm-finagle-6.25.x-plugin .......................... FAILURE [ 22.089 s]

@kezhenxu94

**Comment by wu-sheng** [comment]
I am closing this, as I got the block about the old scala plugin. `finagle-6.25.x-plugin`.

**Pull request closed without merging**
