### PR TITLE
Update FileWriter.java

### PR DESCRIPTION
**Pull request by mainColorZwh**
file "apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/logging/core/FileWriter.java",add  volatile to field "FileWriter INSTANCE" to avoid Instruction reordering.if no volatile , client may get an "FileWriter INSTANCE" that have not been constructed compeletly.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
This constructor should be called as soon as the agent main entrance loaded, as `SnifferConfigInitializer` has `LOGGER = LogManager.getLogger(SnifferConfigInitializer.class);`. Which case could cause the issue you describe? Do you face any real-world issue?

**Comment by mainColorZwh** [comment]
> This constructor should be called as soon as the agent main entrance loaded, as `SnifferConfigInitializer` has `LOGGER = LogManager.getLogger(SnifferConfigInitializer.class);`. Which case could cause the issue you describe? Do you face any real-world issue?

1.This constructor first called at 'PluginBootstrap.loadPlugins()' method (en... I have debugged for that). 
2.FileWriter use singleton of double-check type to prevent concurrent problem ,  I just find that it is not a standard double-check type.It may be hard to produce the scenario because of low probability.
3.git hub dont support insert a picture ,so I attach a picture to explain more details at link [https://blog.csdn.net/dshf_1/article/details/109614612](blog)

**Comment by wu-sheng** [comment]
I could understand officially this is not standard, yes, you are correct. But, the issue is, if you add `volatile`, there would be unnecessary performance cost. Actually, the whole double-check is not necessary :) Like you have debugged, there is no concurrency case in the boot stage.

**Comment by mainColorZwh** [comment]
> I could understand officially this is not standard, yes, you are correct. But, the issue is, if you add `volatile`, there would be unnecessary performance cost. Actually, the whole double-check is not necessary :) Like you have debugged, there is no concurrency case in the boot stage.

**Comment by mainColorZwh** [comment]
en ...thanks for your particutar explain:)

**Pull request closed without merging**
