### PR TITLE
issue 3713 - Cannot get the TID using the ConsoleAppender + LogstashE…

### PR DESCRIPTION
**Pull request by dagmom**
…ncoder + TradeIdJsonProvider in logback.xml

Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

issue 3713
___
### New feature or improvement

- How to fix?
 `LogstashTcpSocketAppender` enhance class put `TID` to `ILoggingEvent`, but `ConsoleAppender` don't use `ILoggingEvent` , so enhance `TraceIdJsonProvider` class and set traceId

### CODE REVIEW

**Comment by zhaoyuguang** [comment]
The following two problems were found
1 org.apache.commons.lang3.StringUtils class not found
image

2 why use `allArguments[0]` getTracingId has no args
image

**Comment by zhaoyuguang** [comment]
@dagmom 
What kind of demo, The code logic will go here?
image

**Comment by dagmom** [comment]
> @dagmom
> What kind of demo, The `TraceIdJsonProviderInterceptor.java` code logic will go here?
> image

@zhaoyuguang Maybe async log enhance by `AsyncAppenderBaseMethodInterceptor`,let me verify that.

**Comment by dagmom** [comment]
image


image

**Comment by zhaoyuguang** [comment]
Sorry for the delay, I'm will testing asynchrony as soon

**Comment by zhaoyuguang** [comment]
LGTM  @dagmom  Please deal `This branch is out-of-date with the base branch`

**Pull request merged**
