### PR TITLE
Add UI templates

### PR DESCRIPTION
**Pull request by kezhenxu94**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Wait for @Fine0830 to confirm

**Comment by wu-sheng** [comment]
Do you two have test env to verify?

**Review by Fine0830 — COMMENTED** [review]
`Topology Instance` and `Topology Endpoint` also need types(like default, tcp) in the `configuration`.

**Review by Fine0830 — APPROVED** [review]

**Comment by wu-sheng** [comment]
Storage e2e tests fail? Any change relates to this?

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
