### PR TITLE
[WIP] Add OAP+Istio(mixer) to CI pipeline

### PR DESCRIPTION
**Pull request by innerpeacez**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [X] New feature provided
- [ ] Improve performance

I will complete #3771 follow-up tasks in this PR.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please open `pull request` on GitHub action YAML, https://github.com/apache/skywalking/blob/istio-ci/.github/workflows/istio-mixer-ci.yaml#L19. Otherwise, nothing happens for this.

**Comment by wu-sheng** [comment]
@innerpeacez @hanahmily As we are using GitHub action, which is pretty very safe for CI process, and current status is passed. Could we merge the `istio-ci` into the master? Also, move the `install` folder to `test/e2e-mixer/install` and other mixer tests in `test/e2e-mixer` by following the current folder style?

**Comment by hanahmily** [comment]
I prefer to leave install folder alone for our users to install mixer
adapter and OAP with its help

**Comment by wu-sheng** [comment]
Please merge #3902 first, then we could submit PR to master directly.

**Pull request closed without merging**
